/* global console, process, fetch, Buffer */
// Claims each real company for its test founder, then approves the claims as
// the founder's own platform-admin account (2026-10-08, after the claim-flow
// fixes F1/F2/F4). Every person here is a test persona on a plus-alias of the
// founder's own inbox (docs/seed/real-companies/LOGINS.md); nobody at these
// companies is contacted. The registry document is a generated one-page PDF
// that says, on its face, that it is a test document and not a registry
// record.
//
// Through the app's own API only, as each person:
//   founder: find the company (GET /v1/companies/claimable), claim it with
//            REGISTRY_DOCUMENT, attach the PDF (direct upload to private
//            storage, then .../evidence/complete)
//   admin:   step up with a fresh token, list the claims queue, approve each
//            seeded claim that has its document (an approval makes the founder
//            the company's first owner; the canonical company is unchanged)
//
//   node scripts/seed/real-companies/claim-all.mjs           plan only (default)
//   node scripts/seed/real-companies/claim-all.mjs --apply   claim and approve
//   ... --apply --claims-only | --approve-only
//
// Needs SUPABASE_ACCESS_TOKEN (management API, to mint sign-in tokens without
// sending email). CQ_API_URL overrides the API (default: production). Never
// prints a token.
import * as lib from "../tavus20/lib.mjs";
import { FOUNDERS } from "./accounts.mjs";

const ADMIN_EMAIL = "adedaniel502@gmail.com";
const apply = process.argv.includes("--apply");
const claimsOnly = process.argv.includes("--claims-only");
const approveOnly = process.argv.includes("--approve-only");
const REASON =
  "Seeded test persona (claim-all.mjs, 2026-10-08): generated test registry document, founder's own test account.";

const slug = (s) =>
  s
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

/** A one-page PDF that names itself a test document (valid xref offsets). */
export function testRegistryPdf(companyName) {
  const safe = (text) => text.replace(/[\\()]/g, (c) => `\\${c}`);
  const lines = [
    "TEST DOCUMENT - NOT A REGISTRY RECORD",
    `Company: ${companyName}`,
    "Generated by Capital Q seed script claim-all.mjs for a test persona.",
    `Date: ${new Date().toISOString().slice(0, 10)}`,
  ];
  const stream = [
    "BT /F1 14 Tf 72 720 Td",
    ...lines.map(
      (line, i) => `${i === 0 ? "" : "0 -24 Td "}(${safe(line)}) Tj`,
    ),
    "ET",
  ].join("\n");
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
    `<< /Length ${Buffer.byteLength(stream, "latin1")} >>\nstream\n${stream}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];
  let body = "%PDF-1.4\n";
  const offsets = [];
  objects.forEach((object, i) => {
    offsets.push(Buffer.byteLength(body, "latin1"));
    body += `${i + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xref = Buffer.byteLength(body, "latin1");
  body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) {
    body += `${String(offset).padStart(10, "0")} 00000 n \n`;
  }
  body += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return Buffer.from(body, "latin1");
}

async function claimAs(founder) {
  const token = await lib.accessToken(founder.email);
  const found = await lib.call(
    lib.API,
    token,
    "GET",
    `/v1/companies/claimable?q=${encodeURIComponent(founder.company)}`,
  );
  if (found.status !== 200) {
    return `search HTTP ${found.status}`;
  }
  const company = (found.body.companies ?? []).find(
    (c) => c.name.toLowerCase() === founder.company.toLowerCase(),
  );
  if (company === undefined) return "not found among claimable companies";
  if (company.yours) return "already theirs";
  if (company.members > 0)
    return `has ${company.members} member(s); not a claim`;
  if (!apply) return `would claim ${company.companyId}`;

  const claim = await lib.call(
    lib.API,
    token,
    "POST",
    `/v1/companies/${company.companyId}/claim-requests`,
    {
      method: "REGISTRY_DOCUMENT",
      clientRequestId: `claim-all-${slug(founder.company)}`.slice(0, 128),
    },
    `claim-all-${slug(founder.company)}`,
  );
  if (claim.status !== 201 && claim.status !== 200) {
    return `claim HTTP ${claim.status}`;
  }
  const pdf = testRegistryPdf(founder.company);
  const upload = await lib.call(
    lib.API,
    token,
    "POST",
    `/v1/companies/${company.companyId}/claim-requests/evidence`,
    {
      fileName: `${slug(founder.company)}-test-registry-document.pdf`,
      contentType: "application/pdf",
      sizeBytes: pdf.length,
    },
  );
  if (upload.status !== 200 || upload.body.status !== "READY") {
    return `claim ${claim.body.status}; evidence upload HTTP ${upload.status} ${upload.body?.status ?? ""}`;
  }
  const put = await fetch(upload.body.upload.url, {
    method: "PUT",
    headers: upload.body.upload.headers,
    body: pdf,
  });
  if (!put.ok)
    return `claim ${claim.body.status}; storage PUT HTTP ${put.status}`;
  const done = await lib.call(
    lib.API,
    token,
    "POST",
    `/v1/companies/${company.companyId}/claim-requests/evidence/complete`,
    {},
  );
  return `claim ${claim.body.status}; evidence ${done.body?.status ?? done.status}`;
}

async function approveAll() {
  const token = await lib.accessToken(ADMIN_EMAIL);
  const queue = await lib.call(
    lib.API,
    token,
    "GET",
    "/v1/admin/company-claims",
  );
  if (queue.status !== 200) {
    console.log(
      `admin queue HTTP ${queue.status} (is the account a platform admin?)`,
    );
    return;
  }
  const wanted = new Map(FOUNDERS.map((f) => [f.company.toLowerCase(), f]));
  const mine = (queue.body.claims ?? []).filter((c) => {
    const founder = wanted.get(c.companyName.toLowerCase());
    return (
      founder !== undefined &&
      c.method === "REGISTRY_DOCUMENT" &&
      // A claimant with no workspace yet has no display name in the queue.
      (c.requesterName === founder.name || c.requesterName == null)
    );
  });
  if (!apply) {
    for (const c of mine) {
      console.log(
        `would approve\t${c.companyName}\t${c.evidence ? "document attached" : "NO document"}`,
      );
    }
    return;
  }
  const stepUp = await lib.call(lib.API, token, "POST", "/v1/admin/step-up", {
    accessToken: token,
  });
  if (stepUp.status !== 200) {
    console.log(`step-up HTTP ${stepUp.status}; nothing approved`);
    return;
  }
  for (const c of mine) {
    if (!c.evidence) {
      console.log(`skip\t${c.companyName}\tno document attached`);
      continue;
    }
    const decided = await lib.call(
      lib.API,
      token,
      "POST",
      `/v1/admin/company-claims/${c.requestId}/decision`,
      { approve: true, reason: REASON },
      `claim-all-approve-${c.requestId}`,
    );
    console.log(
      `${decided.status === 200 ? "approved" : `HTTP ${decided.status}`}\t${c.companyName}`,
    );
  }
}

if (process.argv[1]?.endsWith("claim-all.mjs")) {
  console.log(`API ${lib.API}${apply ? "" : " (plan only; --apply to act)"}`);
  if (!approveOnly) {
    for (const founder of FOUNDERS) {
      const outcome = await claimAs(founder).catch(
        (error) =>
          `failed: ${error instanceof Error ? error.message : "error"}`,
      );
      console.log(`${founder.company}\t${founder.email}\t${outcome}`);
    }
  }
  if (!claimsOnly) await approveAll();
}
