/**
 * One line-icon system (Lucide, doc 18 §31), curated and re-exported so
 * product code never imports the icon library directly. Sizes: 16 compact,
 * 18 regular, 20 prominent; stroke 1.75.
 *
 * The Q mark is not an icon and is not exported from here.
 */
export {
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  Bookmark,
  BookmarkCheck,
  Building2,
  Captions,
  CaptionsOff,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleUser,
  Compass,
  Download,
  Eye,
  FileText,
  Globe,
  Handshake,
  History,
  Home,
  Info,
  Keyboard,
  Landmark,
  Lock,
  MessageSquare,
  Mic,
  MicOff,
  Monitor,
  Moon,
  MoreHorizontal,
  Move,
  PanelLeft,
  PanelRight,
  Pause,
  Pin,
  PinOff,
  Play,
  Plus,
  Presentation,
  Settings,
  Share2,
  SlidersHorizontal,
  Sparkle,
  Square,
  Sun,
  Upload,
  Users,
  Volume2,
  VolumeX,
  Wifi,
  WifiOff,
  X,
} from "lucide-react";

export const ICON_SIZE = {
  compact: 16,
  regular: 18,
  prominent: 20,
} as const;

export const ICON_STROKE = 1.75;
