"""Advance widths (per 1000 em) for each bundled deck face, as a TS module.

Run: python3 -I gen_metrics.py <packages/deck-render/fonts> <packages/deck-render/src/metrics.ts>
"""
import os, sys
from fontTools.ttLib import TTFont

fonts_dir, out = sys.argv[1], sys.argv[2]
FACES = {
    "INTER": "Inter-Regular.ttf",
    "INTER_SEMIBOLD": "Inter-SemiBold.ttf",
    "INTER_DISPLAY": "InterDisplay-SemiBold.ttf",
    "SOURCE_SERIF_DISPLAY": "SourceSerif4Display-SemiBold.ttf",
    "FRAUNCES": "Fraunces-SemiBold.ttf",
    "PLEX_SERIF": "IBMPlexSerif-SemiBold.ttf",
    "NOTO": "NotoSans-Regular.ttf",
    "NOTO_BOLD": "NotoSans-Bold.ttf",
}
# ASCII printable, Latin-1 + Latin Extended-A, general punctuation, currency, arrows.
RANGE = (
    list(range(0x20, 0x7F)) + list(range(0xA0, 0x180)) + list(range(0x2010, 0x2040))
    + list(range(0x20A0, 0x20C0)) + [0x2190, 0x2192, 0x2212]
)
lines = [
    "// Generated by gen_metrics.py (docs/design/2026-10-08/deck-quality/fonts/)",
    "// from the bundled faces in ../fonts. Do not edit by hand: regenerate.",
    "",
    "/** Codepoints the tables cover, in order (comma-separated). */",
    f"export const METRIC_CODEPOINTS =\n  \"{','.join(str(c) for c in RANGE)}\";",
    "",
    "/** Advance width per 1000 em for each codepoint above; 0 = no glyph. */",
    "export const FACE_METRICS = {",
]
for key, file in FACES.items():
    font = TTFont(os.path.join(fonts_dir, file))
    upm = font["head"].unitsPerEm
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]
    widths = []
    for cp in RANGE:
        g = cmap.get(cp)
        widths.append(0 if g is None else round(hmtx[g][0] * 1000 / upm))
    lines.append(f"  {key}:\n    \"{','.join(str(w) for w in widths)}\",")
lines.append("} as const;")
lines.append("")
lines.append("export type FaceKey = keyof typeof FACE_METRICS;")
open(out, "w").write("\n".join(lines) + "\n")
print("ok", len(RANGE))
