from common import *


def deck(**s):
    order = ["problem", "solution", "value_proposition", "market", "go_to_market",
             "business_model", "traction", "competition", "financials", "the_ask",
             "founders", "team"]
    assert list(s) == order, list(s)
    return [{"section": k, "content": v} for k, v in s.items()]


# ---------------------------------------------------------------- 1 Ledgerline
def c1():
    mrr = geo(19_600_000, 38_000_000)
    cust = geo(590, 1140)
    cap = capital(
        1_800_000, "USD", "SAFE (post-money)", "valuationCap", 14_000_000, "2026-12-18", 50_000,
        [("Engineering and FIRS e-invoicing integration", 35), ("Sales and accountant partner channel", 30),
         ("Customer success and onboarding", 20), ("Compliance reserve and working capital", 15)],
        rounds(("Angel", "2023-06-20", 90_000, "USD", "SAFE (post-money)", "Founder friends and former colleagues"),
               ("Pre-seed", "2024-02-12", 350_000, "USD", "SAFE (post-money)", "Harmattan Angels Syndicate")),
        ["Harmattan Angels Syndicate", "Ikoyi Operators Fund", "Twelve individual angels (tax and banking operators)"],
        410_000, 39_000, 85_000)
    return dict(
        legalName="Ledgerline Technologies Limited", websiteUrl="https://ledgerline.example",
        foundedDate="2023-03-14", headquarters={"city": "Lagos", "country": "NG"}, currentStageCode="seed",
        headcount=26,
        shortDescription="Ledgerline checks every invoice at creation and files VAT returns for Nigerian SMEs, ready for FIRS e-invoicing.",
        primaryDescription=("Ledgerline is VAT compliance software for Nigerian small and medium businesses. It connects to the invoicing and accounting tools a business already uses, validates each invoice as it is created, and prepares and files the monthly VAT return. "
                            "The FIRS e-invoicing rollout means invoice data must be correct at source, which is where most SME penalties start today. "
                            "Ledgerline charges a monthly subscription per legal entity and serves 1,140 paying businesses at about ₦38m in monthly recurring revenue. "
                            "Six-month logo retention is 96%."),
        tags={"industry": ["fintech", "enterprise_software"], "business_model": ["b2b_saas"],
              "customer_type": ["small_business", "business_customer"], "geography": ["nigeria", "west_africa", "africa"],
              "other": ["regulated_financial_services", "workflow_automation"]},
        keywords=["VAT compliance", "e-invoicing", "FIRS", "tax filing", "Nigeria SME", "invoice validation",
                  "regtech", "accounting integration", "VAT returns", "Lagos", "tax automation", "SME software"],
        brand={"primary": "#1F5C4A", "accent": "#E3B23C", "ink": "#14201C",
               "logoConcept": "Lowercase l resting on a single ruled ledger line"},
        founderPerson=dict(
            name="Tobenna Okafor", role="Co-founder & CEO", appRole="OWNER", age=34, nationality="Nigerian", gender="male",
            city="Lagos", education=["BSc Accounting, University of Nigeria, Nsukka (2013)", "ACA, Institute of Chartered Accountants of Nigeria (2017)"],
            previousRoles=[{"title": "Graduate Trainee, Audit", "org": "Mid-tier accounting firm, Lagos", "from": 2014, "to": 2015},
                           {"title": "Tax Manager, Indirect Tax (VAT)", "org": "Big Four firm, Lagos", "from": 2015, "to": 2022},
                           {"title": "Independent VAT adviser to SMEs", "org": "Self-employed", "from": 2022, "to": 2023}],
            headline="Co-founder & CEO, Ledgerline | Ex-Big Four tax manager | Making VAT boring again for Nigerian SMEs",
            professionalSummary="Chartered accountant who spent seven years in a Big Four tax practice in Lagos, filing VAT returns by hand for mid-sized and small clients. Built Ledgerline's first validation rules from the errors he corrected by hand.",
            backgroundSummary="Grew up in Enugu, moved to Lagos for national service and stayed. Started Ledgerline after realising most VAT penalties he handled traced back to invoices that were wrong when they were issued.",
            languages=["English", "Igbo", "Nigerian Pidgin"]),
        team=[person("Funmilayo Adebayo", "Co-founder & CTO", "ADMIN", "Backend engineer; previously led the payments ledger team at a Lagos fintech. Owns the invoice validation engine and FIRS integration.", "Nigerian", "female"),
              person("Emeka Chukwu", "Head of Partnerships", "MEMBER", "Former practice manager at a mid-tier accounting firm. Runs the accountant referral channel that brings in about 40% of new entities.", "Nigerian", "male"),
              person("Zainab Lawal", "Head of Customer Success", "MEMBER", "Joined from a business banking support team. Leads onboarding, aiming for a first filed return within ten days of sign-up.", "Nigerian", "female")],
        capital=cap,
        metrics=metrics([("mrr", "Monthly recurring revenue", "money", "NGN"),
                         ("paying_businesses", "Paying businesses", "count", None),
                         ("logo_retention_6m_pct", "Six-month logo retention", "percent", None),
                         ("invoices_validated", "Invoices validated in month", "count", None)],
                        {"mrr": mrr, "paying_businesses": cust,
                         "logo_retention_6m_pct": [94.8, 95.1, 95.4, 95.6, 95.9, 96.0, 96.1, 96.0],
                         "invoices_validated": geo(41_000, 96_000)},
                        "MRR divided by paying businesses holds near ₦33,300 per business per month. USD figures in the deck use ₦1,550/USD."),
        deck=deck(
            problem=["Nigerian SMEs pay accountants to file VAT and are still penalised, because invoice data is wrong when it is issued.",
                     "Returns are rebuilt each month by copying numbers between spreadsheets.",
                     "The FIRS e-invoicing rollout moves validation to the point of invoicing, so bad data becomes a filing failure, not a later correction."],
            solution=["Ledgerline connects to the invoicing and accounting tools a business already uses.",
                      "Every invoice is checked as it is created (TIN, VAT treatment, sequence, totals).",
                      "The monthly VAT return is prepared and filed from validated data. Nobody re-types anything."],
            value_proposition=["Fewer penalties: errors are caught when the invoice is raised, not at month end.",
                               "Lower cost than an outsourced filing retainer for most SMEs.",
                               "Ready for e-invoicing without changing the tools staff already use."],
            market=["Method: bottom-up count of VAT-filing businesses multiplied by an annual compliance software spend.",
                    "TAM: about 420,000 VAT-filing businesses × ₦400,000 a year = ₦168bn (about $108m).",
                    "SAM: 140,000 businesses in Lagos, Abuja and Port Harcourt already invoicing digitally = ₦56bn.",
                    "SOM: 12,000 entities by 2029 = ₦4.8bn ARR."],
            go_to_market=["Accountant and tax-practitioner referral channel (about 40% of new entities today).",
                          "Integrations listed inside the accounting tools SMEs already use.",
                          "Direct sales to multi-entity groups ahead of each e-invoicing phase deadline."],
            business_model=["Per-entity monthly subscription: Starter ₦18,000, Growth ₦42,000 (multi-branch, unlimited invoices).",
                            "Accountant plan at ₦12,500 per client entity.",
                            "Blended revenue of about ₦33,300 per business per month; gross margin 78%."],
            traction=["1,140 paying businesses, up from 590 twelve months ago.",
                      "₦38m MRR (about ₦456m annualised).",
                      "96% logo retention over six months.",
                      "96,000 invoices validated in September 2026."],
            competition=["Sage, QuickBooks Online and Zoho Books create invoices but do not file Nigerian VAT returns.",
                         "Traditional tax consultants file returns but fix errors after the fact, at higher cost.",
                         "Ledgerline sits between the two: validation at source plus filing, priced as software."],
            financials=["FY2027 revenue ₦780m, FY2028 ₦1.65bn, FY2029 ₦3.1bn (base case).",
                        f"Monthly net burn today about ${cap['monthlyNetBurn']['amount']:,}; peaks near ${cap['plannedMonthlyNetBurnPostRaise']['amount']:,} after the raise.",
                        f"Runway after the raise is about {cap['runwayMonthsPostRaise']:.0f} months; break-even planned for Q3 2028."],
            the_ask=["Raising a $1.8m seed on a post-money SAFE.",
                     "Use of funds: 35% engineering and FIRS integration, 30% sales and partner channel, 20% customer success, 15% compliance reserve."],
            founders=["Tobenna Okafor, CEO: chartered accountant, seven years as a tax manager in Lagos.",
                      "Funmilayo Adebayo, CTO: built payment ledgers at a Lagos fintech before Ledgerline."],
            team=["26 people in Lagos: 11 engineering, 7 customer success, 5 sales and partnerships, 3 operations.",
                  "Hiring a head of finance and two integration engineers from this round."]),
        deckGaps=[],
        dataRoom=standard_room(
            "Ledgerline Technologies Limited", "the Corporate Affairs Commission (CAC), Nigeria", "RC 6894215", "2023-03-14",
            [("Tobenna Okafor", 41), ("Funmilayo Adebayo", 29), ("Employee option pool", 10),
             ("Harmattan Angels Syndicate", 8.5), ("Ikoyi Operators Fund", 6.5), ("Individual angels", 5)],
            10, "Four-year vesting with a one-year cliff; 214,000 options granted to 17 staff.",
            ["Monthly P&L, balance sheet and cash flow in naira, prepared by an external accountant.",
             "Revenue grew from ₦19.6m in Oct 2025 to ₦38.0m in Sep 2026.",
             "Gross margin 78%; payroll is 64% of operating cost.",
             "Cash at 30 Sep 2026: about $410,000 equivalent across naira and dollar accounts."],
            "FIRS Tax Clearance Certificate (2026)",
            ["Tax Clearance Certificate issued by FIRS covering the 2023, 2024 and 2025 years of assessment.",
             "Monthly VAT returns filed on time since incorporation (filed through Ledgerline's own product).",
             "Withholding tax and PAYE remittance schedules for the last 12 months attached."],
            ["Deeds of assignment from both co-founders covering all code, rules and trademarks.",
             "Standard IP clause in all 26 employment contracts.",
             "'Ledgerline' word mark application filed with the Trademarks Registry, Abuja (pending)."],
            ("Key customer contract summary: Adunni Foods Distribution Ltd",
             ["14 legal entities on the Growth plan; 24-month term from March 2026.",
              "Annual value ₦7.06m, invoiced monthly; 30 days' termination for cause only.",
              "Service level: returns prepared five working days before the FIRS deadline.",
              "Customer data processed under a data processing agreement aligned to the Nigeria Data Protection Act."]),
            ("Board minutes, Q2 2026",
             ["Approved the seed fundraising plan and the post-money SAFE terms.",
              "Reviewed churn: 11 entities lost in the quarter, 7 due to business closure.",
              "Approved hiring plan of 9 roles conditional on closing the round.",
              "Noted the FIRS e-invoicing timeline update and integration testing status."]),
            ("Founder and company KYC pack",
             ["CAC status report and Form CAC 7 (particulars of directors).",
              "Directors' BVN verification and government ID.",
              "Proof of registered office address (utility bill, 2026).",
              "Beneficial ownership declaration."]),
            [("FIRS e-invoicing integration test report", "legal_ip", "ON_REQUEST",
              ["Results of integration testing against the FIRS e-invoicing sandbox, July 2026.",
               "Covers invoice submission, validation responses and error handling.",
               "Lists the four open issues and fix dates."]),
             ("Unit economics and cohort workbook", "financials", "SHARED_ONLY",
              ["Monthly cohorts from March 2024 to September 2026.",
               "Customer acquisition cost by channel: accountant referral ₦61,000, direct ₦148,000.",
               "Payback period of about 3 months on accountant referrals.",
               "Logo and revenue retention by cohort."])]),
        qGuide=["Lead with the problem: SMEs are penalised because invoice data is wrong at source.",
                "Use plain numbers: 1,140 paying businesses, about ₦38m MRR, 96% six-month logo retention.",
                "Say naira first, then dollars, and state the exchange rate used.",
                "Do not call us an accounting app. We validate invoices and file VAT; we do not keep the books.",
                "Never imply FIRS endorses Ledgerline. We integrate with the e-invoicing system; that is all.",
                "If asked about churn, give the real number and the reasons, including business closures.",
                "Keep customer names private unless they have agreed to be named.",
                "Do not share cap table or unit economics without my approval.",
                "I prefer warm, measured language. No hype, no 'revolutionising tax'.",
                "If an investor asks something you do not know, say so and offer to bring it to me."],
        qPersonality="WARM",
        gateqAnswers={"sector": "Fintech / RegTech: VAT and e-invoicing compliance SaaS", "stage": "seed",
                      "geography": "Lagos, Nigeria; customers across Nigeria",
                      "chequeNeed": {"targetRaise": 1_800_000, "minimumCheque": 50_000, "currency": "USD"},
                      "traction": "1,140 paying businesses; ₦38m MRR; 96% six-month logo retention",
                      "teamSize": 26})


# ---------------------------------------------------------------- 2 Termly
def c2():
    fam = [1150, 1420, 3900, 4300, 6100, 6200, 6350, 9400]
    rev = [round(f * 2362.5) for f in fam]  # ₦210k avg term fee x 4.5% take, spread over 4 months
    cap = capital(
        600_000, "USD", "SAFE (post-money)", "valuationCap", 5_000_000, "2026-12-11", 15_000,
        [("Credit and collections operations", 30), ("School partnerships team (Lagos and Abuja)", 30),
         ("Product and engineering", 25), ("First-loss reserve for the lending partner", 15)],
        rounds(("Angel", "2025-01-15", 120_000, "USD", "SAFE (post-money)", "Yaba Mothers Circle (angel group)")),
        ["Yaba Mothers Circle", "Three individual angels from Lagos banking"],
        95_000, 18_000, 30_000)
    return dict(
        legalName="Termly Edupay Limited", websiteUrl="https://termly-pay.example",
        foundedDate="2024-08-05", headquarters={"city": "Lagos", "country": "NG"}, currentStageCode="pre_seed",
        headcount=11,
        shortDescription="Termly lets Lagos parents spread school fees across the term while the school is paid in full on day one.",
        primaryDescription=("Termly is a school-fee instalment service for Nigerian families. Schools sign up and offer Termly at enrolment; parents spread the fee across the term, and the school receives the full amount on the first day. "
                            "The instalments are funded through a credit line from a partner microfinance bank, with Termly running underwriting and collections. "
                            "212 partner schools and about 9,400 families are on plans, with a 1.6% default rate. "
                            "Schools pay a platform fee and parents pay a small instalment fee."),
        tags={"industry": ["fintech", "education"], "business_model": ["transaction_fee"],
              "customer_type": ["consumer", "business_customer"], "geography": ["nigeria", "west_africa", "africa"],
              "other": ["digital_lending", "embedded_finance", "financial_inclusion"]},
        keywords=["school fees", "instalments", "buy now pay later", "education payments", "Lagos parents",
                  "consumer credit", "private schools", "Nigeria", "embedded lending", "fee collection", "edfin"],
        brand={"primary": "#E2563B", "accent": "#2B4C7E", "ink": "#1E1A1A",
               "logoConcept": "A small calendar block split into three term bars"},
        founderPerson=dict(
            name="Adaeze Nwosu", role="Founder & CEO", appRole="OWNER", age=29, nationality="Nigerian", gender="female",
            city="Lagos", education=["BSc Economics, University of Lagos (2018)"],
            previousRoles=[{"title": "Collections Officer", "org": "Microfinance bank, Lagos", "from": 2019, "to": 2021},
                           {"title": "Collections Team Lead", "org": "Microfinance bank, Lagos", "from": 2021, "to": 2024}],
            headline="Founder & CEO, Termly | School fees in instalments, schools paid on day one",
            professionalSummary="Five years in microfinance collections in Lagos, ending as team lead for a 14-person collections desk. Knows what makes repayment work and what makes it fail.",
            backgroundSummary="Watched her older sister borrow from three people every September to pay school fees. Started Termly in 2024 to give families a plan instead of a scramble.",
            languages=["English", "Igbo", "Yoruba", "Nigerian Pidgin"]),
        team=[person("Oluwaseun Bakare", "Head of Credit & Risk", "ADMIN", "Former credit analyst at a consumer lender. Built Termly's affordability model and runs the weekly arrears review.", "Nigerian", "male"),
              person("Chiamaka Eze", "School Partnerships Lead", "MEMBER", "Ex-admissions officer at a Lekki private school. Signs and supports partner schools.", "Nigerian", "female"),
              person("Ibrahim Musa", "Lead Engineer", "MEMBER", "Full-stack engineer; built the parent app, mandate set-up and school payout flow.", "Nigerian", "male")],
        capital=cap,
        metrics=metrics([("partner_schools", "Partner schools", "count", None),
                         ("families_on_plans", "Families on active plans", "count", None),
                         ("default_rate_pct", "Default rate (60+ days past due, share of instalment volume)", "percent", None),
                         ("net_revenue", "Net revenue in month", "money", "NGN")],
                        {"partner_schools": [38, 52, 88, 104, 131, 140, 158, 212], "families_on_plans": fam,
                         "default_rate_pct": [2.4, 2.1, 1.9, 1.8, 1.7, 1.7, 1.6, 1.6], "net_revenue": rev},
                        "Families jump at term starts (January, April-May, September). Revenue assumes an average ₦210,000 term fee and a 4.5% combined take (1.5% school, 3% parent) recognised over four months."),
        deck=deck(
            problem=["For many Lagos families, September school fees are more than three months of salary, due on one day.",
                     "Parents borrow from friends and loan apps; schools spend weeks chasing late fees."],
            solution=["Schools sign up with Termly and offer it at enrolment.",
                      "Parents spread fees across the term by card or bank mandate.",
                      "The school is paid in full on day one."],
            value_proposition=["Parents: no scramble for loans, one predictable plan.",
                               "Schools: full fees on day one and no chasing.",
                               "Lending partner: low-default, purpose-specific credit."],
            market=["Lagos has an estimated 18,000+ private schools; Nigeria has many more.",
                    "TAM: private school fees in Nigeria, roughly ₦1.5 trillion a year (company estimate from enrolment and average fees).",
                    "SAM: Lagos and Abuja low- and mid-fee private schools. SOM: 1,000 schools by end of 2027."],
            go_to_market=["Direct school sign-ups through proprietor associations and school-owner WhatsApp groups.",
                          "Referral fee to schools that introduce other schools.",
                          "Parent onboarding happens through the school at enrolment, so parent acquisition cost is near zero."],
            business_model=["Schools pay a 1.5% platform fee on fees collected.",
                            "Parents pay a 3% instalment fee per term.",
                            "Funding comes from a ₦2.5bn credit line at a partner microfinance bank; Termly provides a 10% first-loss cover."],
            traction=["212 partner schools and about 9,400 families on plans.",
                      "1.6% default rate.",
                      "₦22.2m net revenue in September 2026."],
            competition=["Loan apps and family borrowing."],
            financials=["We expect to be profitable once we pass 1,000 schools."],
            the_ask=["Raising $600k pre-seed to reach 1,000 schools.",
                     "30% credit and collections, 30% school partnerships, 25% product, 15% first-loss reserve."],
            founders=["Adaeze Nwosu, Founder & CEO: five years in collections at a Lagos microfinance bank, ending as team lead.",
                      "Started Termly after watching her older sister borrow from three people every September."],
            team=["11 people: credit and risk, school partnerships, engineering and collections.",
                  "Next hires: Abuja partnerships lead and a second risk analyst."]),
        deckGaps=[{"section": "competition", "gap": "One line; no named competitors and no differentiation."},
                  {"section": "financials", "gap": "No projection, burn or runway; only a profitability claim."}],
        dataRoom=standard_room(
            "Termly Edupay Limited", "the Corporate Affairs Commission (CAC), Nigeria", "RC 7712048", "2024-08-05",
            [("Adaeze Nwosu", 78), ("Employee option pool", 10), ("Yaba Mothers Circle", 9), ("Individual angels", 3)],
            10, "Four-year vesting with a one-year cliff; 3 of 11 staff hold options so far.",
            ["Monthly P&L and balance sheet prepared in-house, reviewed quarterly by an external accountant.",
             "Net revenue rose from ₦2.7m in Oct 2025 to ₦22.2m in Sep 2026, with term-start peaks.",
             "First-loss reserve held in a separate account at the partner bank.",
             "Cash at 30 Sep 2026: about $95,000 equivalent."],
            "FIRS Tax Clearance Certificate (2026)",
            ["Tax Clearance Certificate covering the 2024 and 2025 years of assessment.",
             "Company qualifies as a small company for CIT; VAT charged on platform fees.",
             "PAYE remittances to Lagos State Internal Revenue Service attached."],
            ["Founder deed of assignment covering the app, risk model and brand.",
             "IP clauses in all employment and contractor agreements.",
             "Termly word mark not yet filed (planned for Q4 2026)."],
            ("Key contract summary: partner microfinance bank credit line",
             ["₦2.5bn revolving facility to fund parent instalments; 12-month term, renewable.",
              "Termly provides 10% first-loss cover and runs collections.",
              "Bank retains credit approval rights on schools above 400 enrolled families.",
              "Reporting: weekly arrears file and monthly portfolio review."]),
            ("Board minutes, July 2026",
             ["Two-person board (founder and angel representative).",
              "Approved pre-seed raise of $600k on a post-money SAFE.",
              "Reviewed default rate by school cohort; two schools paused for late transfers.",
              "Approved Abuja pilot with 10 schools."]),
            ("Founder and company KYC pack",
             ["CAC status report and particulars of directors.",
              "Founder BVN verification, NIN and passport.",
              "Beneficial ownership declaration and proof of address."]),
            [("School partner agreement (template)", "contracts", "ON_REQUEST",
              ["Standard agreement signed by all 212 partner schools.",
               "School receives full term fee on day one; Termly takes 1.5%.",
               "School must share enrolment confirmation and report withdrawals within 7 days."])]),
        qGuide=["Talk like me: direct, a bit funny, never stiff.",
                "Start with the parent's problem: one huge bill every September.",
                "Be clear that Termly is not a loan app. Credit comes from a licensed partner bank.",
                "Quote the default rate as 1.6% and explain how we measure it.",
                "Never name a family or share anything about a family's payments.",
                "Do not name partner schools without their consent.",
                "If asked about the bank partner terms, say they are available in the data room on request.",
                "Do not promise investors returns or timelines I have not committed to.",
                "If an investor is a fit, offer a call with me. If not, say so politely."],
        qPersonality="WITTY",
        gateqAnswers={"sector": "Fintech: education payments and consumer instalment credit", "stage": "pre_seed",
                      "geography": "Lagos, Nigeria; Abuja pilot next",
                      "chequeNeed": {"targetRaise": 600_000, "minimumCheque": 15_000, "currency": "USD"},
                      "traction": "212 partner schools; about 9,400 families on plans; 1.6% default rate",
                      "teamSize": 11})


# ---------------------------------------------------------------- 3 Clearwater Assurance
def c3():
    cap = capital(
        9_000_000, "GBP", "Priced equity (Series A preferred)", "preMoneyValuation", 32_000_000, "2027-02-26", 500_000,
        [("European expansion (Netherlands and Ireland first)", 35), ("Product: ML model testing and documentation checks", 30),
         ("UK sales and customer success", 20), ("Security, assurance certifications and G&A", 15)],
        rounds(("Pre-seed", "2021-09-30", 650_000, "GBP", "Advance subscription agreement", "Thameside Angels"),
               ("Seed", "2023-04-18", 3_000_000, "GBP", "Priced equity (seed preferred)", "Kittiwake Capital")),
        ["Kittiwake Capital", "Thameside Angels", "Northgate Fintech Partners"],
        1_900_000, 210_000, 420_000)
    return dict(
        legalName="Clearwater Assurance Ltd", websiteUrl="https://clearwater-assurance.example",
        foundedDate="2021-06-21", headquarters={"city": "London", "country": "GB"}, currentStageCode="series_a",
        headcount=38,
        shortDescription="Continuous, independent validation of UK banks' credit and AI models, with the evidence supervisors ask for.",
        primaryDescription=("Clearwater Assurance gives banks and building societies continuous, independent validation of their production models. "
                            "It tests each model against its own documentation, monitors drift, and produces evidence packs aligned to supervisory expectations for model risk management. "
                            "Seven UK banks and building societies use it on annual enterprise licences, giving £2.4m ARR and 132% net revenue retention. "
                            "The founding team combines bank model validation and supervisory review experience."),
        tags={"industry": ["enterprise_software", "fintech"], "business_model": ["b2b_saas", "licensing"],
              "customer_type": ["financial_institution", "enterprise"], "geography": ["united_kingdom", "europe"],
              "other": ["banking", "regulated_financial_services", "machine_learning"]},
        keywords=["model risk management", "model validation", "credit models", "AI governance", "bank regulation",
                  "drift monitoring", "supervisory evidence", "UK banks", "building societies", "regtech", "MRM", "machine learning risk"],
        brand={"primary": "#1E6E7A", "accent": "#CDE6E8", "ink": "#0B1620",
               "logoConcept": "A water droplet cut by one level horizontal line"},
        founderPerson=dict(
            name="Helena Marsh", role="Co-founder & CEO", appRole="OWNER", age=46, nationality="British", gender="female",
            city="London", education=["BSc Mathematics, University of Warwick (2001)", "MSc Statistics, London School of Economics (2003)"],
            previousRoles=[{"title": "Model Validation Analyst to Head of Credit Model Validation", "org": "FTSE 100 bank, London", "from": 2006, "to": 2018},
                           {"title": "Technical Specialist, Supervisory Model Reviews", "org": "UK prudential regulator", "from": 2018, "to": 2020},
                           {"title": "Independent model risk adviser", "org": "Self-employed", "from": 2020, "to": 2021}],
            headline="Co-founder & CEO, Clearwater Assurance | Model risk for the AI era | Former bank validator and supervisor",
            professionalSummary="Twelve years validating credit models inside a FTSE 100 bank, then two years reviewing banks' models for the regulator. Founded Clearwater to make validation continuous instead of annual.",
            backgroundSummary="Statistician by training. Saw from both sides of the table how manual validation lags the number of models banks now run.",
            languages=["English", "French (working)"]),
        team=[person("Rohan Mehta", "Co-founder & CTO", "ADMIN", "Formerly led ML platform engineering at a UK challenger bank. Architect of the continuous testing engine.", "British", "male"),
              person("Siobhan Gallagher", "Head of Validation Science", "MEMBER", "Ex-quant validator; PhD in statistics. Designs the test library and reviews every evidence pack template.", "Irish", "female"),
              person("Tom Ashworth", "CFO", "MEMBER", "Previously finance director at a B2B software scale-up. Runs finance, procurement and audit readiness.", "British", "male")],
        capital=cap,
        metrics=metrics([("arr", "Annual recurring revenue", "money", "GBP"),
                         ("customers", "Bank and building society customers", "count", None),
                         ("nrr_pct", "Net revenue retention, trailing 12 months", "percent", None),
                         ("models_monitored", "Models under continuous validation", "count", None)],
                        {"arr": [1_380_000, 1_520_000, 1_660_000, 1_830_000, 2_050_000, 2_160_000, 2_270_000, 2_400_000],
                         "customers": [5, 5, 6, 6, 6, 7, 7, 7],
                         "nrr_pct": [124, 126, 127, 129, 130, 131, 131, 132],
                         "models_monitored": geo(610, 1480)}),
        deck=deck(
            problem=["UK banks run hundreds of production models, a growing share of them machine learning.",
                     "Validation is still manual and periodic, built on spreadsheets and documents.",
                     "Supervisory expectations on model risk management make this a board-level issue."],
            solution=["Clearwater runs independent validation continuously, not once a year.",
                      "Each model is tested against its own documentation and monitored for drift.",
                      "Evidence packs are produced in the form supervisors ask for."],
            value_proposition=["Validation capacity scales with the model inventory without scaling headcount at the same rate.",
                               "Independence: the second line gets evidence the first line cannot shape.",
                               "Faster approval of new models, including ML models."],
            market=["Method: banks by size tier × typical annual model risk spend on tooling and external validation.",
                    "TAM: about 2,400 European banks and building societies, roughly £1.9bn a year.",
                    "SAM: UK, Ireland and Netherlands regulated lenders with 50+ models: about 160 institutions, £310m.",
                    "SOM: 40 institutions by 2029 at £350k average: £14m ARR."],
            go_to_market=["Direct enterprise sales to Chief Risk Officers and heads of model risk.",
                          "Land with one model family (usually retail credit), expand across the inventory.",
                          "Partnerships with two mid-tier audit firms for European introductions."],
            business_model=["Annual enterprise licence priced by number of models in scope.",
                            "Average contract value about £343k; three-year terms are standard.",
                            "Gross margin 84%."],
            traction=["£2.4m ARR from 7 UK banks and building societies.",
                      "132% net revenue retention; customers expand spend by about a third each year.",
                      "1,480 models under continuous validation."],
            competition=["SAS Model Manager: model lifecycle tooling, owned by the first line.",
                         "ValidMind and Yields: model documentation and validation tools.",
                         "Big Four validation teams: expert but manual and periodic.",
                         "Clearwater is independent, continuous and built around supervisory evidence."],
            financials=["ARR target: £5.1m end-2027, £9.8m end-2028, £16m end-2029.",
                        f"Net burn today about £{cap['monthlyNetBurn']['amount']:,} a month; about £{cap['plannedMonthlyNetBurnPostRaise']['amount']:,} after the raise.",
                        f"Runway after the raise about {cap['runwayMonthsPostRaise']:.0f} months; cash-flow positive in 2029."],
            the_ask=["Raising a £9m Series A (priced) to take the product into Europe.",
                     "35% European expansion, 30% product, 20% UK sales and success, 15% security, certifications and G&A."],
            founders=["Helena Marsh, CEO: 12 years in bank model validation, 2 years on supervisory model reviews.",
                      "Rohan Mehta, CTO: built ML platform infrastructure at a UK challenger bank."],
            team=["38 people in London: 17 engineering, 8 validation science, 7 commercial, 6 G&A.",
                  "ISO 27001 certified; SOC 2 Type II audit in progress."]),
        deckGaps=[],
        dataRoom=standard_room(
            "Clearwater Assurance Ltd", "Companies House (England and Wales)", "Company number 13492067", "2021-06-21",
            [("Helena Marsh", 31), ("Rohan Mehta", 24), ("Kittiwake Capital", 19.5), ("Employee option pool (EMI)", 12),
             ("Thameside Angels", 8), ("Northgate Fintech Partners", 5.5)],
            12, "EMI options, four-year vesting with a one-year cliff; 29 of 38 staff hold options.",
            ["Monthly management accounts in sterling, with ARR bridge and deferred revenue schedule.",
             "ARR grew from £1.38m in Oct 2025 to £2.40m in Sep 2026.",
             "Gross margin 84%; headcount cost 71% of operating expenses.",
             "Cash at 30 Sep 2026: £1.9m; monthly net burn about £210k."],
            "HMRC tax position: CT600 filings and account statement",
            ["Corporation tax returns (CT600) for the years to June 2023, 2024 and 2025.",
             "R&D tax relief claims and HMRC acceptance letters.",
             "VAT and PAYE account statements showing no arrears.",
             "HMRC does not issue tax clearance certificates; this pack is the equivalent evidence."],
            ["Founder IP assignment deeds dated June 2021.",
             "IP and confidentiality clauses in all employment contracts.",
             "UK trade mark 'CLEARWATER ASSURANCE' registered in classes 9 and 42."],
            ("Key customer contract summary: UK building society (name withheld)",
             ["Three-year enterprise licence from January 2025; £410k a year.",
              "Scope: 210 retail credit and pricing models, expanded in 2026 to IRB models.",
              "Audit rights for the customer and its regulator; data stays in the customer's UK tenancy.",
              "Termination for convenience after year two with six months' notice."]),
            ("Board minutes, Q3 2026",
             ["Approved Series A process and appointment of a placement adviser.",
              "Reviewed European regulatory mapping for the Netherlands and Ireland.",
              "Approved SOC 2 Type II audit budget.",
              "Noted one customer renewal moved from Q4 to Q1 due to procurement."]),
            ("Company KYB pack",
             ["Companies House confirmation statement and register of PSCs.",
              "Directors' passports and proof of address.",
              "Bank reference letter and sanctions screening results."]),
            [("ISO 27001 certificate and statement of applicability", "legal_ip", "ON_REQUEST",
              ["ISO/IEC 27001:2022 certificate issued March 2026.",
               "Scope covers product, hosting and validation operations.",
               "Statement of applicability with excluded controls justified."]),
             ("Customer reference list (consented)", "contracts", "SHARED_ONLY",
              ["Four of seven customers have agreed to take reference calls after a term sheet.",
               "Contact roles: Chief Risk Officer, two heads of model risk, one CFO.",
               "Calls are arranged by Clearwater; no direct contact without notice."])]),
        qGuide=["Be precise. Use exact figures: £2.4m ARR, seven customers, 132% net revenue retention.",
                "Never name a customer. Say 'a UK building society' or 'a mid-sized UK bank'.",
                "Do not say we are approved or endorsed by any regulator. We help banks meet supervisory expectations.",
                "Describe my regulator background accurately: two years on supervisory model reviews.",
                "Avoid the words 'disrupt' and 'revolution'. Model risk is a discipline, not a slogan.",
                "Contract terms and pipeline stay in the data room. Share only with approved investors.",
                "If asked about Europe, be honest that we have no European customers yet.",
                "Tone: composed, formal, quietly confident.",
                "When unsure, say what we know, what we do not, and offer a follow-up."],
        qPersonality="FORMAL",
        gateqAnswers={"sector": "Enterprise software / RegTech: model risk management for banks", "stage": "series_a",
                      "geography": "London, United Kingdom; expanding to Europe",
                      "chequeNeed": {"targetRaise": 9_000_000, "minimumCheque": 500_000, "currency": "GBP"},
                      "traction": "£2.4m ARR; 7 UK banks and building societies; 132% net revenue retention",
                      "teamSize": 38})


# ---------------------------------------------------------------- 4 Tensorgate
def c4():
    req = [3.1, 5.0, 7.9, 12.0, 17.6, 21.2, 25.8, 31.0]
    cap = capital(
        4_000_000, "USD", "SAFE (post-money)", "valuationCap", 30_000_000, "2027-01-29", 100_000,
        [("Engineering: GPU enclave support and SDKs", 45), ("Security certifications (SOC 2, HITRUST)", 15),
         ("Go-to-market: two enterprise AEs and a solutions engineer", 30), ("G&A and legal", 10)],
        rounds(("Pre-seed", "2024-05-08", 1_200_000, "USD", "SAFE (post-money)", "Bastion Hill Ventures")),
        ["Bastion Hill Ventures", "Lone Oak Angels", "Two security founders as angels"],
        1_100_000, 135_000, 220_000)
    return dict(
        legalName="Tensorgate, Inc.", websiteUrl="https://tensorgate.example",
        foundedDate="2024-02-05", headquarters={"city": "Austin", "country": "US"}, currentStageCode="seed",
        headcount=14,
        shortDescription="A gateway that runs LLM inference inside hardware enclaves and attests every request, so regulated firms can use AI on sensitive data.",
        primaryDescription=("Tensorgate is a confidential-computing gateway for large language models. Prompts are decrypted only inside a hardware enclave, the model runs there, and every request gets a cryptographic attestation of the code that touched the data. "
                            "Batched attestation and pinned memory keep enclave overhead to about 40 milliseconds per request. "
                            "Four design partners in banking and healthcare use it, two on paid $180k annual contracts, and it has served 31 million requests. "
                            "Pricing is usage-based with an enterprise floor."),
        tags={"industry": ["cybersecurity", "enterprise_software"], "business_model": ["usage_based", "b2b_saas"],
              "customer_type": ["enterprise", "financial_institution"], "geography": ["united_states", "north_america"],
              "other": ["artificial_intelligence", "cloud_infrastructure", "data_protection_sensitive"]},
        keywords=["confidential computing", "secure enclave", "LLM gateway", "attestation", "AI security",
                  "regulated AI", "data privacy", "healthcare AI", "banking AI", "inference security", "TEE", "zero trust"],
        brand={"primary": "#263238", "accent": "#39D98A", "ink": "#0A0C10",
               "logoConcept": "A square gate with a keyhole notch cut into its top edge"},
        founderPerson=dict(
            name="Daniel Park", role="Co-founder & CTO", appRole="OWNER", age=31, nationality="American", gender="male",
            city="Austin", education=["BS Computer Science, University of Texas at Austin (2016)", "MS Computer Science (Security), Carnegie Mellon University (2017)"],
            previousRoles=[{"title": "Security Researcher", "org": "University systems security lab", "from": 2017, "to": 2019},
                           {"title": "Senior Software Engineer, Confidential Computing", "org": "Hyperscale cloud provider", "from": 2019, "to": 2023},
                           {"title": "Staff Engineer, Secure Enclaves", "org": "Hyperscale cloud provider", "from": 2023, "to": 2024}],
            headline="Co-founder & CTO, Tensorgate | Enclaves, attestation, side channels | Making 'prove where the data went' a default",
            professionalSummary="Built secure-enclave infrastructure at a hyperscaler and published research on side-channel attacks. Leads Tensorgate's enclave runtime and attestation pipeline.",
            backgroundSummary="Grew up in Houston. Got into security by breaking things in grad school and decided he preferred building the locks.",
            languages=["English", "Korean (conversational)"]),
        team=[person("Laura Bennett", "Co-founder & CEO", "ADMIN", "Previously VP of sales at a data-security company selling to US banks and health systems. Runs fundraising and enterprise sales.", "American", "female"),
              person("Marcus Delgado", "Head of Applied Cryptography", "MEMBER", "Former cryptography engineer at a payments network. Owns the attestation format and key management.", "American", "male"),
              person("Jordan Whitfield", "Founding Solutions Engineer", "MEMBER", "Deploys Tensorgate into design partners' cloud accounts and writes the integration guides.", "American", "male")],
        capital=cap,
        metrics=metrics([("requests_served_m", "Requests served, cumulative (millions)", "count_millions", None),
                         ("design_partners", "Design partners", "count", None),
                         ("paid_contracts", "Paid contracts", "count", None),
                         ("contracted_arr", "Contracted ARR", "money", "USD"),
                         ("median_overhead_ms", "Median enclave overhead per request", "milliseconds", None)],
                        {"requests_served_m": req, "design_partners": [2, 3, 3, 4, 4, 4, 4, 4],
                         "paid_contracts": [0, 0, 0, 1, 1, 1, 2, 2],
                         "contracted_arr": [0, 0, 0, 180_000, 180_000, 180_000, 360_000, 360_000],
                         "median_overhead_ms": [210, 160, 118, 85, 58, 49, 43, 40]},
                        "Each paid contract is a $180k annual enterprise floor; usage above the floor is billed monthly."),
        deck=deck(
            problem=["Banks and health systems want LLMs on customer data, but data leaving their environment fails compliance review.",
                     "Existing controls show where data is stored, not what code processed it."],
            solution=["A gateway that runs inside a hardware enclave: prompts decrypted only inside, model runs inside.",
                      "A cryptographic attestation for every single request, proving exactly what code touched the data.",
                      "Enclave overhead cut from seconds to about 40 ms with batched attestation and pinned memory."],
            value_proposition=["Security teams get per-request proof, not a policy document.",
                               "Data science teams use LLMs on regulated data without a separate approval each time.",
                               "Works with open-weight models in the customer's own cloud account."],
            market=["Method: regulated enterprises × expected annual AI-security platform spend.",
                    "TAM: about 9,000 US and European banks, insurers and health systems at $250k average = $2.25bn.",
                    "SAM: 1,100 US banks and health systems over $5bn in assets or revenue running LLM pilots = $275m.",
                    "SOM: 60 enterprise customers by 2029 = $15m ARR."],
            go_to_market=["Design-partner programme with security and data leaders at regulated enterprises.",
                          "Land through a single high-risk use case (claims notes, KYC review), expand by request volume.",
                          "Marketplace listing on the major cloud providers for procurement."],
            business_model=["Usage-based pricing per million requests above an enterprise floor.",
                            "Current paid contracts: $180k annual floor each.",
                            "Target gross margin 70% at scale; GPU enclave capacity is the main cost."],
            traction=["4 design partners in banking and healthcare; 2 converted to paid contracts.",
                      "$360k contracted ARR.",
                      "31 million requests served; median overhead about 40 ms."],
            competition=["Fortanix and Anjuna: general confidential-computing platforms, not LLM-specific.",
                         "Opaque Systems: confidential analytics and AI.",
                         "Hyperscaler confidential VMs: infrastructure, but no per-request attestation trail.",
                         "Tensorgate is LLM-first, with per-request attestation and low latency."],
            financials=["Revenue plan: $1.4m in 2027, $4.8m in 2028, $11m in 2029.",
                        f"Net burn today about ${cap['monthlyNetBurn']['amount']:,} a month, rising to about ${cap['plannedMonthlyNetBurnPostRaise']['amount']:,}.",
                        f"Runway after the raise about {cap['runwayMonthsPostRaise']:.0f} months."],
            the_ask=["Raising a $4m seed on a post-money SAFE.",
                     "45% engineering, 30% go-to-market, 15% certifications, 10% G&A."],
            founders=["Daniel Park, CTO: secure-enclave infrastructure at a hyperscaler; published side-channel research.",
                      "Laura Bennett, CEO: data-security enterprise sales to US banks and health systems."],
            team=["14 people: 10 engineering (4 with enclave or cryptography backgrounds), 2 go-to-market, 2 operations.",
                  "Remote-first, with a small office in Austin."]),
        deckGaps=[],
        dataRoom=standard_room(
            "Tensorgate, Inc.", "the Delaware Division of Corporations", "File number 7914652", "2024-02-05",
            [("Daniel Park", 36), ("Laura Bennett", 36), ("Employee option pool", 12), ("Bastion Hill Ventures", 11), ("Angels", 5)],
            12, "Four-year vesting, one-year cliff; early-exercise permitted with 83(b) elections.",
            ["Monthly P&L and balance sheet (accrual), prepared by an outsourced accounting firm.",
             "Revenue began in April 2026 with the first paid contract.",
             "Cloud and GPU costs were $41k in September 2026.",
             "Cash at 30 Sep 2026: $1.1m; monthly net burn about $135k."],
            "Tax filings and Delaware good standing",
            ["Federal Form 1120 for 2024 and 2025.",
             "Delaware franchise tax paid; certificate of good standing dated August 2026.",
             "Texas franchise tax no-tax-due report for 2025."],
            ["Confidential information and invention assignment agreements (CIIAA) for both founders and all staff.",
             "Daniel Park's prior-inventions schedule lists two published papers; no prior employer claim.",
             "Two US provisional patent applications on batched attestation."],
            ("Key customer contract summary: regional US bank (name withheld)",
             ["Enterprise agreement with $180k annual floor plus usage above 40m requests a year.",
              "Deployed in the bank's own cloud account; Tensorgate has no access to plaintext.",
              "Security addendum with right to audit and 72-hour incident notice.",
              "Initial term 12 months, auto-renewing."]),
            ("Board minutes, August 2026",
             ["Three-person board: both founders and Bastion Hill Ventures.",
              "Approved seed raise on a post-money SAFE with a $30m cap.",
              "Approved SOC 2 Type I audit start.",
              "Discussed converting the remaining two design partners before year end."]),
            ("Company KYB pack",
             ["Certificate of incorporation, bylaws and EIN letter.",
              "Beneficial ownership information report filing receipt.",
              "Founders' government IDs."]),
            [("Penetration test report (third party)", "legal_ip", "SHARED_ONLY",
              ["Independent test of the gateway and attestation service, June 2026.",
               "No critical findings; two medium findings fixed within 14 days.",
               "Retest letter attached."]),
             ("Latency benchmark methodology", "legal_ip", "ON_REQUEST",
              ["How the 40 ms median overhead is measured: same model and hardware, enclave on versus off.",
               "Percentiles reported at p50, p95 and p99 across request sizes.",
               "Scripts to reproduce the benchmark."])]),
        qGuide=["Be technically precise. If you simplify, say you are simplifying.",
                "The 40 ms figure is median overhead per request versus the same model outside the enclave. Do not round it down.",
                "Two paid contracts at $180k a year each. Four design partners total. Do not inflate either.",
                "Never name design partners or customers.",
                "We do not claim to be unbreakable. Enclaves have had side-channel issues, and I published on some of them.",
                "Do not describe us as an LLM provider. We secure inference; customers choose the model.",
                "A bit of dry humour is fine. Hype is not.",
                "Laura handles commercial terms; route term questions to her or to me.",
                "If a question needs the security whitepaper, offer it on request."],
        qPersonality="DIRECT",
        gateqAnswers={"sector": "AI infrastructure / Cybersecurity: confidential computing for LLM inference", "stage": "seed",
                      "geography": "Austin, Texas, United States",
                      "chequeNeed": {"targetRaise": 4_000_000, "minimumCheque": 100_000, "currency": "USD"},
                      "traction": "4 design partners in banking and healthcare; 2 paid contracts at $180k a year each; 31m requests served",
                      "teamSize": 14})


# ---------------------------------------------------------------- 5 Drishti Health
def c5():
    monthly, cum = cum_from_monthly(8_900, 22_000, 210_000)
    refs = [round(c * 6900 / 210000) for c in cum]
    pharm = geo(140, 380)
    rev = [m * 140 for m in monthly]
    cap = capital(
        3_000_000, "USD", "Priced equity (CCPS)", "preMoneyValuation", 15_000_000, "2027-01-15", 75_000,
        [("Pharmacy roll-out: cameras and field team (Maharashtra, Karnataka)", 40), ("Clinical validation and CDSCO regulatory work", 20),
         ("Referral network with eye hospitals", 15), ("Engineering and data", 25)],
        rounds(("Angel", "2022-12-20", 40_000_000, "INR", "Compulsorily convertible debentures", "Deccan Doctors Angel Network"),
               ("Pre-seed", "2023-10-05", 650_000, "USD", "Priced equity (CCPS)", "Sahyadri Health Ventures")),
        ["Sahyadri Health Ventures", "Deccan Doctors Angel Network", "A grant from a state innovation society (non-dilutive)"],
        520_000, 55_000, 125_000)
    return dict(
        legalName="Drishti Health Technologies Private Limited", websiteUrl="https://drishtihealth.example",
        foundedDate="2022-11-08", headquarters={"city": "Pune", "country": "IN"}, currentStageCode="seed",
        headcount=34,
        shortDescription="Retinal cameras in neighbourhood pharmacies; AI reads the image in under a minute and refers at-risk diabetics the same day.",
        primaryDescription=("Drishti Health screens people with diabetes for diabetic retinopathy where they already go every month: the neighbourhood pharmacy. "
                            "A pharmacist takes a photo with a low-cost retinal camera, Drishti's AI grades it in under a minute, and anyone at risk is referred to an eye specialist the same day. "
                            "The service runs in 380 pharmacies, has completed over 210,000 screenings, and has referred about 6,900 people early. "
                            "Pharmacy chains and insurers' wellness programmes pay a per-screen fee."),
        tags={"industry": ["healthcare"], "business_model": ["transaction_fee"],
              "customer_type": ["business_customer", "insurance_company"], "geography": ["india", "asia"],
              "other": ["digital_health", "computer_vision", "health_access", "regulated_healthcare"]},
        keywords=["diabetic retinopathy", "eye screening", "retinal camera", "pharmacy health", "AI diagnostics",
                  "India diabetes", "early referral", "ophthalmology", "Pune", "preventive care", "fundus imaging", "insurer wellness"],
        brand={"primary": "#E89B1C", "accent": "#0F5E6B", "ink": "#2A1D0E",
               "logoConcept": "Two concentric iris rings opening like a lens aperture"},
        founderPerson=dict(
            name="Priya Raman", role="Founder & CEO", appRole="OWNER", age=38, nationality="Indian", gender="female",
            city="Pune", education=["MBBS, Madras Medical College (2011)", "MS Ophthalmology (2014)"],
            previousRoles=[{"title": "Resident, Ophthalmology", "org": "Government medical college hospital, Chennai", "from": 2011, "to": 2014},
                           {"title": "Ophthalmologist and camp lead, rural eye camps", "org": "Charitable eye hospital network, Maharashtra", "from": 2012, "to": 2022},
                           {"title": "Clinical adviser, diabetic eye screening pilot", "org": "District health programme", "from": 2020, "to": 2022}],
            headline="Founder & CEO, Drishti Health | Ophthalmologist | Diabetic eye screening where people already go",
            professionalSummary="Ophthalmologist who ran rural eye camps for a decade, seeing late-stage diabetic retinopathy that a simple photo would have caught years earlier. Founded Drishti to move screening into pharmacies.",
            backgroundSummary="Trained in Chennai, practised mostly in rural Maharashtra. Started Drishti in Pune in 2022 with a borrowed camera and three pharmacies.",
            languages=["Tamil", "English", "Marathi", "Hindi"]),
        team=[person("Aditya Kulkarni", "CTO", "ADMIN", "Computer vision engineer; previously built medical imaging pipelines at a Pune health-tech company. Owns the grading model and device integration.", "Indian", "male"),
              person("Sneha Deshpande", "Head of Pharmacy Network", "MEMBER", "Ex-regional manager at a pharmacy chain. Recruits and trains pharmacies, runs camera logistics.", "Indian", "female"),
              person("Dr Farhan Qureshi", "Clinical Lead", "MEMBER", "Retina specialist; reviews flagged images and manages the referral hospital network.", "Indian", "male")],
        capital=cap,
        metrics=metrics([("pharmacies", "Pharmacies live", "count", None),
                         ("screenings_month", "Screenings in month", "count", None),
                         ("screenings_cumulative", "Screenings, cumulative", "count", None),
                         ("referred_early_cumulative", "People referred early, cumulative", "count", None),
                         ("revenue_month", "Revenue in month", "money", "INR")],
                        {"pharmacies": pharm, "screenings_month": monthly, "screenings_cumulative": cum,
                         "referred_early_cumulative": refs, "revenue_month": rev},
                        "Average realised fee ₹140 per screen (₹120 pharmacy chains, ₹180 insurer programmes). About 3.3% of screens are referred."),
        deck=deck(
            problem=["India has more than 100 million people with diabetes; most will never see an eye specialist.",
                     "Diabetic retinopathy is preventable if caught early, but it is usually found when sight is already going."],
            solution=["A small retinal camera in neighbourhood pharmacies, which most diabetics visit every month.",
                      "AI reads the image in under a minute.",
                      "Anyone at risk is referred to a partner eye hospital the same day."],
            value_proposition=["Patients: a two-minute check where they already buy medicine.",
                               "Pharmacies: a paid service that brings customers back.",
                               "Insurers: early detection at a fraction of late-stage treatment cost."],
            market=["Method: diabetics in reach of organised pharmacies × one screen a year × average fee.",
                    "TAM: about 100 million diabetics × ₹140 = ₹1,400 crore (about $160m) a year.",
                    "SAM: urban and semi-urban Maharashtra, Karnataka and Gujarat, about 18 million diabetics = ₹252 crore.",
                    "SOM: 2.4 million screens a year by 2029 = ₹34 crore."],
            go_to_market=["Pharmacy chains first (one contract, many stores), then independent pharmacies via distributors.",
                          "Insurer wellness programmes pay for screens for their members.",
                          "Referral partnerships with eye hospitals that also co-market."],
            business_model=["Per-screen fee: ₹120 from pharmacy chains, ₹180 from insurer programmes.",
                            "Camera placed free; minimum 40 screens a month per pharmacy.",
                            "Gross margin 61% after camera depreciation and grader review."],
            traction=["380 pharmacies live.",
                      "Over 210,000 screenings; about 22,000 in September 2026.",
                      "About 6,900 people referred early."],
            competition=["Remidio: portable fundus cameras with offline AI, sold mainly to clinics.",
                         "Eyenuk: AI grading software, strong in the US and Europe.",
                         "Artelus: AI screening in Indian hospitals and camps.",
                         "Drishti owns the pharmacy channel and the referral loop, not just the device or the model."],
            financials=["Revenue: ₹6.2 crore in FY2027-28, ₹14 crore in FY2028-29, ₹27 crore in FY2029-30.",
                        f"Net burn today about ${cap['monthlyNetBurn']['amount']:,} a month; about ${cap['plannedMonthlyNetBurnPostRaise']['amount']:,} after the raise.",
                        f"Runway after the raise about {cap['runwayMonthsPostRaise']:.0f} months."],
            the_ask=["Raising a $3m seed (priced, CCPS).",
                     "40% pharmacy roll-out, 25% engineering, 20% clinical validation and regulatory, 15% referral network."],
            founders=["Dr Priya Raman, Founder & CEO: ophthalmologist, a decade running rural eye camps in Maharashtra.",
                      "Supported by CTO Aditya Kulkarni (medical imaging pipelines) and Clinical Lead Dr Farhan Qureshi (retina specialist)."],
            team=["34 people: 9 engineering and data, 16 field and pharmacy operations, 4 clinical, 5 G&A.",
                  "Clinical advisory board of three retina specialists."]),
        deckGaps=[],
        dataRoom=standard_room(
            "Drishti Health Technologies Private Limited", "the Registrar of Companies, Pune (Ministry of Corporate Affairs)",
            "CIN U86900MH2022PTC394218", "2022-11-08",
            [("Priya Raman", 58), ("Sahyadri Health Ventures", 14), ("Employee stock option pool", 11),
             ("Aditya Kulkarni", 9), ("Deccan Doctors Angel Network (as converted)", 8)],
            11, "Four-year vesting, one-year cliff; exercise within five years of vesting.",
            ["Monthly management accounts in rupees under Ind AS formats.",
             "Revenue rose from ₹12.5 lakh in Oct 2025 to ₹30.8 lakh in Sep 2026.",
             "Camera fleet capitalised and depreciated over three years.",
             "Cash at 30 Sep 2026: about $520,000 equivalent."],
            "GST registration and income tax returns",
            ["GST registration certificate (Maharashtra) and GSTR-3B filings for FY2025-26.",
             "Income tax returns for FY2023-24 and FY2024-25 with acknowledgements.",
             "DPIIT startup recognition certificate."],
            ["Founder and CTO IP assignment deeds covering the grading model and training pipeline.",
             "Data-use agreements for training images with consent records.",
             "Indian trade mark application for 'DRISHTI HEALTH' (class 44)."],
            ("Key customer contract summary: western India pharmacy chain (name withheld)",
             ["Covers 148 stores; ₹120 per screen with a 40-screen monthly minimum per store.",
              "Drishti supplies and maintains cameras; chain supplies trained staff.",
              "Patient consent and data handled under the Digital Personal Data Protection Act.",
              "Two-year term from April 2025."]),
            ("Board minutes, Q2 2026",
             ["Approved seed round on CCPS with a $15m pre-money valuation.",
              "Reviewed false-negative audit: two missed referrals in 10,000 reviewed images.",
              "Approved expansion into Karnataka with 60 pharmacies.",
              "Noted CDSCO medical device classification work."]),
            ("Company KYC pack",
             ["Certificate of incorporation, PAN and TAN.",
              "Directors' DIN, Aadhaar-masked ID and PAN.",
              "Registered office proof and bank KYC letter."]),
            [("Clinical validation study summary", "legal_ip", "ON_REQUEST",
              ["Prospective study of 4,820 patients across 22 pharmacies, 2025.",
               "Grading model compared with two retina specialists.",
               "Reports sensitivity and specificity for referable retinopathy with confidence intervals.",
               "Ethics committee approval letter attached."]),
             ("Medical device regulatory status note", "legal_ip", "ON_REQUEST",
              ["Classification of the grading software under the Medical Devices Rules.",
               "Status of CDSCO application and timeline.",
               "Camera supplier's import licence and certifications."])]),
        qGuide=["Speak like a doctor, not a salesperson. Calm and unhurried.",
                "Say 'referred early', not 'diagnosed'. The AI flags risk; specialists diagnose.",
                "Never share any patient's image, name or story beyond what I have told publicly.",
                "Use our real numbers: 380 pharmacies, over 210,000 screenings, about 6,900 referred early.",
                "Do not claim regulatory approval we do not have. Point to the regulatory status note.",
                "If asked about accuracy, quote the validation study with its confidence intervals, not a headline number.",
                "Do not name the pharmacy chain or insurers without their consent.",
                "If someone asks about expansion outside India, say it is not in this round's plan.",
                "Warmth is good. Exaggeration is not."],
        qPersonality="WARM",
        gateqAnswers={"sector": "Health: AI diagnostics for diabetic eye screening", "stage": "seed",
                      "geography": "Pune, India; pharmacies in Maharashtra, expanding to Karnataka",
                      "chequeNeed": {"targetRaise": 3_000_000, "minimumCheque": 75_000, "currency": "USD"},
                      "traction": "380 pharmacies; 210,000 screenings; about 6,900 referred early",
                      "teamSize": 34})


COMPANIES = [c1, c2, c3, c4, c5]
