from common import *
from c01_05 import deck


# ---------------------------------------------------------------- 6 Silo Credit
def c6():
    tonnes = [1500, 2350, 1900, 950, 660, 550, 700, 1600]
    book = [410_000_000, 640_000_000, 520_000_000, 260_000_000, 180_000_000, 150_000_000, 190_000_000, 430_000_000]
    financed = [920_000_000, 1_310_000_000, 1_520_000_000, 1_610_000_000, 1_700_000_000, 1_760_000_000, 1_850_000_000, 2_100_000_000]
    new_fin = [None] + [financed[i] - financed[i - 1] for i in range(1, 8)]
    new_fin[0] = 180_000_000
    rev = [round(b * 0.007 + t * 1500 + nf * 0.01 / (2 if j in (1, 2, 3) else 1)) for j, (b, t, nf) in enumerate(zip(book, tonnes, new_fin))]
    cap = capital(
        2_500_000, "USD", "Priced equity", "preMoneyValuation", 12_000_000, "2027-02-12", 100_000,
        [("Warehouse network: certify 26 more sites in Kano, Kaduna, Katsina and Jigawa", 35),
         ("Technology: receipt registry, grading data and automatic repayment", 25),
         ("First-loss capital supporting the debt facility", 20), ("Risk, grading and insurance operations", 20)],
        rounds(("Angel", "2022-06-01", 150_000, "USD", "SAFE (post-money)", "Kano and Abuja business angels"),
               ("Pre-seed", "2024-03-20", 700_000, "USD", "Priced equity", "Dala Hill Capital")),
        ["Dala Hill Capital", "Sahelian Growth Partners", "Kano and Abuja business angels"],
        640_000, 48_000, 105_000,
        extra={"debtFacility": {"status": "in negotiation alongside this round", "targetAmount": 7_500_000_000, "currency": "NGN",
                                "existingFacility": {"amount": 1_000_000_000, "currency": "NGN", "lender": "Nigerian commercial bank (name withheld)"},
                                "note": "Debt funds the loan book; equity funds operations and first-loss cover."}})
    return dict(
        legalName="Silo Credit Nigeria Limited", websiteUrl="https://silocredit.example",
        foundedDate="2022-02-09", headquarters={"city": "Kano", "country": "NG"}, currentStageCode="seed",
        headcount=31,
        shortDescription="Silo Credit certifies warehouses and issues digital receipts that let Kano grain traders borrow against stored grain and sell later.",
        primaryDescription=("Silo Credit runs warehouse-receipt finance for grain traders and farmers in Northern Nigeria. It certifies warehouses, grades and insures grain on arrival, and issues a digital receipt the trader can borrow against immediately; when the grain is sold, the loan is repaid automatically. "
                            "That lets sellers wait out the harvest price low instead of selling at the bottom. "
                            "Silo works with 14 certified warehouses, has financed about ₦2.1bn, and has a loss rate under 0.5%. "
                            "It earns a lending spread plus warehouse management fees."),
        tags={"industry": ["fintech", "agriculture"], "business_model": ["transaction_fee", "services"],
              "customer_type": ["small_business", "consumer"], "geography": ["nigeria", "west_africa", "africa"],
              "other": ["digital_lending", "agritech", "financial_inclusion", "supply_chain"]},
        keywords=["warehouse receipts", "commodity finance", "grain storage", "Kano", "Dawanau", "maize",
                  "agricultural lending", "collateralised lending", "smallholder finance", "Northern Nigeria", "post-harvest", "inventory finance"],
        brand={"primary": "#9C6B2F", "accent": "#2E5E3A", "ink": "#241A10",
               "logoConcept": "Three grain sacks stacked as rising bars"},
        founderPerson=dict(
            name="Halima Bello", role="Co-founder & CEO", appRole="OWNER", age=41, nationality="Nigerian", gender="female",
            city="Kano", education=["BSc Agricultural Economics, Bayero University Kano (2007)", "MSc Development Finance, Ahmadu Bello University (2010)"],
            previousRoles=[{"title": "Buyer and stock manager", "org": "Family grain trading business, Dawanau market", "from": 2003, "to": 2008},
                           {"title": "Agricultural Lending Officer to Senior Credit Officer", "org": "Development bank, Northern Nigeria", "from": 2010, "to": 2021},
                           {"title": "Consultant to warehouse operators", "org": "Self-employed", "from": 2021, "to": 2022}],
            headline="Co-founder & CEO, Silo Credit | Grain is the collateral | Former agricultural lending officer",
            professionalSummary="Eleven years lending to farmers and agro-dealers at a development bank, after growing up in her family's grain business in Dawanau market. Designed Silo's grading and loan-to-value rules.",
            backgroundSummary="Grew up between the family stall in Dawanau and school in Kano. Watched sellers take harvest-time prices every year because they could not wait.",
            languages=["Hausa", "English", "Arabic (reading)"]),
        team=[person("Abdullahi Sani", "Co-founder & COO", "ADMIN", "Ran logistics for a regional agro-processor for nine years. Manages warehouse certification and grading crews.", "Nigerian", "male"),
              person("Aisha Yusuf", "Head of Risk", "MEMBER", "Former commodity analyst at a commercial bank. Sets loan-to-value by crop and tracks price risk weekly.", "Nigerian", "female"),
              person("Chinedu Obi", "Head of Engineering", "MEMBER", "Built the receipt registry and USSD flows. Previously at a Lagos payments company.", "Nigerian", "male")],
        capital=cap,
        metrics=metrics([("certified_warehouses", "Certified warehouses", "count", None),
                         ("financed_cumulative", "Financed, cumulative", "money", "NGN"),
                         ("loan_book", "Outstanding loan book", "money", "NGN"),
                         ("tonnes_under_receipt", "Grain under financed receipts", "tonnes", None),
                         ("loss_rate_pct", "Cumulative loss rate", "percent", None),
                         ("net_revenue", "Net revenue in month (spread + fees)", "money", "NGN")],
                        {"certified_warehouses": [9, 9, 10, 11, 12, 13, 14, 14], "financed_cumulative": financed,
                         "loan_book": book, "tonnes_under_receipt": tonnes,
                         "loss_rate_pct": [0.3, 0.3, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4], "net_revenue": rev},
                        "Seasonal: lending peaks after harvest (Oct-Jan) and the book runs down as grain is sold. Loan-to-value about 55% of graded value; about ₦270,000 lent per tonne."),
        deck=deck(
            problem=["At harvest, grain prices are at their lowest, and that is when farmers and small traders must sell for cash.",
                     "Three months later the same maize can be worth almost double; the gain goes to whoever can afford to wait.",
                     "Banks will not lend to small traders without collateral they can value and control."],
            solution=["Silo certifies warehouses, then grades and insures grain on arrival.",
                      "It issues a digital receipt the trader can borrow against immediately.",
                      "When the grain is sold, the loan is repaid automatically from the proceeds."],
            value_proposition=["Traders and farmers keep the seasonal price gain instead of giving it away.",
                               "Lenders get graded, insured, controlled collateral.",
                               "Warehouse owners get steady, fee-paying occupancy."],
            market=["Method: marketed grain volume in Northern Nigeria × share suitable for storage × average loan size.",
                    "TAM: about 9 million tonnes of marketed maize, sorghum, millet and soybean a year; financing need about ₦2.4 trillion at 55% loan-to-value.",
                    "SAM: Kano, Kaduna, Katsina and Jigawa trading hubs, about 1.6 million tonnes = ₦430bn.",
                    "SOM: 60,000 tonnes a year by 2029 = ₦16bn financed."],
            go_to_market=["Partner with existing warehouse owners in and around Dawanau rather than building warehouses.",
                          "Trader associations and market leaders introduce members.",
                          "Repeat seasonal borrowers: 71% of 2024-25 borrowers returned in 2025-26."],
            business_model=["Loans priced at 2.6% a month; cost of funds about 1.9% a month, a 0.7% monthly spread.",
                            "Warehouse management fee of ₦1,500 per tonne per month.",
                            "1% grading and receipt fee on each financing."],
            traction=["14 certified warehouses.",
                      "About ₦2.1bn financed since launch.",
                      "Cumulative loss rate 0.4%.",
                      "1,600 tonnes under financed receipt at the start of the 2026 harvest."],
            competition=["AFEX: commodity exchange and warehouse network at large scale, focused on aggregation and trading.",
                         "Informal lenders and off-takers: fast cash, but at harvest-low prices or very high cost.",
                         "Bank agricultural loans: scarce for small traders without land collateral.",
                         "Silo is lender-first, with small tickets and repayment tied to sale."],
            financials=["Financing volume: ₦4.6bn in 2027, ₦9.8bn in 2028, ₦16bn in 2029.",
                        "Net revenue: ₦190m in 2027, ₦420m in 2028, ₦780m in 2029; operating break-even in 2029.",
                        f"Opex net burn today about ${cap['monthlyNetBurn']['amount']:,} a month; about ${cap['plannedMonthlyNetBurnPostRaise']['amount']:,} after the raise.",
                        f"Equity runway after the raise about {cap['runwayMonthsPostRaise']:.0f} months; the loan book is funded by debt."],
            the_ask=["Raising $2.5m of equity, priced, alongside a ₦7.5bn debt facility.",
                     "35% warehouse network, 25% technology, 20% first-loss capital, 20% risk and grading."],
            founders=["Halima Bello, CEO: grew up in the Dawanau grain trade; 11 years in agricultural lending at a development bank.",
                      "Abdullahi Sani, COO: nine years running agro-processing logistics."],
            team=["31 people, 22 of them in grading, warehouse and field operations.",
                  "Hiring a CFO with structured-finance experience from this round."]),
        deckGaps=[],
        dataRoom=standard_room(
            "Silo Credit Nigeria Limited", "the Corporate Affairs Commission (CAC), Nigeria", "RC 1934705", "2022-02-09",
            [("Halima Bello", 44), ("Abdullahi Sani", 22), ("Dala Hill Capital", 14), ("Employee option pool", 10),
             ("Sahelian Growth Partners", 6), ("Business angels", 4)],
            10, "Four-year vesting with a one-year cliff; 12 staff hold options.",
            ["Monthly accounts separating the lending book from operating costs.",
             "Loan book of ₦430m at 30 Sep 2026; peak of ₦640m in December 2025.",
             "Impairment provisions and write-offs by season.",
             "Operating cash at 30 Sep 2026: about $640,000 equivalent."],
            "FIRS Tax Clearance Certificate (2026)",
            ["Tax Clearance Certificate covering the 2023, 2024 and 2025 years of assessment.",
             "Kano State Internal Revenue Service PAYE clearance.",
             "VAT treatment memo on warehouse and grading fees."],
            ["Founder IP assignment covering grading rules, risk model and registry software.",
             "Employment contracts include IP and confidentiality clauses.",
             "Silo Credit trade mark application filed (class 36)."],
            ("Key contract summary: debt facility with a Nigerian commercial bank",
             ["₦1bn revolving facility secured on warehouse receipts; 12-month tenor.",
              "Advance rate 85% of loans outstanding; Silo holds 15% first loss.",
              "Covenants: loss rate under 2%, insurance on all stored grain.",
              "Monthly portfolio and stock audit report to the lender."]),
            ("Board minutes, September 2026",
             ["Approved 2026-27 season lending plan of ₦3.2bn.",
              "Reviewed debt facility term sheets from two lenders.",
              "Approved equity round of $2.5m at a $12m pre-money valuation.",
              "Noted one warehouse suspended pending fumigation re-inspection."]),
            ("Founder and company KYC pack",
             ["CAC status report and particulars of directors.",
              "Directors' BVN, NIN and passports.",
              "Beneficial ownership declaration and SCUML registration certificate."]),
            [("Warehouse certification standard and audit reports", "legal_ip", "ON_REQUEST",
              ["Silo's certification checklist: structure, pest control, security, fire, stacking.",
               "Most recent audit report for each of the 14 warehouses.",
               "Corrective actions and re-inspection dates."]),
             ("Grain insurance policy summary", "contracts", "SHARED_ONLY",
              ["Stock insurance covering fire, theft and flood for grain under receipt.",
               "Sum insured adjusted monthly to graded value.",
               "Claims history: one claim in 2024, settled."])]),
        qGuide=["Speak calmly and plainly. No exaggeration.",
                "Explain the mechanism first: grain is the collateral; the loan is repaid when the grain is sold.",
                "Use exact figures: 14 warehouses, about ₦2.1bn financed, loss rate under half a percent.",
                "Make clear the $2.5m is equity and the loan book is funded by debt.",
                "Never share individual traders' names, balances or locations.",
                "Do not promise investors yields or interest rates on the debt facility.",
                "Price risk is real. If asked, explain loan-to-value and insurance honestly.",
                "Refer debt facility questions to me directly.",
                "Respect that many of our customers prefer Hausa; do not describe them as unsophisticated."],
        qPersonality="FORMAL",
        gateqAnswers={"sector": "Fintech / Agriculture: warehouse-receipt finance", "stage": "seed",
                      "geography": "Kano, Nigeria; Northern Nigeria grain markets",
                      "chequeNeed": {"targetRaise": 2_500_000, "minimumCheque": 100_000, "currency": "USD"},
                      "traction": "14 certified warehouses; about ₦2.1bn financed; 0.4% loss rate",
                      "teamSize": 31})


# ---------------------------------------------------------------- 7 Portside
def c7():
    monthly, cum = cum_from_monthly(1700, 4200, 41_000)
    agencies = [29, 33, 38, 43, 49, 53, 58, 63]
    mrr = [m * 7500 + a * 6 * 15000 for m, a in zip(monthly, agencies)]
    cap = capital(
        2_000_000, "USD", "SAFE (post-money)", "valuationCap", 14_000_000, "2026-12-04", 50_000,
        [("Expansion to Onne and Port Harcourt (office and field team)", 35), ("Product: customs and terminal data integrations", 30),
         ("Sales and agency onboarding", 20), ("Working capital", 15)],
        rounds(("Angel", "2022-09-12", 80_000, "USD", "SAFE (post-money)", "Family and friends"),
               ("Pre-seed", "2023-07-03", 400_000, "USD", "SAFE (post-money)", "Marina Road Capital")),
        ["Marina Road Capital", "Two Lagos importers as angels"],
        300_000, 26_000, 80_000)
    return dict(
        legalName="Portside Logistics Technologies Limited", websiteUrl="https://portside.example",
        foundedDate="2022-08-22", headquarters={"city": "Lagos", "country": "NG"}, currentStageCode="seed",
        headcount=22,
        shortDescription="The software Lagos clearing agents run customs clearance on, from documents to duty payments to sign-offs.",
        primaryDescription=("Portside is customs-clearance software for Nigerian clearing agents working at Apapa and Tin Can ports. "
                            "Every document, duty payment and agency sign-off sits in one place, and the system alerts agents before a delay happens. "
                            "63 clearing agencies use it, 41,000 containers have been processed, and average clearance has fallen from 19 days to 8. "
                            "Portside charges a per-container fee plus seat licences."),
        tags={"industry": ["logistics", "enterprise_software"], "business_model": ["b2b_saas", "transaction_fee"],
              "customer_type": ["small_business", "business_customer"], "geography": ["nigeria", "west_africa", "africa"],
              "other": ["supply_chain", "workflow_automation"]},
        keywords=["customs clearance", "Apapa", "Tin Can", "clearing agents", "demurrage", "port logistics",
                  "Nigeria imports", "freight forwarding", "duty payment", "trade documents", "Lagos ports", "B2B SaaS"],
        brand={"primary": "#B5452B", "accent": "#F2C14E", "ink": "#1A2430",
               "logoConcept": "Four stacked container blocks forming a letter P"},
        founderPerson=dict(
            name="Karim Haddad", role="Founder & CEO", appRole="OWNER", age=36, nationality="Nigerian (Lebanese-Nigerian, born in Lagos)", gender="male",
            city="Lagos", education=["BBA, American University of Beirut (2012)"],
            previousRoles=[{"title": "Clearing and Forwarding Officer", "org": "Family import business, Lagos", "from": 2013, "to": 2019},
                           {"title": "General Manager", "org": "Family import business, Lagos", "from": 2019, "to": 2022}],
            headline="Founder & CEO, Portside | Six years clearing containers at Apapa | Giving importers their days back",
            professionalSummary="Third generation in his family's Lagos import business. Spent six years clearing containers at Apapa and Tin Can himself, then ran the business before building Portside.",
            backgroundSummary="Born and raised in Lagos, studied in Beirut, came home to the family business. Knows every step where a container gets stuck.",
            languages=["English", "Arabic", "French", "Nigerian Pidgin", "Yoruba (conversational)"]),
        team=[person("Folake Adeyemi", "COO", "ADMIN", "Ran operations for a freight forwarder for eight years. Leads agency onboarding and support.", "Nigerian", "female"),
              person("Tunde Balogun", "Head of Product", "MEMBER", "Former product manager at a Lagos logistics marketplace. Owns the workflow engine and alerts.", "Nigerian", "male")],
        capital=cap,
        metrics=metrics([("agencies", "Clearing agencies on Portside", "count", None),
                         ("containers_month", "Containers processed in month", "count", None),
                         ("containers_cumulative", "Containers processed, cumulative", "count", None),
                         ("avg_clearance_days", "Average clearance time on Portside", "days", None),
                         ("mrr", "Monthly revenue", "money", "NGN")],
                        {"agencies": agencies, "containers_month": monthly, "containers_cumulative": cum,
                         "avg_clearance_days": [13.2, 12.1, 11.0, 10.1, 9.2, 8.8, 8.4, 8.0], "mrr": mrr},
                        "Baseline before Portside: 19 days average clearance across onboarding agencies. Revenue = ₦7,500 per container + ₦15,000 per seat per month (about 6 seats per agency)."),
        deck=deck(
            problem=["A container can sit at Apapa for three weeks, and every day someone pays demurrage.",
                     "The days go to paper: duplicate documents, missing forms, and no one knows which step is stuck."],
            solution=["Portside is the software clearing agents run their whole process on.",
                      "Every document, duty payment and agency sign-off in one place.",
                      "Alerts before a delay happens, not after."],
            value_proposition=["Average clearance down from 19 days to 8 on Portside.",
                               "Eleven days of demurrage and storage saved per container.",
                               "Agents handle more containers with the same staff."],
            market=["Every importer in Nigeria needs clearing, so the market is huge."],
            go_to_market=["Direct sales to clearing agencies at Apapa and Tin Can, led by the founder.",
                          "Agencies bring their importer clients onto the shared container view.",
                          "Next: Onne and Port Harcourt."],
            business_model=["₦7,500 per container processed.",
                            "₦15,000 per seat per month; agencies average six seats.",
                            "About ₦37m revenue in September 2026."],
            traction=["63 clearing agencies.",
                      "41,000 containers processed.",
                      "Average clearance cut from 19 days to 8."],
            competition=["Most agents still use paper and WhatsApp. We do not see a real competitor."],
            financials=["Revenue plan: ₦620m in 2027, ₦1.3bn in 2028, ₦2.4bn in 2029.",
                        f"Net burn today about ${cap['monthlyNetBurn']['amount']:,} a month; about ${cap['plannedMonthlyNetBurnPostRaise']['amount']:,} after the raise.",
                        f"Runway after the raise about {cap['runwayMonthsPostRaise']:.0f} months."],
            the_ask=["Raising $2m on a post-money SAFE to expand to Onne and Port Harcourt.",
                     "35% eastern ports expansion, 30% product integrations, 20% sales, 15% working capital."],
            founders=["Karim Haddad, Founder & CEO: third generation in his family's Lagos import business.",
                      "Spent six years clearing containers at Apapa and Tin Can before building Portside."],
            team=["22 people: 8 engineering, 9 onboarding and support, 3 sales, 2 operations.",
                  "COO Folake Adeyemi spent eight years in freight-forwarding operations."]),
        deckGaps=[{"section": "market", "gap": "No TAM/SAM/SOM numbers or method; one sentence."},
                  {"section": "competition", "gap": "Claims no competitor; no named alternatives (e.g. in-house tools, forwarder platforms, the customs service's own system) and no differentiation."}],
        dataRoom=standard_room(
            "Portside Logistics Technologies Limited", "the Corporate Affairs Commission (CAC), Nigeria", "RC 1978120", "2022-08-22",
            [("Karim Haddad", 72), ("Employee option pool", 10), ("Marina Road Capital (as converted)", 13), ("Angels (as converted)", 5)],
            10, "Four-year vesting with a one-year cliff; 9 staff hold options.",
            ["Monthly P&L, balance sheet and cash flow in naira.",
             "Revenue rose from ₦15.4m in Oct 2025 to ₦37.2m in Sep 2026.",
             "Per-container revenue is about 85% of the total; seats the rest.",
             "Cash at 30 Sep 2026: about $300,000 equivalent."],
            "FIRS Tax Clearance Certificate (2026)",
            ["Tax Clearance Certificate covering the 2023, 2024 and 2025 years of assessment.",
             "Monthly VAT and withholding tax filings for the last 12 months.",
             "Lagos State PAYE clearance."],
            ["Founder deed of assignment covering platform code and brand.",
             "IP clauses in all employment and contractor agreements.",
             "Portside word mark registered (class 39 and 42)."],
            ("Key customer contract summary: Apapa clearing agency (name withheld)",
             ["Largest customer: about 610 containers a month across 14 seats.",
              "Standard pricing with a 5% volume discount above 500 containers.",
              "12-month term, auto-renewing; data stays the agency's property.",
              "Service level: 99.5% monthly uptime."]),
            ("Board minutes, June 2026",
             ["Approved $2m seed raise on a post-money SAFE.",
              "Reviewed Onne and Port Harcourt expansion plan and lead customers.",
              "Approved hiring of a finance manager.",
              "Noted two agencies churned after merging with existing customers."]),
            ("Founder and company KYC pack",
             ["CAC status report and particulars of directors.",
              "Founder BVN, NIN and passport.",
              "Beneficial ownership declaration."]),
            [("Clearance time study", "financials", "ON_REQUEST",
              ["How the 19-day baseline and 8-day current average are measured.",
               "Sample of 6,200 containers from agencies with data before and after onboarding.",
               "Clearance measured from vessel discharge to gate-out."])]),
        qGuide=["Be energetic but specific. Numbers beat adjectives.",
                "Lead with days saved: 19 down to 8 on average.",
                "Never name a clearing agency, importer or terminal operator as a customer without permission.",
                "Do not suggest Portside replaces the customs service's own systems. Agents still file through official channels.",
                "Do not talk about any customs officer or agency in a negative way.",
                "If asked about competition, be honest that we need to map it better.",
                "Keep the cap table and contracts in the data room.",
                "Offer a call with me for serious investors. I like to pitch live."],
        qPersonality="WITTY",
        gateqAnswers={"sector": "Logistics / B2B SaaS: customs-clearance workflow", "stage": "seed",
                      "geography": "Lagos, Nigeria (Apapa, Tin Can); expanding to Onne and Port Harcourt",
                      "chequeNeed": {"targetRaise": 2_000_000, "minimumCheque": 50_000, "currency": "USD"},
                      "traction": "63 clearing agencies; 41,000 containers processed; clearance down from 19 to 8 days",
                      "teamSize": 22})


# ---------------------------------------------------------------- 8 MedTrail
def c8():
    monthly, cum = cum_from_monthly(900_000, 1_750_000, 18_000_000)
    wh = [26, 31, 35, 40, 46, 51, 55, 60]
    mrr = [w * 350_000 + m * 3 for w, m in zip(wh, monthly)]
    cap = capital(
        1_500_000, "USD", "SAFE (post-money)", "valuationCap", 10_000_000, "2027-01-22", 40_000,
        [("Distributor onboarding and scanning hardware", 35), ("Engineering: recall console and regulator reporting", 30),
         ("Manufacturer and hospital integrations", 20), ("Working capital and G&A", 15)],
        rounds(("Pre-seed", "2023-06-14", 300_000, "USD", "SAFE (post-money)", "Broad Street Health Angels")),
        ["Broad Street Health Angels", "Two pharmaceutical industry executives as angels"],
        260_000, 24_000, 62_000)
    return dict(
        legalName="MedTrail Health Systems Limited", websiteUrl="https://medtrail.example",
        foundedDate="2023-01-17", headquarters={"city": "Lagos", "country": "NG"}, currentStageCode="seed",
        headcount=19,
        shortDescription="MedTrail serialises medicine packs at Nigerian distributors and tracks each one, so a recall finds every pack in hours, not weeks.",
        primaryDescription=("MedTrail is drug traceability and recall software for Nigerian pharmaceutical distributors. "
                            "It serialises each pack at the distributor and records every movement, so when a batch is recalled the system knows exactly who holds it. "
                            "27 distributors use MedTrail, 18 million packs have been serialised, and its first NAFDAC-recognised recall ran end to end in four hours. "
                            "Distributors pay a per-warehouse subscription plus a per-scan fee."),
        tags={"industry": ["healthcare", "enterprise_software"], "business_model": ["b2b_saas", "transaction_fee"],
              "customer_type": ["business_customer", "enterprise"], "geography": ["nigeria", "west_africa", "africa"],
              "other": ["supply_chain", "regulated_healthcare", "health_access"]},
        keywords=["drug traceability", "pharmaceutical recall", "serialisation", "NAFDAC", "counterfeit medicines",
                  "pharma distribution", "track and trace", "supply chain compliance", "Nigeria health", "batch recall", "expired drugs", "GS1"],
        brand={"primary": "#0067A5", "accent": "#7AC943", "ink": "#0A2233",
               "logoConcept": "A capsule leaving a short dotted trail behind it"},
        founderPerson=dict(
            name="Vikram Chandiramani", role="Co-founder & CEO", appRole="OWNER", age=43, nationality="Nigerian (Indian-Nigerian, born in Lagos)", gender="male",
            city="Lagos", education=["BSc Business Administration, University of Lagos (2005)", "MBA, Lagos Business School (2013)"],
            previousRoles=[{"title": "Operations Manager", "org": "Family pharmaceutical distribution company, Lagos", "from": 2007, "to": 2014},
                           {"title": "Director of Operations", "org": "Family pharmaceutical distribution company, Lagos", "from": 2014, "to": 2022}],
            headline="Co-founder & CEO, MedTrail | 15 years in Nigerian pharma distribution | Every pack, accounted for",
            professionalSummary="Fifteen years running operations at his family's pharmaceutical distribution company, which has been in the business since the 1970s. Knows recalls from the distributor's side.",
            backgroundSummary="Born and raised in Lagos. Started MedTrail after a recall where his own company could not say where half a batch had gone.",
            languages=["English", "Hindi", "Sindhi", "Yoruba (conversational)"]),
        team=[person("Ngozi Okeke", "Co-founder & CTO", "ADMIN", "Software engineer; previously built warehouse management systems for an FMCG distributor. Leads the serialisation platform.", "Nigerian", "female"),
              person("Yetunde Fashola", "Head of Regulatory Affairs", "MEMBER", "Pharmacist with ten years in regulatory affairs at a manufacturer. Manages NAFDAC engagement and recall procedures.", "Nigerian", "female"),
              person("Samuel Etim", "Field Operations Lead", "MEMBER", "Installs scanners and trains warehouse staff across Lagos, Ogun, Abuja and Onitsha.", "Nigerian", "male")],
        capital=cap,
        metrics=metrics([("distributors", "Distributors live", "count", None),
                         ("warehouses", "Warehouses live", "count", None),
                         ("packs_month", "Packs serialised in month", "count", None),
                         ("packs_cumulative", "Packs serialised, cumulative", "count", None),
                         ("mrr", "Monthly revenue", "money", "NGN")],
                        {"distributors": [12, 14, 16, 18, 21, 23, 25, 27], "warehouses": wh,
                         "packs_month": monthly, "packs_cumulative": cum, "mrr": mrr},
                        "Revenue = ₦350,000 per warehouse per month + ₦3 per pack scan."),
        deck=deck(
            problem=["When a batch of medicine is recalled in Nigeria, nobody can say where it went.",
                     "It could be in a hospital in Abuja or a market stall in Onitsha; recalls take weeks.",
                     "That gap is how fake and expired drugs survive."],
            solution=["MedTrail serialises every pack at the distributor.",
                      "Each pack is scanned as it moves to wholesalers, pharmacies and hospitals.",
                      "On a recall, MedTrail lists exactly who holds the batch within minutes."],
            value_proposition=["Distributors meet recall obligations in hours, not weeks.",
                               "Manufacturers see where their product actually goes.",
                               "Patients are less likely to receive recalled or diverted medicine."],
            market=["Method: packs moving through organised distribution × per-pack fee, plus warehouse subscriptions.",
                    "TAM: about 2.5 billion packs a year through registered distributors = ₦7.5bn in scan fees plus ₦4bn in subscriptions.",
                    "SAM: top 300 distributors in Lagos, Ogun, Abuja, Kano and Onitsha = ₦6bn.",
                    "SOM: 120 distributors by 2029 = ₦1.4bn annual revenue."],
            go_to_market=["Founder-led sales through distributor associations and personal relationships.",
                          "Manufacturers ask their distributors to adopt MedTrail for recall coverage.",
                          "Regulatory recognition of the four-hour recall as proof point."],
            business_model=["Per-warehouse subscription of ₦350,000 a month.",
                            "₦3 per pack scan.",
                            "About ₦26m revenue in September 2026; gross margin 72%."],
            traction=["27 distributors; 60 warehouses.",
                      "18 million packs serialised.",
                      "First NAFDAC-recognised recall run end to end in four hours."],
            competition=["Sproxil and mPedigree: consumer-facing authentication codes, strong with manufacturers.",
                         "TraceLink: global serialisation network built for regulated Western markets, priced accordingly.",
                         "Spreadsheets and phone calls: the default today.",
                         "MedTrail works from the distributor outward, which is where Nigerian recalls break."],
            financials=["Revenue plan: ₦480m in 2027, ₦950m in 2028, ₦1.7bn in 2029.",
                        f"Net burn today about ${cap['monthlyNetBurn']['amount']:,} a month; about ${cap['plannedMonthlyNetBurnPostRaise']['amount']:,} after the raise.",
                        f"Runway after the raise about {cap['runwayMonthsPostRaise']:.0f} months; break-even in 2029."],
            the_ask=["Raising a $1.5m seed on a post-money SAFE.",
                     "35% distributor onboarding, 30% engineering, 20% integrations, 15% working capital."],
            founders=["Vikram Chandiramani, CEO: 15 years running pharmaceutical distribution operations in Lagos.",
                      "Ngozi Okeke, CTO: built warehouse systems for an FMCG distributor."],
            team=["19 people: 7 engineering, 8 field operations, 2 regulatory, 2 commercial.",
                  "Head of Regulatory Affairs Yetunde Fashola is a pharmacist with ten years in regulatory affairs."]),
        deckGaps=[],
        dataRoom=standard_room(
            "MedTrail Health Systems Limited", "the Corporate Affairs Commission (CAC), Nigeria", "RC 6905532", "2023-01-17",
            [("Vikram Chandiramani", 48), ("Ngozi Okeke", 27), ("Employee option pool", 10),
             ("Broad Street Health Angels (as converted)", 11), ("Angels (as converted)", 4)],
            10, "Four-year vesting with a one-year cliff; 8 staff hold options.",
            ["Monthly P&L, balance sheet and cash flow in naira.",
             "Revenue rose from ₦11.8m in Oct 2025 to ₦26.3m in Sep 2026.",
             "Scanner hardware capitalised; three-year depreciation.",
             "Cash at 30 Sep 2026: about $260,000 equivalent."],
            "FIRS Tax Clearance Certificate (2026)",
            ["Tax Clearance Certificate covering the 2023, 2024 and 2025 years of assessment.",
             "VAT returns and withholding tax schedules for the last 12 months.",
             "Lagos State PAYE clearance."],
            ["Founder and CTO deeds of assignment covering platform code and data model.",
             "IP clauses in all staff and contractor agreements.",
             "MedTrail trade mark application filed (classes 9 and 42)."],
            ("Key customer contract summary: national pharmaceutical distributor (name withheld)",
             ["Nine warehouses on subscription; about 420,000 pack scans a month.",
              "Recall service level: holder list within 60 minutes of a recall notice.",
              "Data processing agreement; distributor owns its trade data.",
              "Two-year term from February 2026."]),
            ("Board minutes, August 2026",
             ["Reviewed the four-hour recall and NAFDAC's recognition letter.",
              "Approved the $1.5m seed raise.",
              "Approved pilot with two manufacturers for upstream serialisation.",
              "Noted scanner supply lead times of eight weeks."]),
            ("Founder and company KYC pack",
             ["CAC status report and particulars of directors.",
              "Directors' BVN, NIN and passports.",
              "Beneficial ownership declaration."]),
            [("Recall exercise report and NAFDAC recognition letter", "legal_ip", "SHARED_ONLY",
              ["Timeline of the August 2026 recall from notice to last confirmed holder: 4 hours.",
               "Batch traced across 9 states and 214 receiving outlets.",
               "Copy of NAFDAC's letter recognising the exercise.",
               "Lessons learned and fixes."]),
             ("Data protection compliance filing", "legal_ip", "ON_REQUEST",
              ["Data protection audit filed with the Nigeria Data Protection Commission.",
               "Records of processing for distributor and outlet data.",
               "No patient data is collected."])]),
        qGuide=["Plain-spoken and steady. I have been in this business a long time and I do not oversell.",
                "Say 'recognised by NAFDAC' only for the specific four-hour recall exercise. Never say NAFDAC endorses MedTrail.",
                "Use the exact numbers: 27 distributors, 18 million packs, four hours.",
                "Do not name distributors or manufacturers without their written consent.",
                "Do not speculate about specific counterfeit cases or name companies involved in them.",
                "We collect no patient data. Say so if asked.",
                "If asked about my family's company, say it is one customer on standard terms and the board has approved the related-party arrangement.",
                "Route questions on contracts and the cap table to the data room request flow."],
        qPersonality="DIRECT",
        gateqAnswers={"sector": "Health / B2B SaaS: pharmaceutical traceability and recall", "stage": "seed",
                      "geography": "Lagos, Nigeria; distributors in Lagos, Ogun, Abuja and Onitsha",
                      "chequeNeed": {"targetRaise": 1_500_000, "minimumCheque": 40_000, "currency": "USD"},
                      "traction": "27 distributors; 18m packs serialised; first NAFDAC-recognised recall run in 4 hours",
                      "teamSize": 19})


# ---------------------------------------------------------------- 9 Baridi
def c9():
    rooms = [24, 27, 30, 33, 37, 40, 43, 46]
    rev = [r * 110 * 30 * 35 for r in rooms]
    cap = capital(
        2_200_000, "USD", "Convertible note", "valuationCap", 11_000_000, "2027-03-12", 50_000,
        [("Field operations and new landing beaches", 35), ("Room engineering and remote monitoring", 20),
         ("Senior hires (finance, operations)", 20), ("Working capital and maintenance reserve", 25)],
        rounds(("Grant", "2023-05-10", 250_000, "USD", "Grant (non-dilutive)", "Lakeshore Climate Challenge Fund"),
               ("Pre-seed", "2024-04-22", 600_000, "USD", "Convertible note", "Nyanza Impact Partners")),
        ["Nyanza Impact Partners", "Lakeshore Climate Challenge Fund (grant)", "Four Nairobi angels"],
        450_000, 52_000, 100_000,
        extra={"assetFinance": {"purpose": "Next 100 cold rooms", "targetAmount": 1_650_000, "currency": "USD",
                                "unitCost": {"amount": 16_500, "currency": "USD"}, "status": "term sheets requested"}})
    return dict(
        legalName="Baridi Cooling Limited", websiteUrl="https://baridi.example",
        foundedDate="2023-02-13", headquarters={"city": "Kisumu", "country": "KE"}, currentStageCode="seed",
        headcount=27,
        shortDescription="Solar cold rooms at Lake Victoria landing beaches; fish traders pay per crate per day on mobile money.",
        primaryDescription=("Baridi builds and runs solar-powered cold rooms at fish landing beaches around Lake Victoria. "
                            "Traders, most of them women who buy fish the same morning, pay per crate per day through mobile money rather than buying equipment. "
                            "Baridi runs 46 cold rooms used by about 3,800 traders, and spoilage among users has fallen from about 30% to around 6%. "
                            "It is raising equity alongside asset finance for its next hundred rooms."),
        tags={"industry": ["energy", "agriculture"], "business_model": ["transaction_fee", "services"],
              "customer_type": ["small_business", "consumer"], "geography": ["kenya", "east_africa", "africa"],
              "other": ["energy_access", "clean_energy", "climate", "financial_inclusion", "economic_opportunity"]},
        keywords=["cold storage", "solar cooling", "Lake Victoria", "fish traders", "post-harvest loss", "Kisumu",
                  "cooling as a service", "mobile money", "M-Pesa", "productive use solar", "women traders", "food loss"],
        brand={"primary": "#2A9DD6", "accent": "#F7931E", "ink": "#10293A",
               "logoConcept": "A low sun over a single crate outline"},
        founderPerson=dict(
            name="Anjali Shah", role="Co-founder & CEO", appRole="OWNER", age=35, nationality="Kenyan", gender="female",
            city="Kisumu", education=["BSc Mechanical Engineering, University of Nairobi (2013)", "MSc Sustainable Energy Engineering, KTH Royal Institute of Technology (2015)"],
            previousRoles=[{"title": "Field Engineer", "org": "Solar home-system company, East Africa", "from": 2015, "to": 2018},
                           {"title": "Head of Field Operations, East Africa", "org": "Solar home-system company", "from": 2018, "to": 2022}],
            headline="Co-founder & CEO, Baridi | Solar cold rooms at Lake Victoria | Field operations, not slideware",
            professionalSummary="Engineer who led field operations for a solar home-system company across Kenya, Uganda and Tanzania. Moved back to Kisumu in 2022 and co-founded Baridi.",
            backgroundSummary="Kenyan-born, from a Kisumu family. Grew up near the lake, left for university and work in Nairobi, and came back to build cold storage at the beaches.",
            languages=["English", "Swahili", "Gujarati", "Dholuo (basic)"]),
        team=[person("Otieno Ouma", "Co-founder & COO", "ADMIN", "Grew up on Dunga beach; ran a fish-trading business and a boat-repair yard. Leads beach operations.", "Kenyan", "male"),
              person("Akinyi Achieng", "Community Lead", "MEMBER", "Former beach management unit secretary. Runs trader sign-up and the traders' feedback meetings.", "Kenyan", "female")],
        capital=cap,
        metrics=metrics([("cold_rooms", "Cold rooms operating", "count", None),
                         ("active_traders", "Active traders", "count", None),
                         ("spoilage_pct", "Spoilage among Baridi traders", "percent", None),
                         ("revenue_month", "Revenue in month", "money", "KES")],
                        {"cold_rooms": rooms, "active_traders": [1900, 2150, 2450, 2750, 3100, 3350, 3550, 3800],
                         "spoilage_pct": [9.5, 8.8, 8.1, 7.4, 6.9, 6.5, 6.2, 6.0], "revenue_month": rev},
                        "Baseline spoilage before Baridi is about 30%. Revenue = rooms × about 110 crates a day × 30 days × KES 35 per crate-day."),
        deck=deck(
            problem=["Almost a third of the fish caught on Lake Victoria is lost before it is sold, because landing beaches have no cold storage.",
                     "The loss falls mostly on women traders who bought the fish that morning."],
            solution=["Solar-powered cold rooms built right at the beach.",
                      "Traders do not buy anything; they pay per crate, per day, on mobile money.",
                      "Remote monitoring of temperature and power for every room."],
            value_proposition=["Spoilage among our traders down from about 30% to around 6%.",
                               "Traders can sell over two or three days instead of dumping at a low price.",
                               "No upfront cost and no diesel."],
            market=["Method: landing beaches on the Kenyan, Ugandan and Tanzanian shores × rooms each × annual revenue per room.",
                    "TAM: about 1,400 landing sites × 2 rooms × $11,000 a year = $30.8m.",
                    "SAM: 320 larger Kenyan and Ugandan landing sites = $7.0m.",
                    "SOM: 150 rooms by 2028 = $1.65m a year."],
            go_to_market=["Beach management units invite Baridi and allocate sites.",
                          "Community lead signs up traders in person; first week free.",
                          "Payments and reminders through M-Pesa."],
            business_model=["KES 35 per crate per day, paid through mobile money.",
                            "A room averages about 110 crates a day.",
                            "Room costs about $16,500 installed; financed through asset finance."],
            traction=["46 cold rooms; about 3,800 traders.",
                      "Spoilage down from about 30% to around 6%.",
                      "KES 5.3m revenue in September 2026."],
            competition=["ColdHubs (Nigeria): solar walk-in cold rooms for produce, similar pay-per-crate model.",
                         "SokoFresh (Kenya): cold storage for horticulture.",
                         "Ice from diesel-powered plants: expensive and melts by afternoon.",
                         "Baridi is built for fish at the beach, with daily mobile-money pricing."],
            financials=["We expect each room to pay back in about three years, and the company to reach profitability at around 150 rooms."],
            the_ask=["Raising $2.2m on a convertible note, plus asset finance for the next 100 rooms.",
                     "35% field operations, 25% working capital and maintenance, 20% engineering, 20% senior hires."],
            founders=["Anjali Shah, CEO: engineer; led field operations for a solar home-system company across East Africa.",
                      "Otieno Ouma, COO: grew up on a landing beach; ran fish trading and boat repair."],
            team=["Small, committed team in Kisumu."]),
        deckGaps=[{"section": "financials", "gap": "No revenue projection, burn or runway; a payback claim only."},
                  {"section": "team", "gap": "One line; no headcount, functions or hiring plan."}],
        dataRoom=standard_room(
            "Baridi Cooling Limited", "the Business Registration Service (BRS), Kenya", "PVT-6LU2MK8R", "2023-02-13",
            [("Anjali Shah", 46), ("Otieno Ouma", 24), ("Nyanza Impact Partners (as converted)", 14), ("Employee option pool", 10),
             ("Nairobi angels (as converted)", 6)],
            10, "Four-year vesting with a one-year cliff; beach supervisors are eligible.",
            ["Monthly management accounts in Kenya shillings.",
             "Revenue grew from KES 2.8m in Oct 2025 to KES 5.3m in Sep 2026.",
             "Room-level P&L: average room covers its operating cost from month four.",
             "Cash at 30 Sep 2026: about $450,000 equivalent."],
            "KRA Tax Compliance Certificate",
            ["Tax Compliance Certificate issued by the Kenya Revenue Authority, valid to June 2027.",
             "Corporate income tax returns for 2023 and 2024.",
             "PAYE, NSSF and SHIF remittance records."],
            ["Founder IP assignment covering room design, monitoring firmware and brand.",
             "Contractor agreements with IP assignment for the refrigeration design firm.",
             "Baridi trade mark registered with KIPI (class 39)."],
            ("Key contract summary: site agreement with a beach management unit",
             ["Five-year site licence for two rooms at a Homa Bay County landing beach.",
              "Baridi pays a monthly site fee and employs two local attendants.",
              "Pricing changes require 30 days' notice to the beach management unit.",
              "Either side may terminate with 90 days' notice."]),
            ("Board minutes, Q3 2026",
             ["Approved convertible note round of $2.2m with an $11m cap.",
              "Reviewed asset finance options for 100 rooms.",
              "Approved Uganda feasibility visit.",
              "Noted three rooms with inverter faults; replaced under warranty."]),
            ("Founder and company KYC pack",
             ["Certificate of incorporation and CR12 (list of directors and shareholders).",
              "Directors' national IDs and KRA PINs.",
              "Beneficial ownership register filing."]),
            [("Spoilage measurement method", "financials", "ON_REQUEST",
              ["How spoilage is measured: weighed rejects at sale versus crate intake weight.",
               "Baseline from 2023 survey of 640 traders at 12 beaches.",
               "Monthly sample of 300 Baridi traders."])]),
        qGuide=["Practical and upbeat. Talk like someone who has been on the beach this morning.",
                "Say 'around six percent' for spoilage, and give the baseline of about thirty.",
                "Our customers are traders, mostly women. Never describe them as beneficiaries.",
                "Do not name individual traders or share their payment data.",
                "Be clear the $2.2m is a convertible note and asset finance is separate.",
                "If asked about financial projections, offer the model on request rather than guessing.",
                "Do not overstate climate impact. We cut food loss and diesel use; we do not sell carbon credits.",
                "If an investor is outside East Africa and wants a site visit, offer one."],
        qPersonality="AUTO",
        gateqAnswers={"sector": "Climate / Energy access: productive-use solar cold storage", "stage": "seed",
                      "geography": "Kisumu, Kenya; Lake Victoria landing beaches",
                      "chequeNeed": {"targetRaise": 2_200_000, "minimumCheque": 50_000, "currency": "USD"},
                      "traction": "46 cold rooms; about 3,800 traders; spoilage cut from 30% to around 6%",
                      "teamSize": 27})


# ---------------------------------------------------------------- 10 Prumo
def c10():
    sites = geo(236, 410)
    arr = [s * 2236 * 12 for s in sites]
    cap = capital(
        12_000_000, "USD", "Priced equity (Series A preferred)", "preMoneyValuation", 55_000_000, "2027-03-05", 500_000,
        [("Sales expansion: Rio de Janeiro, Minas Gerais, Paraná and the Northeast", 35),
         ("Product: photo reading and budget forecasting", 30), ("ERP and bank integrations", 20), ("Customer success", 15)],
        rounds(("Pre-seed", "2021-11-08", 1_500_000, "BRL", "Convertible note (mútuo conversível)", "São Paulo construction angels"),
               ("Seed", "2022-10-17", 2_500_000, "USD", "Priced equity", "Paulista Seed Partners")),
        ["Paulista Seed Partners", "Andaime Capital", "São Paulo construction angels"],
        3_400_000, 260_000, 560_000)
    return dict(
        legalName="Prumo Tecnologia para Construção Ltda.", websiteUrl="https://prumo.example",
        foundedDate="2021-07-26", headquarters={"city": "São Paulo", "country": "BR"}, currentStageCode="series_a",
        headcount=85,
        shortDescription="Prumo turns site photos and WhatsApp updates into budget tracking, warning Brazilian builders weeks before a line overruns.",
        primaryDescription=("Prumo is cost-control software for Brazilian construction sites. Site teams keep sending photos and updates the way they already do; Prumo reads them, tracks progress against the budget, and warns managers when a budget line is drifting. "
                            "It runs on 410 active sites with R$11m in annual recurring revenue, sold as a per-project subscription. "
                            "Clients cut budget overruns by 38% on average. "
                            "Prumo is raising a $12m Series A."),
        tags={"industry": ["real_estate", "enterprise_software"], "business_model": ["b2b_saas"],
              "customer_type": ["mid_market", "business_customer"], "geography": ["brazil", "latin_america"],
              "other": ["proptech", "computer_vision", "artificial_intelligence"]},
        keywords=["construction tech", "cost control", "budget overrun", "site photos", "WhatsApp", "Brazil construction",
                  "construtoras", "progress tracking", "São Paulo", "project management", "contech", "obra"],
        brand={"primary": "#D95F18", "accent": "#4A4E54", "ink": "#1C1C1C",
               "logoConcept": "A plumb bob hanging from a straight line"},
        founderPerson=dict(
            name="Rafael Moreira", role="Co-founder & CEO", appRole="OWNER", age=37, nationality="Brazilian", gender="male",
            city="São Paulo", education=["Engenharia Civil, Escola Politécnica da USP (2011)", "MBA in Construction Management, FGV (2017)"],
            previousRoles=[{"title": "Engenheiro de obra (site engineer)", "org": "Residential developer, São Paulo", "from": 2012, "to": 2016},
                           {"title": "Gerente de obras (construction manager)", "org": "Residential developer, São Paulo", "from": 2016, "to": 2021}],
            headline="Co-founder & CEO, Prumo | Civil engineer | Connecting the budget spreadsheet to the site",
            professionalSummary="Civil engineer who ran residential projects for a São Paulo developer for nine years, from site engineer to construction manager. Built Prumo from the reports he wished he had.",
            backgroundSummary="Grew up in Campinas, son of a mestre de obras. Spent nine years explaining delays and overruns to clients before deciding to fix the cause.",
            languages=["Portuguese", "English", "Spanish"]),
        team=[person("Juliana Tavares", "Co-founder & CTO", "ADMIN", "Computer vision engineer; previously led an imaging team at a São Paulo fintech. Owns the photo reading pipeline.", "Brazilian", "female"),
              person("Thiago Albuquerque", "Chief Revenue Officer", "MEMBER", "Sold ERP software to construtoras for ten years. Runs sales and partnerships.", "Brazilian", "male"),
              person("Camila Rocha", "Head of Customer Success", "MEMBER", "Former planning engineer. Leads onboarding and the monthly budget reviews with clients.", "Brazilian", "female")],
        capital=cap,
        metrics=metrics([("arr", "Annual recurring revenue", "money", "BRL"),
                         ("active_sites", "Active sites", "count", None),
                         ("clients", "Construction company clients", "count", None),
                         ("overrun_reduction_pct", "Average reduction in budget overrun", "percent", None)],
                        {"arr": arr, "active_sites": sites, "clients": [58, 63, 68, 73, 79, 84, 89, 94],
                         "overrun_reduction_pct": [33, 34, 35, 36, 37, 37, 38, 38]},
                        "ARR = active sites × average R$2,236 per site per month × 12. Overrun reduction compares each client's overrun on Prumo projects against its own prior three years."),
        deck=deck(
            problem=["Brazilian construction projects end late and over budget.",
                     "The budget lives in a spreadsheet and the site lives in WhatsApp; nobody connects them until it is too late."],
            solution=["Site teams send photos and updates as they already do.",
                      "Prumo reads them and tracks physical progress against each budget line.",
                      "Managers get a warning when a line is drifting, weeks before it becomes a problem."],
            value_proposition=["Overruns cut by 38% on average.",
                               "No new habit for site teams.",
                               "Directors see every site's real position each week."],
            market=["Method: active formal construction sites × annual software spend per site.",
                    "TAM: about 120,000 formal building sites in Brazil × R$27,000 a year = R$3.2bn.",
                    "SAM: 22,000 residential and commercial sites run by mid-sized and large construtoras = R$590m.",
                    "SOM: 2,000 sites by 2029 = R$54m ARR."],
            go_to_market=["Direct sales to construtoras, starting with directors of engineering.",
                          "Land with two or three sites, expand across the portfolio.",
                          "Partnerships with construction ERPs and with banks that finance projects."],
            business_model=["Per-project subscription from R$1,900 to R$3,500 per site per month.",
                            "Average R$2,236 per site per month.",
                            "Gross margin 81%."],
            traction=["R$11m ARR.",
                      "410 active sites with 94 construction companies.",
                      "Clients cut overruns by 38% on average."],
            competition=["Sienge: the dominant construction ERP, strong on accounting, weak on site reality.",
                         "Procore: global project management, priced and built for large projects.",
                         "Prevision and Mobuss Construção: planning and quality tools in Brazil.",
                         "Prumo starts from what the site already sends and ties it to the budget."],
            financials=["ARR target: R$21m end-2027, R$38m end-2028, R$62m end-2029.",
                        f"Net burn today about ${cap['monthlyNetBurn']['amount']:,} a month; about ${cap['plannedMonthlyNetBurnPostRaise']['amount']:,} after the raise.",
                        f"Runway after the raise about {cap['runwayMonthsPostRaise']:.0f} months; break-even planned for 2029."],
            the_ask=["Raising a $12m Series A (priced).",
                     "35% sales expansion, 30% product, 20% integrations, 15% customer success."],
            founders=["Rafael Moreira, CEO: civil engineer, nine years running residential projects in São Paulo.",
                      "Juliana Tavares, CTO: led computer vision at a São Paulo fintech."],
            team=["85 people in São Paulo: 32 engineering and data, 24 sales, 21 customer success, 8 G&A.",
                  "Six former site and planning engineers in customer success."]),
        deckGaps=[],
        dataRoom=standard_room(
            "Prumo Tecnologia para Construção Ltda.", "the Junta Comercial do Estado de São Paulo (JUCESP)",
            "CNPJ 43.218.906/0001-52; NIRE 35236704118", "2021-07-26",
            [("Rafael Moreira", 32), ("Juliana Tavares", 22), ("Paulista Seed Partners", 18), ("Employee option pool", 13),
             ("Andaime Capital", 9), ("Angels", 6)],
            13, "Stock option plan (plano de opções) with four-year vesting and one-year cliff; Delaware flip under evaluation.",
            ["Monthly management accounts in reais, with ARR bridge (new, expansion, churn).",
             "ARR grew from R$6.3m in Oct 2025 to R$11.0m in Sep 2026.",
             "Gross margin 81%; logo churn 1.1% a month.",
             "Cash at 30 Sep 2026: about $3.4m equivalent."],
            "Federal tax clearance (CND) and FGTS certificate",
            ["Certidão Negativa de Débitos relativos a Tributos Federais e à Dívida Ativa da União, valid to January 2027.",
             "FGTS Certificate of Regularity (CRF).",
             "São Paulo municipal ISS clearance."],
            ["Founder IP assignment (cessão de direitos) covering code, models and brand.",
             "IP clauses in all CLT and PJ contracts.",
             "Prumo trade mark registered with INPI (class 42)."],
            ("Key customer contract summary: São Paulo construtora (name withheld)",
             ["38 sites on subscription at R$2,400 per site per month.",
              "Annual contract with automatic renewal; sites can be added monthly.",
              "Data processing under the LGPD; photos stored in Brazil.",
              "Monthly budget review meeting included."]),
            ("Board minutes, Q3 2026",
             ["Approved the Series A process and data room.",
              "Reviewed Rio de Janeiro pilot results (18 sites).",
              "Approved hiring of a CFO.",
              "Discussed logo churn of 1.1% a month and causes."]),
            ("Company KYB pack",
             ["Contrato social (articles) and latest amendment registered at JUCESP.",
              "CNPJ card and partners' CPF documents.",
              "Beneficial ownership declaration to the Receita Federal."]),
            [("Overrun reduction study", "financials", "ON_REQUEST",
              ["Method behind the 38% average reduction.",
               "Compares 212 completed Prumo projects with the same clients' prior three years.",
               "Excludes projects shorter than six months."])]),
        qGuide=["Tell it as a story, but keep the numbers exact.",
                "Say R$11m in recurring revenue and 410 active sites. Give dollar figures only with the exchange rate.",
                "38% is an average reduction in overruns, measured against each client's own history. Explain that if asked.",
                "Never name a client or a building project without permission.",
                "Do not imply site workers are to blame for overruns. The problem is disconnected information.",
                "We read photos and messages that clients share with us. Do not suggest we monitor workers.",
                "Confident, animated tone is fine. Hype words are not.",
                "If asked about Latin American expansion, say this round is for Brazil."],
        qPersonality="WARM",
        gateqAnswers={"sector": "Construction tech / B2B SaaS: site-to-budget cost control", "stage": "series_a",
                      "geography": "São Paulo, Brazil; national expansion",
                      "chequeNeed": {"targetRaise": 12_000_000, "minimumCheque": 500_000, "currency": "USD"},
                      "traction": "R$11m ARR; 410 active sites; overruns cut by 38% on average",
                      "teamSize": 85})


COMPANIES = [c6, c7, c8, c9, c10]
