from common import *
from c01_05 import deck


# ---------------------------------------------------------------- 11 Ferrolith
def c11():
    cap = capital(
        25_000_000, "EUR", "Priced equity (Series A preferred)", "preMoneyValuation", 70_000_000, "2027-03-26", 1_000_000,
        [("First production line: equipment and site fit-out (0.5 GWh/yr)", 60), ("Cell engineering and cathode scale-up", 20),
         ("Safety certification and customer qualification", 10), ("Team and G&A", 10)],
        rounds(("Pre-seed", "2020-12-15", 1_800_000, "EUR", "Priced equity", "Isar Deep Tech Fund"),
               ("Seed", "2022-09-28", 8_000_000, "EUR", "Priced equity", "Isar Deep Tech Fund"),
               ("Grant", "2023-06-01", 4_600_000, "EUR", "Public R&D grants (non-dilutive)", "Federal and Bavarian research programmes")),
        ["Isar Deep Tech Fund", "Alpine Materials Ventures", "Lechfeld Capital", "Angels from the German battery industry"],
        6_800_000, 650_000, 1_350_000,
        extra={"coFinancing": {"note": "Production line total cost about €45m: €15m from this round, plus public co-funding and equipment finance applied for.",
                               "publicCoFundingApplied": {"amount": 18_000_000, "currency": "EUR"},
                               "equipmentFinanceTarget": {"amount": 12_000_000, "currency": "EUR"}}})
    return dict(
        legalName="Ferrolith GmbH", websiteUrl="https://ferrolith.example",
        foundedDate="2020-09-14", headquarters={"city": "Munich", "country": "DE"}, currentStageCode="series_a",
        headcount=64,
        shortDescription="Sodium-ion cells for stationary storage, made in Europe without lithium, cobalt or nickel; validated past 4,000 cycles.",
        primaryDescription=("Ferrolith makes sodium-ion battery cells designed for stationary storage, where cost, safety and cycle life matter more than weight. "
                            "Its cells use abundant materials, contain no lithium, cobalt or nickel, and are much harder to set on fire than lithium-ion cells. "
                            "Cells have been validated past 4,000 cycles; a pilot line in Munich produces 40 MWh a year, and storage integrators have signed letters of intent for 1.2 GWh. "
                            "Ferrolith sells cells and licenses its process to storage integrators, and is raising €25m to build its first production line."),
        tags={"industry": ["energy", "manufacturing"], "business_model": ["hardware_sales", "licensing"],
              "customer_type": ["enterprise", "business_customer"], "geography": ["germany", "europe"],
              "other": ["clean_energy", "climate", "hardware"]},
        keywords=["sodium-ion", "battery cells", "stationary storage", "grid storage", "lithium-free", "cobalt-free",
                  "battery manufacturing", "Europe", "energy transition", "BESS", "cell chemistry", "Munich", "deep tech"],
        brand={"primary": "#5B6770", "accent": "#D4A017", "ink": "#1A1D20",
               "logoConcept": "Cross-section of a cell drawn as three flat layers"},
        founderPerson=dict(
            name="Matthias Krüger", role="Co-founder & CEO", appRole="OWNER", age=52, nationality="German", gender="male",
            city="Munich", education=["Diplom in Chemistry, Technical University of Munich (1999)", "Dr. rer. nat. in Electrochemistry, Karlsruhe Institute of Technology (2003)"],
            previousRoles=[{"title": "Research Scientist, battery materials", "org": "Applied research institute, Germany", "from": 2003, "to": 2008},
                           {"title": "Senior Engineer, cell development", "org": "European automotive supplier", "from": 2008, "to": 2014},
                           {"title": "Head of Cell Development", "org": "European automotive supplier", "from": 2014, "to": 2020}],
            headline="Co-founder & CEO, Ferrolith | Electrochemist | Storage that Europe can make itself",
            professionalSummary="Electrochemist with twenty years in battery R&D, most recently head of cell development at a European automotive supplier. Leads Ferrolith's chemistry choices and its manufacturing plan.",
            backgroundSummary="Grew up in Augsburg. Spent his career on lithium-ion for cars and concluded that stationary storage needs a different chemistry.",
            languages=["German", "English"]),
        team=[person("Dr Anna Weber", "Co-founder & CTO", "ADMIN", "Materials scientist; led cathode research at a German university for eight years. Owns the cathode process and cell design.", "German", "female"),
              person("Lukas Hoffmann", "COO", "MEMBER", "Ran battery module production lines for an automotive supplier. Leads the pilot line and production line build.", "German", "male"),
              person("Sabine Richter", "CFO", "MEMBER", "Previously CFO of an industrial hardware company. Leads grant, debt and equity financing.", "German", "female")],
        capital=cap,
        metrics=metrics([("pilot_capacity_mwh_yr", "Pilot line annualised capacity", "MWh_per_year", None),
                         ("loi_gwh", "Offtake letters of intent", "GWh", None),
                         ("validated_cycles", "Validated cycles at 80% capacity retention (best cell group)", "cycles", None),
                         ("sample_cells_shipped", "Sample cells shipped to integrators, cumulative", "count", None),
                         ("revenue_month", "Sample and engineering revenue in month", "money", "EUR")],
                        {"pilot_capacity_mwh_yr": [12, 12, 20, 20, 28, 32, 36, 40],
                         "loi_gwh": [0.3, 0.3, 0.55, 0.55, 0.9, 0.9, 1.2, 1.2],
                         "validated_cycles": [3100, 3250, 3420, 3580, 3760, 3850, 3960, 4150],
                         "sample_cells_shipped": geo(1400, 9800, 0), "revenue_month": geo(38_000, 118_000, 0)},
                        "Cycle counts are from the longest-running validated cell group at 25°C, 1C/1C, 100% depth of discharge."),
        deck=deck(
            problem=["Stationary storage uses lithium-ion because cars did, but a battery next to a solar farm does not care about weight.",
                     "It cares about cost, safety and cycle life, and Europe depends on imported cells and critical minerals."],
            solution=["Sodium-ion cells built for batteries that never move.",
                      "Iron-based Prussian-white cathode and hard-carbon anode: no lithium, cobalt or nickel.",
                      "Abundant materials and cells that are much harder to set on fire."],
            value_proposition=["Lower material cost and less price volatility than lithium-ion.",
                               "Safer cells mean simpler fire protection for integrators.",
                               "European-made, with no critical raw materials in the bill of materials."],
            market=["Method: projected stationary storage deployments × cell price per kWh.",
                    "TAM: about 600 GWh of global stationary storage a year by 2030 × €55/kWh = €33bn.",
                    "SAM: European stationary storage, about 80 GWh a year by 2030 × €70/kWh = €5.6bn.",
                    "SOM: 2 GWh a year by 2030 = €140m."],
            go_to_market=["Sell cells to storage integrators who build containerised systems.",
                          "Qualify with three integrators now holding letters of intent.",
                          "License the process to regional manufacturers outside Europe after the first line."],
            business_model=["Cell sales priced per kWh, targeting €70/kWh at production scale.",
                            "Process licensing with royalties per GWh produced.",
                            "Target gross margin of 22% on cells at full production."],
            traction=["Cells validated past 4,000 cycles.",
                      "Pilot line producing 40 MWh a year.",
                      "Letters of intent for 1.2 GWh from three integrators."],
            competition=["CATL and BYD: large sodium-ion programmes, made in China.",
                         "Altris (Sweden): Prussian-white cathode materials.",
                         "Peak Energy (US): sodium-ion systems for grid storage.",
                         "LFP lithium-ion incumbents: the price to beat. Ferrolith competes on safety, supply security and cost stability in Europe."],
            financials=["Revenue: €2.5m in 2027, €18m in 2028 (production ramp), €52m in 2029.",
                        f"Net burn today about €{cap['monthlyNetBurn']['amount']:,} a month; about €{cap['plannedMonthlyNetBurnPostRaise']['amount']:,} including line build after the raise.",
                        f"Runway after the raise about {cap['runwayMonthsPostRaise']:.0f} months, before public co-funding and equipment finance."],
            the_ask=["Raising €25m Series A (priced) to build the first production line.",
                     "60% production line, 20% cell engineering, 10% certification, 10% team and G&A.",
                     "Line total cost about €45m, with public co-funding and equipment finance applied for."],
            founders=["Matthias Krüger, CEO: electrochemist, 20 years in battery R&D, former head of cell development at an automotive supplier.",
                      "Dr Anna Weber, CTO: led cathode research at a German university."],
            team=["64 people in Munich: 38 R&D and engineering, 16 pilot line, 10 commercial and G&A.",
                  "COO Lukas Hoffmann has built automotive battery module lines."]),
        deckGaps=[],
        dataRoom=standard_room(
            "Ferrolith GmbH", "the commercial register at the Amtsgericht München", "HRB 259417", "2020-09-14",
            [("Matthias Krüger", 26), ("Isar Deep Tech Fund", 22), ("Dr Anna Weber", 18), ("Alpine Materials Ventures", 12),
             ("Virtual stock option pool (VSOP)", 12), ("Lechfeld Capital", 6), ("Angels", 4)],
            12, "Virtual stock option plan (VSOP), four-year vesting with a one-year cliff, paid out on exit.",
            ["Monthly management accounts under German GAAP (HGB).",
             "Sample and engineering revenue of about €0.86m over the last 12 months.",
             "Grant receivables and capitalised pilot line equipment shown separately.",
             "Cash at 30 Sep 2026: €6.8m; monthly net burn about €650k."],
            "Tax clearance certificate (Unbedenklichkeitsbescheinigung)",
            ["Certificate of tax compliance from the Finanzamt München, issued August 2026.",
             "Corporate and trade tax filings for 2023 and 2024.",
             "VAT returns for the last 12 months."],
            ["Inventor assignments under the German Employee Inventions Act for all staff inventors.",
             "Five granted patents and seven pending applications (EP and US) on cathode synthesis and electrolyte.",
             "University licence for one background patent, exclusive in the field of stationary storage."],
            ("Key contract summary: offtake letter of intent with a storage integrator (name withheld)",
             ["Non-binding letter of intent for 500 MWh over 2028-2030.",
              "Indicative price range per kWh tied to qualification results.",
              "Conversion to supply agreement after module-level qualification.",
              "Exclusivity: none."]),
            ("Board (Beirat) minutes and shareholder resolutions, 2026",
             ["Shareholders approved the Series A process and the VSOP extension.",
              "Advisory board reviewed site options for the production line (Bavaria and Saxony).",
              "Approved application for public co-funding of the production line.",
              "Noted cycle-test results above 4,000 cycles."]),
            ("Company KYB pack",
             ["Commercial register extract and list of shareholders (Gesellschafterliste).",
              "Transparency register entry.",
              "Managing directors' ID documents."]),
            [("Third-party cycle-life test report", "legal_ip", "SHARED_ONLY",
              ["Independent laboratory test of 24 cells, 25°C, 1C/1C, full depth of discharge.",
               "Capacity retention curves to 4,150 cycles.",
               "Abuse tests: nail penetration and overcharge results."]),
             ("Production line business plan and capex schedule", "financials", "SHARED_ONLY",
              ["Line design for 0.5 GWh a year; total cost about €45m.",
               "Equipment supplier quotes and lead times.",
               "Financing plan: equity, public co-funding and equipment finance."])]),
        qGuide=["Be deliberate and exact. I would rather say less and be right.",
                "4,000 cycles means validated cycles at 80% capacity retention under stated conditions. Give the conditions if asked.",
                "Letters of intent are not purchase orders. Always call them letters of intent.",
                "Never claim our cells cannot catch fire. Say they are much harder to set on fire than lithium-ion.",
                "Do not name integrators who signed letters of intent.",
                "Explain the production line financing honestly: this round plus co-funding and equipment finance we have applied for.",
                "Avoid comparisons with car batteries beyond the weight point.",
                "Technical detail is welcome with technical investors. Keep it plain for generalists.",
                "Formal tone."],
        qPersonality="FORMAL",
        gateqAnswers={"sector": "Deep tech / Climate: sodium-ion battery cells for stationary storage", "stage": "series_a",
                      "geography": "Munich, Germany; European customers",
                      "chequeNeed": {"targetRaise": 25_000_000, "minimumCheque": 1_000_000, "currency": "EUR"},
                      "traction": "Pilot line at 40 MWh/yr; 3 offtake letters of intent totalling 1.2 GWh; cells validated past 4,000 cycles",
                      "teamSize": 64})


# ---------------------------------------------------------------- 12 Shiftwell
def c12():
    cg = geo(21_500, 38_000)
    arr = [c * 9 * 12 for c in cg]
    cap = capital(
        15_000_000, "USD", "Priced equity (Series A preferred)", "preMoneyValuation", 65_000_000, "2027-02-19", 500_000,
        [("Sales and marketing: expand from 9 to 22 states", 40), ("Product: billing, claims and state EVV integrations", 30),
         ("Customer onboarding and payroll operations", 20), ("G&A, security and compliance (SOC 2, HIPAA)", 10)],
        rounds(("Pre-seed", "2022-06-02", 900_000, "USD", "SAFE (post-money)", "Midwest operator angels"),
               ("Seed", "2023-09-12", 4_000_000, "USD", "Priced equity", "Buckeye Harbor Ventures")),
        ["Buckeye Harbor Ventures", "Lakefront Health Capital", "Midwest operator angels"],
        4_200_000, 310_000, 700_000)
    return dict(
        legalName="Shiftwell, Inc.", websiteUrl="https://shiftwell.example",
        foundedDate="2022-03-07", headquarters={"city": "Columbus", "region": "Ohio", "country": "US"}, currentStageCode="series_a",
        headcount=62,
        shortDescription="Scheduling, EVV, payroll and billing for US home-care agencies in one system, built by a former agency owner.",
        primaryDescription=("Shiftwell is one system for US home-care agencies to schedule caregivers, run electronic visit verification, pay staff and bill Medicaid and other payers. "
                            "When a caregiver clocks in at a client's home, payroll and billing update automatically instead of being reconciled by hand. "
                            "290 agencies use it, about 38,000 caregivers are paid through the platform, and ARR is $4.1m on a per-caregiver monthly price. "
                            "The founder ran a 400-caregiver agency in Ohio for eight years."),
        tags={"industry": ["healthcare", "enterprise_software"], "business_model": ["b2b_saas"],
              "customer_type": ["small_business", "mid_market"], "geography": ["united_states", "north_america"],
              "other": ["hr_technology", "workflow_automation", "regulated_healthcare"]},
        keywords=["home care", "caregiver scheduling", "EVV", "electronic visit verification", "Medicaid billing",
                  "payroll", "home health", "workforce management", "agency software", "Ohio", "healthcare SaaS", "caregivers"],
        brand={"primary": "#7B2D8E", "accent": "#F6C9A8", "ink": "#22182A",
               "logoConcept": "A rounded clock whose hands form a check mark"},
        founderPerson=dict(
            name="Megan Holloway", role="Founder & CEO", appRole="OWNER", age=39, nationality="American", gender="female",
            city="Columbus", education=["BS Health Services Administration, Ohio University (2009)"],
            previousRoles=[{"title": "Scheduling Coordinator to Operations Manager", "org": "Home-care agency, Ohio", "from": 2009, "to": 2013},
                           {"title": "Owner & CEO", "org": "Home-care agency with 400 caregivers, Ohio", "from": 2013, "to": 2021},
                           {"title": "Operating adviser to home-care agencies", "org": "Self-employed", "from": 2021, "to": 2022}],
            headline="Founder & CEO, Shiftwell | Ran a 400-caregiver home-care agency for 8 years | Pay caregivers right, and on time",
            professionalSummary="Ran a home-care agency with 400 caregivers in Ohio for eight years, using five systems that did not talk to each other. Sold the agency and built Shiftwell.",
            backgroundSummary="Started as a scheduler at 22 and bought into the agency she later ran. Knows payroll Fridays and Medicaid audits from the inside.",
            languages=["English"]),
        team=[person("Marcus Greene", "CTO", "ADMIN", "Former engineering director at a payroll software company. Leads platform, payroll engine and EVV integrations.", "American", "male"),
              person("Danielle Ortiz", "VP Customer Operations", "MEMBER", "Ran billing for a multi-state home-care group. Leads onboarding and payroll support.", "American", "female"),
              person("Brian Kowalski", "VP Sales", "MEMBER", "Sold scheduling software to post-acute providers for twelve years.", "American", "male")],
        capital=cap,
        metrics=metrics([("arr", "Annual recurring revenue", "money", "USD"),
                         ("agencies", "Agencies", "count", None),
                         ("caregivers_paid", "Caregivers paid through Shiftwell in month", "count", None),
                         ("gross_payroll_month", "Gross caregiver payroll processed in month", "money", "USD")],
                        {"arr": arr, "agencies": geo(168, 290), "caregivers_paid": cg,
                         "gross_payroll_month": [c * 2100 for c in cg]},
                        "ARR = caregivers paid × $9 per caregiver per month × 12. Average gross pay about $2,100 per caregiver per month."),
        deck=deck(
            problem=["Home-care agencies run scheduling, EVV, payroll and billing in separate systems that do not talk to each other.",
                     "Agencies spend days every pay period fixing payroll by hand, and errors hit caregivers' pay and Medicaid claims."],
            solution=["One system for scheduling, electronic visit verification, payroll and billing.",
                      "A caregiver clocks in at a client's home and everything downstream just happens.",
                      "State EVV aggregator integrations built in."],
            value_proposition=["Payroll runs in hours, not days.",
                               "Fewer denied claims because visits, pay and bills come from one record.",
                               "Caregivers paid correctly and on time."],
            market=["Method: home-care aides employed by agencies × annual software spend per caregiver.",
                    "TAM: about 2.6 million agency-employed home-care aides × $180 a year (full suite) = $468m.",
                    "SAM: 900,000 caregivers at Medicaid-funded agencies with 50-1,000 caregivers in 22 target states, at $108 a year = $97m.",
                    "SOM: 125,000 caregivers by 2029 = $13.5m ARR."],
            go_to_market=["Founder-led credibility with agency owners; state home-care association partnerships.",
                          "Inside sales for agencies under 150 caregivers; field sales above.",
                          "Expansion from 9 to 22 states with approved EVV integrations."],
            business_model=["$9 per caregiver per month, all modules included.",
                            "Implementation fee of $2,500-$7,500, waived for annual prepay.",
                            "Gross margin 76%; net revenue retention 118%."],
            traction=["$4.1m ARR.",
                      "290 agencies; about 38,000 caregivers paid through Shiftwell.",
                      "About $80m of caregiver payroll processed each month."],
            competition=["WellSky: broad post-acute suite, complex for small and mid-sized agencies.",
                         "AlayaCare and AxisCare: scheduling-first platforms.",
                         "HHAeXchange: EVV and payer-side portal, not a full agency system.",
                         "Shiftwell connects the clock-in to pay and bill in one record."],
            financials=["ARR target: $7.0m end-2027, $10.4m end-2028, $13.5m end-2029.",
                        f"Net burn today about ${cap['monthlyNetBurn']['amount']:,} a month; about ${cap['plannedMonthlyNetBurnPostRaise']['amount']:,} after the raise.",
                        f"Runway after the raise about {cap['runwayMonthsPostRaise']:.0f} months."],
            the_ask=["Raising a $15m Series A (priced).",
                     "40% sales and marketing, 30% product, 20% onboarding and payroll operations, 10% G&A and compliance."],
            founders=["Megan Holloway, Founder & CEO: ran a 400-caregiver home-care agency in Ohio for eight years and sold it.",
                      "Used five disconnected systems at her agency; Shiftwell is the system she wished she had."],
            team=["62 people: 24 engineering, 16 customer operations, 14 sales, 8 G&A.",
                  "CTO Marcus Greene built payroll engines at a payroll software company."]),
        deckGaps=[],
        dataRoom=standard_room(
            "Shiftwell, Inc.", "the Delaware Division of Corporations", "File number 6587243", "2022-03-07",
            [("Megan Holloway", 44), ("Buckeye Harbor Ventures", 21), ("Employee option pool", 14), ("Marcus Greene", 6),
             ("Lakefront Health Capital", 8), ("Angels", 7)],
            14, "Four-year vesting with a one-year cliff; ISOs for US employees.",
            ["Monthly accrual-basis accounts with ARR bridge and deferred revenue.",
             "ARR grew from $2.32m in Oct 2025 to $4.10m in Sep 2026.",
             "Gross margin 76%; payroll-processing float held in a separate trust account, not on the balance sheet.",
             "Cash at 30 Sep 2026: $4.2m; monthly net burn about $310k."],
            "Tax filings and certificates of good standing",
            ["Federal Form 1120 for 2023, 2024 and 2025.",
             "Delaware certificate of good standing and Ohio certificate of good standing (2026).",
             "State payroll tax registrations in the nine states where Shiftwell files on agencies' behalf."],
            ["CIIAA agreements for founder and all employees.",
             "No open-source licence conflicts in the third-party scan (May 2026).",
             "US trade mark SHIFTWELL registered (class 9 and 42)."],
            ("Key customer contract summary: multi-state home-care agency (name withheld)",
             ["About 3,100 caregivers across Ohio and Pennsylvania; $9 per caregiver per month.",
              "Three-year term from January 2026.",
              "HIPAA business associate agreement in place.",
              "Payroll service level: pay files delivered by 5 pm the day before payday."]),
            ("Board minutes, Q3 2026",
             ["Approved Series A process and target close in Q1 2027.",
              "Reviewed state expansion plan (13 new states).",
              "Approved SOC 2 Type II renewal.",
              "Noted a payroll incident in July affecting 212 caregivers, resolved within one business day."]),
            ("Company KYB pack",
             ["Certificate of incorporation, bylaws and EIN letter.",
              "Beneficial ownership information filing receipt.",
              "Payroll service provider registrations and surety bonds where required."]),
            [("HIPAA risk assessment and SOC 2 Type II report", "legal_ip", "SHARED_ONLY",
              ["SOC 2 Type II report for the period ending March 2026.",
               "Annual HIPAA security risk assessment.",
               "Remediation tracker for open items."]),
             ("Cohort and net revenue retention analysis", "financials", "SHARED_ONLY",
              ["Agency cohorts by quarter since 2022.",
               "Net revenue retention 118% trailing 12 months.",
               "Logo churn by agency size."])]),
        qGuide=["Brisk and practical. I ran an agency; talk like an operator.",
                "Lead with the problem: five systems, payroll fixed by hand every two weeks.",
                "$4.1m ARR, 290 agencies, about 38,000 caregivers paid. Say 'about' for the caregiver figure.",
                "Never share client, patient or caregiver information. We hold PHI under HIPAA; Q does not see it.",
                "Do not name customer agencies without written permission.",
                "Be honest about the July payroll incident if asked, and how fast we fixed it.",
                "Caregivers are workers, not 'resources'. Speak about them with respect.",
                "Route pricing negotiations and term sheet questions to me."],
        qPersonality="DIRECT",
        gateqAnswers={"sector": "Enterprise software / Healthcare workforce SaaS", "stage": "series_a",
                      "geography": "Columbus, Ohio, United States; customers in 9 states",
                      "chequeNeed": {"targetRaise": 15_000_000, "minimumCheque": 500_000, "currency": "USD"},
                      "traction": "$4.1m ARR; 290 agencies; about 38,000 caregivers paid through the platform",
                      "teamSize": 62})


# ---------------------------------------------------------------- 13 Halyard Security
def c13():
    seats = geo(24_000, 71_000)
    cap = capital(
        3_000_000, "GBP", "Priced equity (ordinary shares, SEIS/EIS eligible)", "preMoneyValuation", 10_000_000, "2026-12-16", 25_000,
        [("Deployment team for NHS trusts and councils", 35), ("Product: shared workstation and lost-device flows", 30),
         ("Public-sector sales and framework listings", 25), ("Assurance (Cyber Essentials Plus, DSPT, ISO 27001) and G&A", 10)],
        rounds(("Pre-seed", "2023-05-22", 600_000, "GBP", "Priced equity (SEIS/EIS)", "Leith Shore Angels")),
        ["Leith Shore Angels", "Scottish founder angels"],
        480_000, 70_000, 140_000)
    return dict(
        legalName="Halyard Security Ltd", websiteUrl="https://halyard-security.example",
        foundedDate="2023-01-30", headquarters={"city": "Edinburgh", "country": "GB"}, currentStageCode="seed",
        headcount=21,
        shortDescription="Halyard rolls out phishing-resistant passkeys across NHS trusts and councils, including shared workstations and lost devices.",
        primaryDescription=("Halyard Security handles passkey rollout for NHS trusts and UK councils: enrolment, shared workstations, lost devices and the support that comes with tens of thousands of staff. "
                            "Passkeys cannot be phished, but deploying them to nurses, porters and admin staff on shared computers is the hard part. "
                            "Eleven NHS trusts and councils use Halyard, 64,000 staff are enrolled, and no enrolled account has been taken over by phishing. "
                            "It is sold as a per-user annual licence."),
        tags={"industry": ["cybersecurity", "enterprise_software"], "business_model": ["b2b_saas"],
              "customer_type": ["government", "enterprise"], "geography": ["united_kingdom", "europe"],
              "other": ["identity_security", "data_protection_sensitive"]},
        keywords=["passkeys", "phishing-resistant", "FIDO2", "NHS", "councils", "public sector security", "identity",
                  "passwordless", "shared workstations", "ransomware", "Edinburgh", "authentication"],
        brand={"primary": "#1D3557", "accent": "#E63946", "ink": "#0D1B2A",
               "logoConcept": "A single rope line running up to a pennant flag"},
        founderPerson=dict(
            name="Callum Reid", role="Co-founder & CEO", appRole="OWNER", age=33, nationality="British (Scottish)", gender="male",
            city="Edinburgh", education=["BSc (Hons) Ethical Hacking, Abertay University (2015)"],
            previousRoles=[{"title": "Security Operations Analyst", "org": "Scottish retail bank", "from": 2015, "to": 2017},
                           {"title": "Incident Responder", "org": "National cyber security centre", "from": 2017, "to": 2020},
                           {"title": "Senior Incident Responder, public sector", "org": "National cyber security centre", "from": 2020, "to": 2022}],
            headline="Co-founder & CEO, Halyard Security | Former incident responder | Passwords had a good run",
            professionalSummary="Former incident responder at the national cyber security centre who led the response to two ransomware attacks on public bodies. Both started with a phished password.",
            backgroundSummary="From Dundee. Has spent the nights after hospital ransomware attacks in the room, and decided to work on stopping the first step.",
            languages=["English"]),
        team=[person("Eilidh MacLeod", "Co-founder & CTO", "ADMIN", "Identity engineer; previously built single sign-on for a UK public cloud supplier. Leads the enrolment and recovery platform.", "British (Scottish)", "female"),
              person("Jamie Fraser", "Head of Public Sector Partnerships", "MEMBER", "Ten years selling into NHS boards and councils. Manages framework listings and procurement.", "British (Scottish)", "male")],
        capital=cap,
        metrics=metrics([("organisations", "NHS trusts, health boards and councils", "count", None),
                         ("staff_enrolled", "Staff enrolled with passkeys", "count", None),
                         ("licensed_seats", "Licensed seats", "count", None),
                         ("arr", "Annual recurring revenue", "money", "GBP"),
                         ("phishing_takeovers_enrolled", "Successful phishing takeovers of enrolled accounts", "count", None)],
                        {"organisations": [4, 5, 5, 6, 7, 8, 9, 11], "staff_enrolled": geo(17_000, 64_000),
                         "licensed_seats": seats, "arr": [s * 12 for s in seats],
                         "phishing_takeovers_enrolled": [0, 0, 0, 0, 0, 0, 0, 0]},
                        "ARR = licensed seats × £12 per user per year. Enrolment lags licences during rollout."),
        deck=deck(
            problem=["Most ransomware attacks on hospitals and councils start with one password typed into a fake login page.",
                     "Passkeys stop this, but rollout fails on shared computers, shift workers and lost phones."],
            solution=["Halyard runs the whole passkey rollout: enrolment, shared workstations, lost devices.",
                      "Works on top of the identity provider the organisation already uses.",
                      "Deployment team on site during go-live."],
            value_proposition=["Phishing-resistant sign-in for every member of staff, not just IT.",
                               "No enrolled account taken over by phishing so far.",
                               "Fewer password-reset calls to the service desk."],
            market=["Method: UK public-sector staff × per-user annual licence.",
                    "TAM: about 5.9 million UK public-sector employees × £12 = £71m a year.",
                    "SAM: NHS trusts, health boards and councils, about 3.0 million staff = £36m.",
                    "SOM: 600,000 seats by 2029 = £7.2m ARR."],
            go_to_market=["Sell through public-sector procurement frameworks.",
                          "Land after a near-miss or incident; expand across neighbouring trusts and councils.",
                          "Partnerships with NHS shared IT services."],
            business_model=["£12 per user per year, three-year terms common.",
                            "Deployment fee for on-site go-live support.",
                            "Gross margin 82%."],
            traction=["11 NHS trusts and councils.",
                      "64,000 staff enrolled.",
                      "Zero successful phishing takeovers on enrolled accounts.",
                      "£852k ARR."],
            competition=["Microsoft Entra ID and Okta: identity platforms that support passkeys but leave rollout to the customer.",
                         "Yubico: hardware security keys; strong, but costly to issue to every shift worker.",
                         "Imprivata: fast user switching on clinical workstations.",
                         "Halyard does the rollout itself and works alongside these."],
            financials=["ARR target: £1.9m end-2027, £3.8m end-2028, £6.5m end-2029.",
                        f"Net burn today about £{cap['monthlyNetBurn']['amount']:,} a month; about £{cap['plannedMonthlyNetBurnPostRaise']['amount']:,} after the raise.",
                        f"Runway after the raise about {cap['runwayMonthsPostRaise']:.0f} months."],
            the_ask=["Raising a £3m seed (priced equity, SEIS/EIS eligible).",
                     "35% deployment team, 30% product, 25% sales and frameworks, 10% assurance and G&A."],
            founders=["Callum Reid, CEO: former incident responder; led response to two ransomware attacks on public bodies.",
                      "Eilidh MacLeod, CTO: identity engineer, built single sign-on for a UK public cloud supplier."],
            team=["21 people in Edinburgh and Manchester: 9 engineering, 7 deployment, 3 sales, 2 operations.",
                  "All staff hold or are applying for security clearance."]),
        deckGaps=[],
        dataRoom=standard_room(
            "Halyard Security Ltd", "Companies House (Scotland)", "Company number SC761284", "2023-01-30",
            [("Callum Reid", 38), ("Eilidh MacLeod", 34), ("Employee option pool (EMI)", 10), ("Leith Shore Angels", 13),
             ("Scottish founder angels", 5)],
            10, "EMI options, four-year vesting with a one-year cliff.",
            ["Monthly management accounts in sterling.",
             "ARR rose from £288k in Oct 2025 to £852k in Sep 2026.",
             "Deployment fees recognised on go-live.",
             "Cash at 30 Sep 2026: £480k; monthly net burn about £70k."],
            "HMRC tax position and SEIS/EIS advance assurance",
            ["Corporation tax returns (CT600) for the years to January 2024 and 2025.",
             "HMRC EIS advance assurance letter for this round.",
             "VAT and PAYE account statements showing no arrears."],
            ["Founder IP assignment deeds dated February 2023.",
             "IP clauses in all employment contracts.",
             "UK trade mark HALYARD SECURITY application filed (class 9 and 42)."],
            ("Key customer contract summary: NHS trust (name withheld)",
             ["9,800 licensed users at £12 per user per year; three-year term.",
              "Bought through a public-sector framework call-off.",
              "Data processing agreement; no clinical data processed.",
              "Go-live support for six weeks included."]),
            ("Board minutes, Q3 2026",
             ["Approved the £3m seed round and EIS advance assurance application.",
              "Reviewed rollout at two new councils.",
              "Approved ISO 27001 project.",
              "Noted no successful phishing takeovers on enrolled accounts."]),
            ("Company KYB pack",
             ["Companies House confirmation statement and PSC register.",
              "Directors' passports and proof of address.",
              "Cyber Essentials Plus certificate."]),
            [("NHS Data Security and Protection Toolkit submission", "legal_ip", "ON_REQUEST",
              ["DSPT 2025-26 submission status: Standards Met.",
               "Supporting evidence index.",
               "Named Data Protection Officer."]),
             ("Phishing outcome reporting method", "financials", "ON_REQUEST",
              ["How takeover attempts against enrolled accounts are counted.",
               "Sources: customer security operations logs and identity provider sign-in records.",
               "Covers 64,000 enrolled accounts to 30 Sep 2026."])]),
        qGuide=["Calm, plain, and a bit dry. I have been in the room after an attack; no drama needed.",
                "'Zero successful phishing takeovers on enrolled accounts' is the claim. Do not stretch it to 'unhackable'.",
                "Never name a trust or council customer. Public bodies approve their own announcements.",
                "Do not discuss any specific incident I worked on at the cyber security centre.",
                "We work with Microsoft, Okta and others. Do not position us as replacing them.",
                "Do not say we stop ransomware. We remove the most common first step.",
                "Security details beyond the public overview go through the data room on request.",
                "If asked about the US or Europe, say the UK public sector is the focus for this round."],
        qPersonality="WITTY",
        gateqAnswers={"sector": "Cybersecurity / Public-sector SaaS: passkey rollout", "stage": "seed",
                      "geography": "Edinburgh, United Kingdom; UK public sector",
                      "chequeNeed": {"targetRaise": 3_000_000, "minimumCheque": 25_000, "currency": "GBP"},
                      "traction": "11 NHS trusts and councils; 64,000 staff enrolled; zero successful phishing takeovers on enrolled accounts",
                      "teamSize": 21})


# ---------------------------------------------------------------- 14 Hui
def c14():
    monthly, cum = cum_from_monthly(4_600, 19_500, 190_000)  # ₫ millions
    cum = [round(x / 1000, 1) for x in cum]
    monthly = [round(x / 1000, 1) for x in monthly]
    members = geo(14_000, 52_000)
    cap = capital(
        900_000, "USD", "SAFE (post-money)", "valuationCap", 7_000_000, "2026-12-23", 20_000,
        [("Engineering and security", 35), ("Growth in Ho Chi Minh City and Hanoi markets", 30),
         ("Partner bank integration and compliance", 20), ("Operations and support", 15)],
        rounds(("Angel", "2024-09-10", 150_000, "USD", "SAFE (post-money)", "Saigon product angels")),
        ["Saigon product angels", "Mekong Seed Circle"],
        140_000, 22_000, 42_000,
        extra={"holdingCompany": "Hui Holdings Pte. Ltd. (Singapore) issues the SAFE and owns the Vietnamese operating company."})
    return dict(
        legalName="Hui Technology Company Limited (Công ty TNHH Công nghệ Hụi)", websiteUrl="https://hui-app.example",
        foundedDate="2024-04-15", headquarters={"city": "Ho Chi Minh City", "country": "VN"}, currentStageCode="pre_seed",
        headcount=12,
        shortDescription="Hui runs Vietnam's traditional hụi savings groups in an app, with the pot held by a partner bank so nobody can run off with it.",
        primaryDescription=("Hui is a digital version of the hụi, the rotating savings group many Vietnamese market traders and informal workers already use. "
                            "Members contribute on a schedule and take turns receiving the pot, but the money is held by a partner bank instead of the group organiser's notebook. "
                            "52,000 members run more than 7,300 active groups, and members have saved ₫190bn through the app. "
                            "Hui earns a small fee per completed cycle and a share of the partner bank's interest."),
        tags={"industry": ["fintech"], "business_model": ["transaction_fee"],
              "customer_type": ["consumer"], "geography": ["vietnam", "asia"],
              "other": ["digital_banking", "financial_inclusion", "mobile_technology"]},
        keywords=["hụi", "rotating savings", "ROSCA", "Vietnam", "informal workers", "savings groups", "market traders",
                  "consumer fintech", "partner bank", "Ho Chi Minh City", "community savings", "mobile savings"],
        brand={"primary": "#D9467A", "accent": "#2BA37A", "ink": "#2B1420",
               "logoConcept": "A circle of ten dots with one dot lifted out"},
        founderPerson=dict(
            name="Minh Tran", role="Co-founder & CEO", appRole="OWNER", age=27, nationality="Vietnamese", gender="male",
            city="Ho Chi Minh City", education=["BSc Management Information Systems, University of Economics Ho Chi Minh City (2021)"],
            previousRoles=[{"title": "Associate Product Manager", "org": "Vietnamese e-wallet", "from": 2021, "to": 2022},
                           {"title": "Product Manager, savings and bill pay", "org": "Vietnamese e-wallet", "from": 2022, "to": 2024}],
            headline="Co-founder & CEO, Hui | Former e-wallet product manager | Making the hụi safe",
            professionalSummary="Product manager at a Vietnamese e-wallet for three years, working on savings and bill-pay features. Co-founded Hui in 2024.",
            backgroundSummary="His mother sold fruit at a Saigon market for twenty years and ran a hụi that paid for his schooling. He saw what happened when an organiser disappeared.",
            languages=["Vietnamese", "English"]),
        team=[person("Nguyễn Thu Hà", "Co-founder & CTO", "ADMIN", "Backend engineer from a Vietnamese bank's digital team. Built the bank-held pot and payout scheduling.", "Vietnamese", "female"),
              person("Lê Quốc Bảo", "Head of Partnerships", "MEMBER", "Former relationship manager at a commercial bank. Manages the partner bank relationship.", "Vietnamese", "male"),
              person("Phạm Ngọc Lan", "Community Lead", "MEMBER", "Grew up in Bình Tây market. Trains group organisers and runs the Zalo support community.", "Vietnamese", "female")],
        capital=cap,
        metrics=metrics([("members", "Members", "count", None),
                         ("active_groups", "Active groups", "count", None),
                         ("contributions_month_bn", "Contributions in month (₫ billions)", "money_billions", "VND"),
                         ("saved_cumulative_bn", "Saved through Hui, cumulative (₫ billions)", "money_billions", "VND")],
                        {"members": members, "active_groups": geo(1_900, 7_300), "contributions_month_bn": monthly,
                         "saved_cumulative_bn": cum},
                        "Average contribution in September 2026 about ₫375,000 per member per month."),
        deck=deck(
            problem=["Millions of Vietnamese informal workers save through a hụi: a group pays in each week and one member takes the pot.",
                     "It runs on trust and a notebook, and sometimes the person holding the notebook disappears."],
            solution=["Hui lets people run the same savings group in an app.",
                      "The money is held by a partner bank, so nobody can run off with it.",
                      "Schedules, reminders and payouts are automatic."],
            value_proposition=["Members keep the habit they trust, without the risk.",
                               "Organisers stop chasing payments and keeping notebooks.",
                               "The partner bank reaches savers it could not reach before."],
            market=["Method: estimated hụi participants × annual contributions.",
                    "TAM: an estimated 10 million adults in hụi groups, contributing about ₫4.5m a year each = ₫45 trillion (about $1.7bn) a year.",
                    "SAM: urban market traders and gig workers in Ho Chi Minh City and Hanoi, about 1.5 million people.",
                    "SOM: 400,000 members by 2028."],
            go_to_market=["Organisers bring their whole group; one organiser averages seven members.",
                          "Community lead trains organisers in markets, starting in Ho Chi Minh City.",
                          "Zalo community and referrals."],
            business_model=["We charge a small fee and share interest with the bank."],
            traction=["52,000 members.",
                      "More than 7,300 active groups.",
                      "₫190bn saved through Hui."],
            competition=["Paper hụi run by organisers: the real competitor.",
                         "E-wallet savings features: individual, not group-based.",
                         "Hui keeps the group and adds bank custody."],
            financials=["This round gives us about two years."],
            the_ask=["Raising $900k pre-seed on a post-money SAFE.",
                     "35% engineering and security, 30% growth, 20% bank integration and compliance, 15% operations."],
            founders=["Minh Tran, CEO: former e-wallet product manager; grew up with his mother's hụi.",
                      "Nguyễn Thu Hà, CTO: built core systems on a bank's digital team."],
            team=["12 people in Ho Chi Minh City: 6 engineering, 3 community and support, 2 partnerships, 1 operations.",
                  "Community Lead Phạm Ngọc Lan grew up in Bình Tây market and trains group organisers."]),
        deckGaps=[{"section": "business_model", "gap": "No fee level, no interest-share terms, no unit economics."},
                  {"section": "financials", "gap": "No revenue projection or burn; a runway claim only."}],
        dataRoom=standard_room(
            "Hui Technology Company Limited", "the Business Registration Office, Ho Chi Minh City",
            "Enterprise code 0318462751", "2024-04-15",
            [("Minh Tran", 48), ("Nguyễn Thu Hà", 32), ("Employee option pool", 10), ("Angels (as converted)", 10)],
            10, "Options granted at the Singapore holding company; four-year vesting with a one-year cliff.",
            ["Monthly management accounts in dong, consolidated with the Singapore holding company.",
             "Fee and interest-share revenue of ₫162m in September 2026.",
             "Member funds are held by the partner bank and are not on Hui's balance sheet.",
             "Cash at 30 Sep 2026: about $140,000 equivalent."],
            "Tax finalisation and tax authority confirmation",
            ["Corporate income tax finalisation (quyết toán thuế) for 2025.",
             "Confirmation from the tax department of no outstanding obligations, August 2026.",
             "VAT declarations for the last four quarters."],
            ["Founder IP assignment to the Singapore holding company covering app, brand and code.",
             "Intercompany licence from holding company to the Vietnamese operating company.",
             "Hui trade mark application filed with the Intellectual Property Office of Vietnam."],
            ("Key contract summary: partner bank custody and payout agreement",
             ["Partner bank holds each group's pot in segregated accounts.",
              "Payouts released only on the group's schedule; Hui cannot withdraw member funds.",
              "Interest share paid quarterly to Hui.",
              "Term of two years from March 2025."]),
            ("Board minutes, August 2026",
             ["Approved pre-seed raise of $900k on a post-money SAFE.",
              "Reviewed legal opinion on operating under Decree 19/2019/ND-CP on hụi.",
              "Approved Hanoi pilot with 300 groups.",
              "Noted fraud review: 14 accounts closed for identity mismatch."]),
            ("Founder and company KYC pack",
             ["Enterprise Registration Certificate and company seal registration.",
              "Founders' citizen identity cards.",
              "Singapore holding company ACRA business profile."]),
            [("Legal opinion on digital hụi", "legal_ip", "SHARED_ONLY",
              ["Vietnamese counsel's opinion on operating digital hụi under Decree 19/2019/ND-CP.",
               "Role of the partner bank in holding funds.",
               "Limits on interest and organiser fees."])]),
        qGuide=["Curious, earnest and simple. Explain hụi to people who have never heard of it.",
                "The key point: money is held by a partner bank, so nobody can run off with it.",
                "Never name members or organisers or share anything about their groups.",
                "Do not call Hui a bank or a lender. We are a savings group tool.",
                "Do not promise interest rates to members or returns to investors.",
                "Quote 52,000 members, over 7,300 groups and ₫190bn saved.",
                "Partner bank terms and the legal opinion are available on request only.",
                "If asked about fees, say they are small and offer to share the detail in a call.",
                "Speak respectfully about my mother's generation. They built this system."],
        qPersonality="WARM",
        gateqAnswers={"sector": "Fintech: consumer savings (digital rotating savings groups)", "stage": "pre_seed",
                      "geography": "Ho Chi Minh City, Vietnam",
                      "chequeNeed": {"targetRaise": 900_000, "minimumCheque": 20_000, "currency": "USD"},
                      "traction": "52,000 members; 7,300 active groups; ₫190bn saved",
                      "teamSize": 12})


# ---------------------------------------------------------------- 15 Cosecha Labs
def c15():
    ha = geo(4_800, 9_200)
    cap = capital(
        3_500_000, "USD", "SAFE (post-money)", "valuationCap", 18_000_000, "2027-01-08", 50_000,
        [("Sensor manufacturing and inventory", 30), ("Field agronomy team (Michoacán and Jalisco)", 30),
         ("Software and irrigation-valve integration", 25), ("Sales and G&A", 15)],
        rounds(("Pre-seed", "2023-03-29", 1_100_000, "USD", "SAFE (post-money)", "Bajío Agro Ventures")),
        ["Bajío Agro Ventures", "Three avocado packers as angels"],
        700_000, 75_000, 150_000)
    return dict(
        legalName="Cosecha Labs, S.A.P.I. de C.V.", websiteUrl="https://cosechalabs.example",
        foundedDate="2022-05-23", headquarters={"city": "Guadalajara", "region": "Jalisco", "country": "MX"}, currentStageCode="seed",
        headcount=29,
        shortDescription="Low-cost soil sensors that tell avocado growers when and how much to irrigate, block by block, on their phone.",
        primaryDescription=("Cosecha Labs puts low-cost soil-moisture sensors in avocado orchards and tells growers exactly when and how much to irrigate, block by block, on their phone. "
                            "Most growers irrigate on a fixed weekly schedule whatever the soil needs, while aquifers in Michoacán fall every year. "
                            "Across 9,200 hectares, Cosecha growers use about 31% less water and yields hold steady; 140 growers pay an annual per-hectare subscription. "
                            "The hardware is included in the subscription."),
        tags={"industry": ["agriculture"], "business_model": ["b2b_saas", "hardware_sales"],
              "customer_type": ["small_business", "business_customer"], "geography": ["mexico", "latin_america"],
              "other": ["agritech", "internet_of_things", "climate"]},
        keywords=["avocado", "precision irrigation", "soil moisture", "water efficiency", "Michoacán", "Jalisco",
                  "agtech", "IoT sensors", "aquifer", "Mexico agriculture", "irrigation scheduling", "orchards"],
        brand={"primary": "#6A8D2F", "accent": "#3FA7D6", "ink": "#1F2A12",
               "logoConcept": "An avocado half whose stone is a water drop"},
        founderPerson=dict(
            name="Santiago Ruiz", role="Co-founder & CEO", appRole="OWNER", age=32, nationality="Mexican", gender="male",
            city="Guadalajara", education=["Ingeniería Agronómica, Universidad Michoacana de San Nicolás de Hidalgo (2016)"],
            previousRoles=[{"title": "Field Agronomist", "org": "Avocado packer, Uruapan", "from": 2016, "to": 2018},
                           {"title": "Product Manager, IoT devices", "org": "Hardware startup, Guadalajara", "from": 2018, "to": 2022}],
            headline="Co-founder & CEO, Cosecha Labs | Agronomist from a Michoacán farming family | Farming smarter with less water",
            professionalSummary="Agronomist who worked for an avocado packer, then built IoT products at a Guadalajara hardware startup. Co-founded Cosecha to bring both together.",
            backgroundSummary="His family farms avocados in Michoacán. He has watched wells go deeper every year.",
            languages=["Spanish", "English"]),
        team=[person("Valeria Castañeda", "Co-founder & CTO", "ADMIN", "Embedded systems engineer; led firmware at the same Guadalajara hardware startup. Designed the sensor and its two-year battery life.", "Mexican", "female"),
              person("Diego Herrera", "Field Agronomy Lead", "MEMBER", "Agronomist with eight years advising orchards in Uruapan and Tancítaro. Trains growers and calibrates recommendations.", "Mexican", "male")],
        capital=cap,
        metrics=metrics([("hectares", "Hectares under management", "hectares", None),
                         ("paying_growers", "Paying growers", "count", None),
                         ("arr", "Annual recurring revenue", "money", "MXN"),
                         ("water_saved_pct", "Average water saved versus grower's prior schedule", "percent", None)],
                        {"hectares": ha, "paying_growers": [88, 93, 99, 106, 115, 123, 131, 140],
                         "arr": [h * 1850 for h in ha], "water_saved_pct": [27, 28, 29, 29, 30, 30, 31, 31]},
                        "ARR = hectares × MXN 1,850 per hectare per year, hardware included."),
        deck=deck(
            problem=["Avocados need a lot of water; something like a thousand litres for a single kilo, depending on who you ask.",
                     "In Michoacán, aquifers are dropping every year.",
                     "Most growers irrigate by habit, on the same weekly schedule, whether the soil needs it or not."],
            solution=["Low-cost moisture sensors placed in the orchard.",
                      "Growers get exactly when and how much to irrigate, block by block, on their phone.",
                      "Recommendations calibrated by field agronomists."],
            value_proposition=["About 31% less water with yields holding steady.",
                               "Lower pumping and electricity costs.",
                               "A record of water use that export buyers increasingly ask for."],
            market=["Avocado is a huge industry in Mexico and water is getting scarcer every year."],
            go_to_market=["Word of mouth among growers."],
            business_model=["Annual subscription of MXN 1,850 per hectare, sensors included.",
                            "About one sensor per four hectares; replaced every two years.",
                            "Gross margin 58% including hardware."],
            traction=["9,200 hectares under management.",
                      "140 growers paying every year.",
                      "About 31% less water; yields steady."],
            competition=["CropX: soil sensing and analytics, mostly larger farms in the US and Israel.",
                         "Netafim: drip systems with monitoring, sold with irrigation hardware.",
                         "Phytech and Hortau: plant and soil monitoring at higher price points.",
                         "Cosecha is priced for Mexican avocado growers and backed by local agronomists."],
            financials=["ARR target: MXN 32m end-2027, MXN 58m end-2028, MXN 95m end-2029.",
                        f"Net burn today about ${cap['monthlyNetBurn']['amount']:,} a month; about ${cap['plannedMonthlyNetBurnPostRaise']['amount']:,} after the raise.",
                        f"Runway after the raise about {cap['runwayMonthsPostRaise']:.0f} months."],
            the_ask=["Raising a $3.5m seed on a post-money SAFE.",
                     "30% sensors, 30% field agronomy, 25% software and valve integration, 15% sales and G&A."],
            founders=["Santiago Ruiz, CEO: agronomist from a Michoacán farming family; built IoT products in Guadalajara.",
                      "Valeria Castañeda, CTO: embedded systems engineer; designed the sensor."],
            team=["29 people: 9 engineering, 12 field agronomy and installation, 4 sales, 4 operations.",
                  "Field Agronomy Lead Diego Herrera has eight years advising orchards in Uruapan and Tancítaro."]),
        deckGaps=[{"section": "market", "gap": "No TAM/SAM/SOM numbers or method."},
                  {"section": "go_to_market", "gap": "One line; no channel, cost of acquisition or expansion plan."}],
        dataRoom=standard_room(
            "Cosecha Labs, S.A.P.I. de C.V.", "the Registro Público de Comercio, Guadalajara (Jalisco)", "Folio mercantil electrónico N-2022041873", "2022-05-23",
            [("Santiago Ruiz", 40), ("Valeria Castañeda", 30), ("Employee option pool", 10), ("Bajío Agro Ventures (as converted)", 15),
             ("Packer angels (as converted)", 5)],
            10, "Four-year vesting with a one-year cliff.",
            ["Monthly management accounts in pesos.",
             "ARR rose from MXN 8.9m in Oct 2025 to MXN 17.0m in Sep 2026.",
             "Sensor inventory and installed base capitalised over two years.",
             "Cash at 30 Sep 2026: about $700,000 equivalent."],
            "SAT compliance opinion (Opinión de cumplimiento, 32-D)",
            ["Positive opinion of compliance with tax obligations issued by the SAT, September 2026.",
             "Annual tax returns for 2023, 2024 and 2025.",
             "IMSS and INFONAVIT compliance opinions."],
            ["Founder IP assignment covering sensor design, firmware and recommendation models.",
             "Utility model application filed with IMPI on the sensor housing.",
             "Cosecha Labs trade mark registered with IMPI."],
            ("Key customer contract summary: Michoacán grower cooperative (name withheld)",
             ["1,240 hectares across 31 member growers.",
              "Annual subscription at MXN 1,850 per hectare; renewed for 2026-27.",
              "Cosecha installs and replaces sensors; cooperative provides field access.",
              "Data belongs to each grower."]),
            ("Board minutes, Q3 2026",
             ["Approved $3.5m seed on a post-money SAFE.",
              "Reviewed water-saving results for the 2025-26 season.",
              "Approved pilot of automatic valve control with 12 growers.",
              "Noted sensor failure rate of 3.1% a year."]),
            ("Company KYB pack",
             ["Acta constitutiva and latest shareholder meeting minutes.",
              "RFC registration and proof of address.",
              "Legal representative's ID and power of attorney."]),
            [("Water and yield study, 2025-26 season", "financials", "ON_REQUEST",
              ["Compares 96 growers' water use with their own prior two seasons.",
               "Average reduction 31%; yields within 2% of prior seasons.",
               "Method for metering water at the pump."])]),
        qGuide=["Grounded and friendly. Talk like you are standing in an orchard.",
                "Say 'about 31% less water' and that yields held steady. Do not claim yield increases.",
                "The thousand-litres-per-kilo figure is an estimate that varies by source. Say so.",
                "Do not name growers or cooperatives without their permission.",
                "Water politics in Michoacán are sensitive. Stay factual and do not blame growers.",
                "We do not sell water rights or credits.",
                "Share the market model on request; I am still refining it.",
                "Spanish-speaking investors can be answered in Spanish."],
        qPersonality="WARM",
        gateqAnswers={"sector": "Agriculture / Climate: precision irrigation for avocado growers", "stage": "seed",
                      "geography": "Guadalajara, Mexico; orchards in Michoacán and Jalisco",
                      "chequeNeed": {"targetRaise": 3_500_000, "minimumCheque": 50_000, "currency": "USD"},
                      "traction": "9,200 hectares under management; 31% water saved; 140 paying growers",
                      "teamSize": 29})


COMPANIES = [c11, c12, c13, c14, c15]
