from common import *
from c01_05 import deck


# ---------------------------------------------------------------- 16 Mizan
def c16():
    monthly, cum = cum_from_monthly(28, 82, 640)  # EGP millions
    cap = capital(
        4_000_000, "USD", "Priced equity", "preMoneyValuation", 16_000_000, "2027-02-05", 100_000,
        [("Launch in Morocco and Saudi Arabia", 40), ("Engineering: API, structuring engine and repayments", 25),
         ("New bank and fintech partners in Egypt", 20), ("Shariah governance, compliance and licensing", 15)],
        rounds(("Pre-seed", "2023-07-19", 750_000, "USD", "SAFE (post-money)", "Zamalek Angels")),
        ["Zamalek Angels", "Nile Delta Ventures", "Two Gulf family-office angels"],
        600_000, 60_000, 160_000)
    return dict(
        legalName="Mizan Financial Technologies S.A.E.", websiteUrl="https://mizan-finance.example",
        foundedDate="2023-02-20", headquarters={"city": "Cairo", "country": "EG"}, currentStageCode="seed",
        headcount=24,
        shortDescription="An API that lets Egyptian banks and fintechs offer Shariah-compliant SME financing: structuring, Shariah review, documents and repayments.",
        primaryDescription=("Mizan is infrastructure for Shariah-compliant small-business financing. Banks and fintechs connect to its API, and Mizan handles contract structuring, the Shariah review workflow, documentation and repayment collection. "
                            "Many Egyptian business owners will not take a conventional loan for reasons of faith; Mizan lets lenders offer products they can say yes to. "
                            "Three banks are live, EGP 640m has been originated, and the non-performing rate is 0.9%. "
                            "Mizan charges a fee per financing and is raising to launch in Morocco and Saudi Arabia."),
        tags={"industry": ["fintech"], "business_model": ["transaction_fee", "usage_based"],
              "customer_type": ["financial_institution", "small_business"], "geography": ["egypt", "north_africa", "africa", "middle_east"],
              "other": ["lending_platform", "developer_api", "embedded_finance", "regulated_financial_services"]},
        keywords=["Islamic finance", "Shariah-compliant", "SME financing", "murabaha", "ijara", "lending API",
                  "Egypt", "banking infrastructure", "embedded lending", "Cairo", "Morocco", "Saudi Arabia"],
        brand={"primary": "#7A1F2B", "accent": "#D8B26E", "ink": "#2A0F14",
               "logoConcept": "A level balance beam with two equal pans"},
        founderPerson=dict(
            name="Youssef Kamal", role="Co-founder & CEO", appRole="OWNER", age=34, nationality="Egyptian", gender="male",
            city="Cairo", education=["BSc Economics, Cairo University (2013)", "MBA, The American University in Cairo (2019)"],
            previousRoles=[{"title": "SME Credit Analyst", "org": "Egyptian bank", "from": 2014, "to": 2017},
                           {"title": "Product Manager, SME Banking", "org": "Egyptian bank", "from": 2017, "to": 2020},
                           {"title": "Product Lead, SME Division", "org": "Egyptian bank", "from": 2020, "to": 2023}],
            headline="Co-founder & CEO, Mizan | Former SME product lead | Financing small businesses can say yes to",
            professionalSummary="Nine years in an Egyptian bank's SME division, ending as product lead, where he designed the bank's first digital murabaha product. Co-founded Mizan to give every lender that capability.",
            backgroundSummary="Grew up in Shubra; his father ran a printing shop that never borrowed because the only loans on offer were conventional.",
            languages=["Arabic", "English", "French (basic)"]),
        team=[person("Nour El-Sayed", "Co-founder & CTO", "ADMIN", "Engineer from a regional payments processor. Built the structuring engine and bank connectors.", "Egyptian", "female"),
              person("Omar Farouk", "Head of Bank Partnerships", "MEMBER", "Former corporate banker. Manages the three live banks and the pipeline in Morocco and Saudi Arabia.", "Egyptian", "male"),
              person("Mariam Hassan", "Head of Compliance and Shariah Governance", "MEMBER", "Lawyer specialising in Islamic finance. Coordinates the external Shariah board's reviews.", "Egyptian", "female")],
        capital=cap,
        metrics=metrics([("bank_partners_live", "Bank partners live", "count", None),
                         ("originated_month_egp_m", "Originated in month (EGP millions)", "money_millions", "EGP"),
                         ("originated_cumulative_egp_m", "Originated, cumulative (EGP millions)", "money_millions", "EGP"),
                         ("npl_pct", "Non-performing rate (90+ days)", "percent", None),
                         ("fee_revenue_month", "Fee revenue in month", "money", "EGP")],
                        {"bank_partners_live": [1, 1, 2, 2, 2, 3, 3, 3], "originated_month_egp_m": monthly,
                         "originated_cumulative_egp_m": cum, "npl_pct": [0.6, 0.7, 0.8, 0.8, 0.9, 0.9, 0.9, 0.9],
                         "fee_revenue_month": [round(m * 1_000_000 * 0.014) for m in monthly]},
                        "Fee of 1.4% of each financing, paid by the lender. Average financing about EGP 380,000. Financing sits on partner banks' balance sheets, not Mizan's."),
        deck=deck(
            problem=["Many Egyptian small-business owners will not take a conventional loan because it conflicts with their faith.",
                     "Banks want to offer Islamic SME financing, but building those products is slow and expensive, and every contract must be structured correctly."],
            solution=["Banks and fintechs plug into Mizan's API.",
                      "Mizan handles structuring (murabaha, ijara), the Shariah review workflow, documentation and repayments.",
                      "Lenders keep the credit decision and the balance sheet."],
            value_proposition=["Lenders launch Islamic SME products in weeks instead of years.",
                               "Every contract follows templates approved by an external Shariah board.",
                               "Business owners get financing they can say yes to."],
            market=["Method: SME financing volume that could be Shariah-compliant × Mizan's 1.4% fee.",
                    "TAM: about $40bn a year of SME financing across Egypt, Morocco and Saudi Arabia × 1.4% = $560m in fees.",
                    "SAM: Egyptian bank and fintech SME financing, about EGP 180bn a year × 1.4% = EGP 2.5bn.",
                    "SOM: EGP 6bn originated a year by 2029 = EGP 84m in fees."],
            go_to_market=["Direct partnerships with banks' SME divisions; founder's network from nine years in SME banking.",
                          "Fintech lenders and B2B marketplaces add Islamic financing through the API.",
                          "Morocco (participative banks) and Saudi Arabia next."],
            business_model=["1.4% of each financing, paid by the lender.",
                            "Set-up fee per new product launched with a partner.",
                            "Gross margin 80%."],
            traction=["3 bank partners live.",
                      "EGP 640m originated.",
                      "0.9% non-performing rate."],
            competition=["In-house bank builds: slow and expensive for each new product.",
                         "Temenos Islamic Banking and Path Solutions iMAL: core banking systems, not SME origination workflows.",
                         "Conventional SME lending fintechs: fast, but not Shariah-compliant.",
                         "Mizan is product infrastructure that sits on top of any core banking system."],
            financials=["Fee revenue: EGP 19m in 2027, EGP 46m in 2028, EGP 84m in 2029, plus Morocco and Saudi Arabia from 2028.",
                        f"Net burn today about ${cap['monthlyNetBurn']['amount']:,} a month; about ${cap['plannedMonthlyNetBurnPostRaise']['amount']:,} after the raise.",
                        f"Runway after the raise about {cap['runwayMonthsPostRaise']:.0f} months."],
            the_ask=["Raising a $4m seed (priced) to launch in Morocco and Saudi Arabia.",
                     "40% new markets, 25% engineering, 20% Egyptian partners, 15% Shariah governance and compliance."],
            founders=["Youssef Kamal, CEO: designed an Egyptian bank's first digital murabaha product.",
                      "Nour El-Sayed, CTO: built payment processing systems at a regional processor."],
            team=["24 people in Cairo: 11 engineering, 5 partnerships and operations, 4 compliance, 4 G&A.",
                  "External Shariah board of three scholars."]),
        deckGaps=[],
        dataRoom=standard_room(
            "Mizan Financial Technologies S.A.E.", "the Commercial Registry, Cairo (via GAFI)", "Commercial registration no. 184527", "2023-02-20",
            [("Youssef Kamal", 42), ("Nour El-Sayed", 26), ("Zamalek Angels (as converted)", 12), ("Employee option pool", 10),
             ("Nile Delta Ventures", 6), ("Gulf angels", 4)],
            10, "Four-year vesting with a one-year cliff.",
            ["Monthly management accounts in Egyptian pounds.",
             "Fee revenue rose from EGP 392k in Oct 2025 to EGP 1.15m in Sep 2026.",
             "Financings sit on partner banks' balance sheets; Mizan carries no credit risk.",
             "Cash at 30 Sep 2026: about $600,000 equivalent."],
            "Tax card and tax status certificate",
            ["Tax card issued by the Egyptian Tax Authority.",
             "Certificate of tax status showing no arrears, August 2026.",
             "VAT registration and monthly returns."],
            ["Founder IP assignment covering the structuring engine, API and templates.",
             "Contract templates owned by Mizan; Shariah board opinions licensed to partners.",
             "Mizan trade mark filed with the Egyptian Trademarks Office."],
            ("Key customer contract summary: Egyptian bank partner (name withheld)",
             ["Platform agreement for murabaha and ijara SME financing.",
              "Fee of 1.4% per financing; three-year term from June 2024.",
              "Bank makes every credit decision; Mizan provides workflow and documents.",
              "Data hosted in Egypt in line with Central Bank of Egypt rules."]),
            ("Board minutes, September 2026",
             ["Approved the $4m seed at a $16m pre-money valuation.",
              "Reviewed Morocco market entry and two participative bank conversations.",
              "Reviewed Saudi licensing options.",
              "Noted non-performing rate stable at 0.9%."]),
            ("Founder and company KYC pack",
             ["Commercial registry extract and articles of association.",
              "Directors' national IDs.",
              "Beneficial ownership declaration."]),
            [("Shariah board opinions and review process", "legal_ip", "ON_REQUEST",
              ["Fatwas from the external Shariah board approving murabaha and ijara templates.",
               "Workflow for case-by-case review of non-standard contracts.",
               "Annual Shariah audit report."]),
             ("Portfolio performance report", "financials", "SHARED_ONLY",
              ["Originations, repayments and non-performing rate by partner and month.",
               "Average financing about EGP 380,000; average tenor 14 months.",
               "Sector mix of financed businesses."])]),
        qGuide=["Articulate and respectful. Faith is the reason our customers choose us; treat it seriously.",
                "Do not issue or paraphrase religious rulings. Refer to our external Shariah board's opinions.",
                "Mizan does not lend. Banks lend; we provide the infrastructure.",
                "Use exact figures: three banks live, EGP 640m originated, non-performing rate under 1%.",
                "Never name partner banks without their approval.",
                "For Morocco and Saudi Arabia, say we are preparing to launch; we have no live partners there yet.",
                "Give dollar figures only with the exchange rate used.",
                "Route any regulatory question to me or Mariam."],
        qPersonality="FORMAL",
        gateqAnswers={"sector": "Fintech: Shariah-compliant SME financing infrastructure (B2B API)", "stage": "seed",
                      "geography": "Cairo, Egypt; launching in Morocco and Saudi Arabia",
                      "chequeNeed": {"targetRaise": 4_000_000, "minimumCheque": 100_000, "currency": "USD"},
                      "traction": "3 bank partners live; EGP 640m originated; 0.9% non-performing",
                      "teamSize": 24})


# ---------------------------------------------------------------- 17 Rand Treasury
def c17():
    corps = geo(104, 160)
    cap = capital(
        8_000_000, "USD", "Priced equity (Series A preferred)", "preMoneyValuation", 32_000_000, "2027-01-29", 250_000,
        [("Product: multi-bank execution and cash-flow forecasting", 35), ("Sales and treasury advisory in Johannesburg, Durban and Cape Town", 35),
         ("Kenya pilot with mid-market importers", 15), ("Compliance (FSCA licence scope) and G&A", 15)],
        rounds(("Seed", "2021-10-04", 18_000_000, "ZAR", "Priced equity", "Table Bay Capital"),
               ("Seed extension", "2023-05-15", 2_000_000, "USD", "Priced equity", "Fynbos Growth Fund")),
        ["Table Bay Capital", "Fynbos Growth Fund", "Former bank treasury executives as angels"],
        2_600_000, 180_000, 400_000)
    return dict(
        legalName="Rand Treasury (Pty) Ltd", websiteUrl="https://randtreasury.example",
        foundedDate="2021-04-12", headquarters={"city": "Cape Town", "country": "ZA"}, currentStageCode="series_a",
        headcount=48,
        shortDescription="Treasury software for South African mid-market companies: see FX exposures automatically, set a hedging policy, execute with any bank.",
        primaryDescription=("Rand Treasury gives South African mid-market companies the FX risk tools large corporates have. "
                            "It connects to the accounting system, identifies currency exposures automatically, recommends a hedging policy, and lets the company execute with any bank. "
                            "160 companies use it, with R14bn of exposure under management and R48m in annual recurring revenue. "
                            "Revenue is a subscription plus an execution fee."),
        tags={"industry": ["fintech", "enterprise_software"], "business_model": ["b2b_saas", "transaction_fee"],
              "customer_type": ["mid_market", "business_customer"], "geography": ["south_africa", "southern_africa", "africa"],
              "other": ["capital_markets", "regulated_financial_services", "data_analytics_platform"]},
        keywords=["FX risk", "currency hedging", "treasury management", "rand", "mid-market", "South Africa",
                  "forward contracts", "exposure management", "CFO tools", "Cape Town", "multi-bank", "importers"],
        brand={"primary": "#3D348B", "accent": "#F7B801", "ink": "#17153B",
               "logoConcept": "A capital R whose leg is a hedged, flattened curve"},
        founderPerson=dict(
            name="Elize van der Merwe", role="Co-founder & CEO", appRole="OWNER", age=49, nationality="South African", gender="female",
            city="Cape Town", education=["BCom Accounting, Stellenbosch University (1998)", "BCom Honours (CTA), Stellenbosch University (1999)", "CA(SA), SAICA (2002)"],
            previousRoles=[{"title": "Audit trainee to Audit Manager", "org": "Audit firm, Cape Town", "from": 1999, "to": 2005},
                           {"title": "Corporate FX Dealer", "org": "South African bank", "from": 2005, "to": 2010},
                           {"title": "Head of Corporate FX Sales, Western Cape", "org": "South African bank", "from": 2010, "to": 2020}],
            headline="Co-founder & CEO, Rand Treasury | CA(SA) | 15 years selling FX hedging to South African companies",
            professionalSummary="Chartered accountant who spent fifteen years in corporate FX at a South African bank, the last ten as head of corporate FX sales. Saw most mid-sized clients either unprotected or overpaying.",
            backgroundSummary="Grew up in Paarl. Left the bank in 2020 to build the tools she had wanted to give her mid-market clients.",
            languages=["Afrikaans", "English"]),
        team=[person("Sipho Ndlovu", "Co-founder & CTO", "ADMIN", "Built trading and risk systems at a Johannesburg asset manager. Leads accounting integrations and the exposure engine.", "South African", "male"),
              person("Ayesha Patel", "Head of Treasury Advisory", "MEMBER", "Former corporate treasurer at a listed manufacturer. Leads the advisory team that sets client hedging policies.", "South African", "female"),
              person("Pieter Botha", "Head of Sales", "MEMBER", "Twelve years in business banking in Gauteng. Runs sales in Johannesburg and Durban.", "South African", "male")],
        capital=cap,
        metrics=metrics([("arr", "Annual recurring revenue (subscriptions)", "money", "ZAR"),
                         ("corporates", "Corporate clients", "count", None),
                         ("hedged_exposure_bn", "Exposure under management (R billions)", "money_billions", "ZAR"),
                         ("execution_fees_month", "Execution fee revenue in month", "money", "ZAR")],
                        {"arr": [c * 300_000 for c in corps], "corporates": corps,
                         "hedged_exposure_bn": geo(8.2, 14.0, 1), "execution_fees_month": geo(320_000, 550_000)},
                        "ARR counts subscriptions only (average R300,000 per client a year); execution fees are reported separately and are not recurring."),
        deck=deck(
            problem=["The rand can move ten percent in a month.",
                     "Large companies have treasury teams; a mid-sized manufacturer importing machinery has a financial director and a phone call to the bank.",
                     "Most such companies are either unprotected or overpaying for hedges."],
            solution=["Rand Treasury connects to the accounting system and finds exposures automatically.",
                      "It recommends a hedging policy the board can approve.",
                      "Companies execute with any bank, with pricing compared side by side."],
            value_proposition=["Fewer currency surprises in the results.",
                               "Lower hedging cost through bank competition.",
                               "A documented policy for auditors and boards."],
            market=["Method: South African companies with material FX exposure × average subscription.",
                    "TAM: about 6,000 companies with R100m-R2bn revenue and FX exposure × R300,000 = R1.8bn a year.",
                    "SAM: about 2,800 importers and exporters with regular foreign-currency flows = R840m.",
                    "SOM: 650 clients by 2029 = R195m ARR."],
            go_to_market=["Direct sales to financial directors, supported by the advisory team.",
                          "Referrals from audit firms and accounting-software partners.",
                          "Industry associations of importers and manufacturers."],
            business_model=["Subscription averaging R300,000 a year, priced by exposure band.",
                            "Execution fee on trades placed through the platform.",
                            "Gross margin 79%."],
            traction=["160 corporates.",
                      "R14bn of exposure under management.",
                      "R48m ARR."],
            competition=["Kyriba: global treasury suite built for large corporates.",
                         "Bound: FX risk software for SMEs, focused on the UK and Europe.",
                         "Bank FX portals: one bank's pricing, no policy support.",
                         "Rand Treasury is bank-neutral and built for the South African mid-market."],
            financials=["ARR target: R82m end-2027, R130m end-2028, R195m end-2029.",
                        f"Net burn today about ${cap['monthlyNetBurn']['amount']:,} a month; about ${cap['plannedMonthlyNetBurnPostRaise']['amount']:,} after the raise.",
                        f"Runway after the raise about {cap['runwayMonthsPostRaise']:.0f} months; break-even planned for 2028."],
            the_ask=["Raising an $8m Series A (priced).",
                     "35% product, 35% sales and advisory, 15% Kenya pilot, 15% compliance and G&A."],
            founders=["Elize van der Merwe, CEO: CA(SA); 15 years in corporate FX at a South African bank.",
                      "Sipho Ndlovu, CTO: built trading and risk systems at a Johannesburg asset manager."],
            team=["48 people in Cape Town and Johannesburg: 18 engineering, 10 treasury advisory, 12 sales, 8 G&A.",
                  "Advisory team led by Ayesha Patel, a former corporate treasurer at a listed manufacturer."]),
        deckGaps=[],
        dataRoom=standard_room(
            "Rand Treasury (Pty) Ltd", "the Companies and Intellectual Property Commission (CIPC)", "Registration no. 2021/412785/07", "2021-04-12",
            [("Elize van der Merwe", 34), ("Sipho Ndlovu", 20), ("Table Bay Capital", 18), ("Fynbos Growth Fund", 12),
             ("Employee share scheme", 11), ("Angels", 5)],
            11, "Share appreciation rights scheme, four-year vesting with a one-year cliff.",
            ["Monthly management accounts in rand under IFRS for SMEs.",
             "Subscription ARR grew from R31.2m in Oct 2025 to R48.0m in Sep 2026.",
             "Execution fees of about R5.1m over the last 12 months, reported separately.",
             "Cash at 30 Sep 2026: about $2.6m equivalent."],
            "SARS Tax Compliance Status PIN",
            ["SARS Tax Compliance Status: compliant, PIN valid to May 2027.",
             "Income tax returns (ITR14) for 2023, 2024 and 2025.",
             "VAT201 and EMP201 submissions for the last 12 months."],
            ["Founder IP assignments covering exposure engine, integrations and brand.",
             "IP clauses in all employment contracts.",
             "Rand Treasury trade mark registered with CIPC (class 36 and 42)."],
            ("Key customer contract summary: Western Cape manufacturer (name withheld)",
             ["Subscription of R420,000 a year; three-year term.",
              "Exposure of about R380m a year in euro and US dollar machinery and inputs.",
              "Hedging policy approved by the client's board in 2025.",
              "Execution through three banks via the platform."]),
            ("Board minutes, Q3 2026",
             ["Approved Series A process and data room.",
              "Reviewed FSCA licence scope for advice on derivatives.",
              "Approved Kenya pilot budget.",
              "Noted two clients lost after acquisition by groups with in-house treasury."]),
            ("Company KYB pack",
             ["CIPC registration certificate (CoR14.3) and memorandum of incorporation.",
              "Directors' IDs and proof of address.",
              "FSCA financial services provider licence, FSP 51327."]),
            [("FSCA licence and compliance officer reports", "legal_ip", "ON_REQUEST",
              ["Financial services provider licence covering advice on derivatives and forex.",
               "Annual compliance officer reports for 2024 and 2025.",
               "Conflict-of-interest policy, including how execution fees are disclosed."]),
             ("Client cohort and retention analysis", "financials", "SHARED_ONLY",
              ["Client cohorts since 2021.",
               "Gross revenue retention 93%; net revenue retention 116%.",
               "Churn reasons by client."])]),
        qGuide=["Crisp and commercial. I sold FX for fifteen years; speak to financial directors in their language.",
                "R48m is subscription ARR. Execution fees are separate. Never add them together as recurring revenue.",
                "R14bn is exposure under management, not assets under management.",
                "Never give hedging advice to anyone through Q. Advice is provided by our licensed advisory team.",
                "Do not name clients or banks.",
                "Give dollar figures only with the exchange rate used.",
                "Be honest about competition from bank portals. Banks are also our execution partners.",
                "If asked about the Kenya pilot, say it is a pilot and not yet live."],
        qPersonality="DIRECT",
        gateqAnswers={"sector": "Fintech / Enterprise software: FX risk and treasury for mid-market companies", "stage": "series_a",
                      "geography": "Cape Town, South Africa; clients across South Africa",
                      "chequeNeed": {"targetRaise": 8_000_000, "minimumCheque": 250_000, "currency": "USD"},
                      "traction": "R48m ARR; 160 corporates; R14bn in hedged exposure",
                      "teamSize": 48})


# ---------------------------------------------------------------- 18 Orphéa Genomics
def c18():
    monthly, cum = cum_from_monthly(70, 150, 2300)
    cap = capital(
        6_000_000, "EUR", "Priced equity", "preMoneyValuation", 22_000_000, "2027-03-19", 100_000,
        [("Engineering and variant interpretation", 30), ("Hospital expansion in France, Belgium and Switzerland", 30),
         ("IVDR certification (CE-IVD) and quality system", 25), ("Clinical studies", 15)],
        rounds(("Pre-seed", "2022-07-11", 1_500_000, "EUR", "Priced equity", "Fonds Lutèce Santé"),
               ("Grant", "2023-11-20", 450_000, "EUR", "Innovation grant (non-dilutive)", "Regional innovation programme, Île-de-France")),
        ["Fonds Lutèce Santé", "Clinician angels from Paris university hospitals"],
        1_400_000, 180_000, 280_000)
    return dict(
        legalName="Orphéa Genomics SAS", websiteUrl="https://orphea-genomics.example",
        foundedDate="2022-03-08", headquarters={"city": "Paris", "country": "FR"}, currentStageCode="seed",
        headcount=23,
        shortDescription="Software that ranks the genomic variants most likely to explain a child's rare disease, with evidence, for hospital geneticists.",
        primaryDescription=("Orphéa Genomics helps hospital genetics teams diagnose rare diseases in children faster. "
                            "Its software does the heavy part of whole-genome analysis, ranking the variants most likely to explain a child's symptoms and showing the evidence for each. "
                            "Nine university hospitals use it; it has analysed 2,300 cases with a diagnostic yield of 41%, against about 25% before. "
                            "Hospital genetics departments pay a fee per case."),
        tags={"industry": ["healthcare"], "business_model": ["transaction_fee", "b2b_saas"],
              "customer_type": ["enterprise", "government"], "geography": ["france", "europe"],
              "other": ["digital_health", "machine_learning", "regulated_healthcare", "health_access"]},
        keywords=["rare disease", "genomics", "whole-genome sequencing", "variant interpretation", "paediatrics",
                  "clinical genetics", "diagnostic yield", "bioinformatics", "Paris", "university hospitals", "precision medicine", "diagnosis"],
        brand={"primary": "#3E5C76", "accent": "#F0A6CA", "ink": "#1D2D44",
               "logoConcept": "A small open lyre whose strings are a DNA ladder"},
        founderPerson=dict(
            name="Camille Laurent", role="Co-founder & CEO", appRole="OWNER", age=36, nationality="French", gender="female",
            city="Paris", education=["MD, Université Paris Cité (2016)", "DES in Medical Genetics (2020)", "PhD in Bioinformatics, Sorbonne Université (2021)"],
            previousRoles=[{"title": "Resident (interne) in Medical Genetics", "org": "Paris university hospitals", "from": 2016, "to": 2020},
                           {"title": "Doctoral researcher in bioinformatics (alongside residency)", "org": "Sorbonne Université", "from": 2017, "to": 2021},
                           {"title": "Clinical Geneticist (part-time since 2022)", "org": "Paris children's hospital", "from": 2020, "to": None}],
            headline="Co-founder & CEO, Orphéa Genomics | Clinical geneticist, PhD bioinformatics | An answer changes everything",
            professionalSummary="Clinical geneticist at a Paris children's hospital with a PhD in bioinformatics. Still holds a part-time clinical post alongside running Orphéa.",
            backgroundSummary="Has sat with many families during the average five-year search for a diagnosis. Started Orphéa when her PhD tools began finding answers her department had missed.",
            languages=["French", "English", "Spanish"]),
        team=[person("Dr Julien Moreau", "Co-founder & CTO", "ADMIN", "Computational biologist; built genome pipelines at a national sequencing centre. Leads the variant ranking engine.", "French", "male"),
              person("Inès Benali", "Head of Clinical Partnerships", "MEMBER", "Former genetic counsellor. Onboards hospital teams and runs the clinical feedback loop.", "French", "female"),
              person("Thomas Lefebvre", "Head of Quality and Regulatory", "MEMBER", "Led ISO 13485 quality systems at a diagnostics company. Owns the IVDR certification project.", "French", "male")],
        capital=cap,
        metrics=metrics([("university_hospitals", "University hospitals using Orphéa", "count", None),
                         ("cases_month", "Cases analysed in month", "count", None),
                         ("cases_cumulative", "Cases analysed, cumulative", "count", None),
                         ("diagnostic_yield_pct", "Diagnostic yield, cumulative", "percent", None),
                         ("revenue_month", "Revenue in month", "money", "EUR")],
                        {"university_hospitals": [5, 6, 6, 7, 7, 8, 8, 9], "cases_month": monthly, "cases_cumulative": cum,
                         "diagnostic_yield_pct": [38, 39, 39, 40, 40, 41, 41, 41], "revenue_month": [m * 480 for m in monthly]},
                        "Baseline diagnostic yield of about 25% is the partner hospitals' rate on comparable cases before Orphéa. Average fee €480 per case."),
        deck=deck(
            problem=["Families of children with a rare disease wait around five years for a diagnosis.",
                     "The answer is often in the child's genome, but finding it means sifting millions of variants.",
                     "Most hospitals do not have enough geneticists to do it."],
            solution=["Software that does the heavy part of the analysis.",
                      "It ranks the variants most likely to explain the child's symptoms.",
                      "It shows the evidence for each, so the geneticist decides."],
            value_proposition=["Diagnostic yield of 41% versus about 25% before.",
                               "Less time per case for scarce geneticists.",
                               "Evidence trail for every reported variant."],
            market=["Method: rare-disease genome cases per year × per-case fee.",
                    "TAM: about 1.2 million rare-disease genome and exome cases a year worldwide × €480 = €576m.",
                    "SAM: France, Belgium and Switzerland, about 40,000 cases a year = €19.2m.",
                    "SOM: 12,000 cases a year by 2029 = €5.8m."],
            go_to_market=["Direct to university hospital genetics departments, led by clinicians.",
                          "Inclusion in public genomic medicine sequencing pathways.",
                          "Belgian and Swiss university hospitals next, then wider Europe after CE-IVD."],
            business_model=["Fee per case analysed, averaging €480.",
                            "Annual platform fee for hospitals above 500 cases a year.",
                            "Gross margin 85%."],
            traction=["9 university hospitals.",
                      "2,300 cases analysed.",
                      "Diagnostic yield 41% versus 25% baseline."],
            competition=["Fabric Genomics and Emedgene (Illumina): AI-assisted interpretation, US-centred.",
                         "Franklin by Genoox: interpretation platform with a large community.",
                         "Exomiser: open-source variant prioritisation used in many academic labs.",
                         "Orphéa is built with French clinicians and designed for EU data and regulation."],
            financials=["Revenue: €1.6m in 2027, €3.4m in 2028, €5.8m in 2029.",
                        f"Net burn today about €{cap['monthlyNetBurn']['amount']:,} a month; about €{cap['plannedMonthlyNetBurnPostRaise']['amount']:,} after the raise.",
                        f"Runway after the raise about {cap['runwayMonthsPostRaise']:.0f} months."],
            the_ask=["Raising a €6m seed (priced).",
                     "30% engineering, 30% hospital expansion, 25% IVDR certification, 15% clinical studies."],
            founders=["Dr Camille Laurent, CEO: clinical geneticist at a Paris children's hospital; PhD in bioinformatics.",
                      "Dr Julien Moreau, CTO: built genome pipelines at a national sequencing centre."],
            team=["23 people in Paris: 12 engineering and bioinformatics, 4 clinical, 3 quality and regulatory, 4 G&A.",
                  "Quality lead Thomas Lefebvre has run ISO 13485 quality systems at a diagnostics company."]),
        deckGaps=[],
        dataRoom=standard_room(
            "Orphéa Genomics SAS", "the Registre du Commerce et des Sociétés (RCS) de Paris", "SIREN 912 457 683", "2022-03-08",
            [("Camille Laurent", 36), ("Julien Moreau", 26), ("Fonds Lutèce Santé", 20), ("Employee option pool (BSPCE)", 12),
             ("Clinician angels", 6)],
            12, "BSPCE warrants, four-year vesting with a one-year cliff.",
            ["Monthly management accounts in euros (French GAAP).",
             "Revenue rose from €33.6k in Oct 2025 to €72.0k in Sep 2026.",
             "Research tax credit (CIR) receivable shown separately.",
             "Cash at 30 Sep 2026: €1.4m; monthly net burn about €180k."],
            "Attestation de régularité fiscale and URSSAF certificate",
            ["Certificate of tax compliance from the tax administration, August 2026.",
             "URSSAF certificate of social contribution compliance.",
             "Corporate tax returns for 2023, 2024 and 2025."],
            ["Founder IP assignments covering ranking engine and models.",
             "University agreement assigning PhD-derived software to Orphéa against a royalty.",
             "Orphéa Genomics trade mark registered with INPI."],
            ("Key customer contract summary: Paris university hospital (name withheld)",
             ["Per-case fee of €450 with a minimum of 300 cases a year.",
              "Public procurement contract, three years from January 2025.",
              "Data hosted on HDS-certified infrastructure in France.",
              "Hospital geneticists sign every report; Orphéa provides decision support."]),
            ("Board minutes, Q3 2026",
             ["Approved €6m seed process.",
              "Reviewed IVDR notified body timeline.",
              "Approved Belgian hospital pilot.",
              "Noted diagnostic yield stable at 41%."]),
            ("Company KYB pack",
             ["Kbis extract and statuts.",
              "Directors' ID documents.",
              "Register of beneficial owners filing."]),
            [("Health data hosting (HDS) certificate and GDPR records", "legal_ip", "ON_REQUEST",
              ["HDS certificate of the hosting provider.",
               "Data protection impact assessment.",
               "Records of processing and patient information notice."]),
             ("Diagnostic yield study", "financials", "SHARED_ONLY",
              ["Retrospective and prospective analysis of 1,180 cases across five hospitals.",
               "Comparison with each hospital's prior yield on comparable cases.",
               "Submitted for peer-reviewed publication."])]),
        qGuide=["Compassionate and exact. Families are at the centre, but never use a family's story without consent.",
                "Say 'diagnostic yield of 41% versus about 25% before', and explain how it is measured if asked.",
                "Orphéa supports geneticists; it does not make diagnoses. Hospital geneticists sign every report.",
                "Never share any patient or case detail.",
                "Do not claim CE-IVD certification. It is in progress.",
                "Do not name hospitals without their communications team's approval.",
                "Avoid medical hype. Rare-disease families have heard enough promises.",
                "French-speaking investors can be answered in French."],
        qPersonality="FORMAL",
        gateqAnswers={"sector": "Biotech / Health: genomic diagnostics software for rare disease", "stage": "seed",
                      "geography": "Paris, France; French university hospitals",
                      "chequeNeed": {"targetRaise": 6_000_000, "minimumCheque": 100_000, "currency": "EUR"},
                      "traction": "9 university hospitals; 2,300 cases analysed; diagnostic yield 41% vs 25% baseline",
                      "teamSize": 23})


# ---------------------------------------------------------------- 19 Akshar
def c19():
    contracted = [120_000, 150_000, 170_000, 190_000, 310_000, 360_000, 420_000, 460_000]
    cap = capital(
        1_200_000, "USD", "Convertible note", "valuationCap", 8_000_000, "2026-12-30", 25_000,
        [("Speech models for more Indian languages", 35), ("State programme delivery and teacher training", 30),
         ("Engineering for low-end Android phones and offline use", 20), ("Evidence studies and G&A", 15)],
        rounds(("Grant", "2024-03-15", 200_000, "USD", "Philanthropic grant (non-dilutive)", "Education philanthropy fund"),
               ("Angel", "2024-10-01", 250_000, "USD", "Convertible note", "Bengaluru founder angels")),
        ["Bengaluru founder angels", "Education philanthropy fund (grant)"],
        180_000, 28_000, 52_000)
    return dict(
        legalName="Akshar Learning Technologies Private Limited", websiteUrl="https://akshar-learning.example",
        foundedDate="2024-01-22", headquarters={"city": "Bengaluru", "country": "IN"}, currentStageCode="pre_seed",
        headcount=16,
        shortDescription="A child reads into a phone in Kannada, Hindi or English; in seconds the teacher sees exactly which sounds and words they find hard.",
        primaryDescription=("Akshar is a voice-based reading assessment for government primary schools in India. "
                            "A child reads a short passage aloud into a phone in Kannada, Hindi or English, and within seconds the teacher sees which sounds and words the child is stuck on. "
                            "It runs in 1,900 schools across two states, and over 410,000 children have been assessed. "
                            "State education departments pay a per-student annual fee."),
        tags={"industry": ["education"], "business_model": ["b2b_saas"],
              "customer_type": ["government"], "geography": ["india", "asia"],
              "other": ["edtech", "natural_language_processing", "artificial_intelligence"]},
        keywords=["reading assessment", "foundational literacy", "speech recognition", "government schools", "India",
                  "Kannada", "Hindi", "teachers", "edtech", "FLN", "oral reading fluency", "Bengaluru"],
        brand={"primary": "#F2D03B", "accent": "#2F4858", "ink": "#1B2631",
               "logoConcept": "A speech bubble shaped like the first letter of a Kannada alphabet chart"},
        founderPerson=dict(
            name="Meera Iyer", role="Co-founder & CEO", appRole="OWNER", age=30, nationality="Indian", gender="female",
            city="Bengaluru", education=["B.Tech Computer Science, PES University (2017)", "MTech (Research) in Signal Processing, Indian Institute of Science (2022)"],
            previousRoles=[{"title": "Teaching Fellow, government primary school", "org": "Teaching fellowship programme, Karnataka", "from": 2018, "to": 2020},
                           {"title": "Research Associate, speech recognition for Indian languages", "org": "University speech lab, Bengaluru", "from": 2022, "to": 2024}],
            headline="Co-founder & CEO, Akshar | Former government school teacher | Speech AI for Indian classrooms",
            professionalSummary="Taught a class of 52 children in a government school through a teaching fellowship, then researched speech recognition for Indian languages. Co-founded Akshar to let teachers hear every child read.",
            backgroundSummary="Grew up in Mysuru. The fellowship showed her that teachers could not hear each child read more than once a term.",
            languages=["Kannada", "Tamil", "English", "Hindi"]),
        team=[person("Karthik Subramanian", "Co-founder & CTO", "ADMIN", "Speech engineer; previously worked on voice assistants for Indian languages. Leads the on-device models.", "Indian", "male"),
              person("Ananya Hegde", "Programme Lead, Karnataka", "MEMBER", "Former cluster resource person in the state education department. Trains teachers and runs the district rollout.", "Indian", "female"),
              person("Rahul Verma", "State Partnerships Lead, Madhya Pradesh", "MEMBER", "Worked with the state's school education department on a literacy mission. Manages the second-state programme.", "Indian", "male")],
        capital=cap,
        metrics=metrics([("schools", "Schools live", "count", None),
                         ("states", "States with contracts", "count", None),
                         ("students_assessed_cumulative", "Students assessed, cumulative", "count", None),
                         ("students_under_contract", "Students under contract", "count", None),
                         ("contract_arr", "Annual contract value", "money", "INR")],
                        {"schools": geo(600, 1_900), "states": [1, 1, 1, 2, 2, 2, 2, 2],
                         "students_assessed_cumulative": [95_000, 140_000, 190_000, 215_000, 260_000, 300_000, 350_000, 410_000],
                         "students_under_contract": contracted, "contract_arr": [s * 60 for s in contracted]},
                        "Per-student fee of ₹60 a year. States: Karnataka (Kannada, English) and Madhya Pradesh (Hindi, English)."),
        deck=deck(
            problem=["A government school teacher with 52 children hears each child read aloud maybe once a term.",
                     "You cannot help a child read if you do not know where they are stuck."],
            solution=["A child reads a short passage into a phone in Kannada, Hindi or English.",
                      "In a few seconds the teacher sees exactly which sounds and words the child is struggling with.",
                      "Works on low-cost Android phones, with poor connectivity."],
            value_proposition=["Teachers: a reading check for every child, every month.",
                               "Departments: real reading data by school and district.",
                               "Children: help aimed at the exact sound they find hard."],
            market=["Method: government primary students in target states × per-student annual fee.",
                    "TAM: about 70 million government primary students in India × ₹60 = ₹420 crore a year.",
                    "SAM: Hindi- and Kannada-medium states, about 30 million students = ₹180 crore.",
                    "SOM: 3 million students by 2028 = ₹18 crore."],
            go_to_market=["We work with state education departments."],
            business_model=["State education departments pay ₹60 per student per year.",
                            "Teacher training included; phones supplied by schools or the state.",
                            "Gross margin 70%."],
            traction=["1,900 schools across two states.",
                      "Over 410,000 children assessed.",
                      "460,000 students under contract."],
            competition=["Paper-based assessments are what most schools use today."],
            financials=["Contract revenue: ₹3.2 crore in FY2026-27, ₹7 crore in FY2027-28, ₹18 crore in FY2028-29.",
                        f"Net burn today about ${cap['monthlyNetBurn']['amount']:,} a month; about ${cap['plannedMonthlyNetBurnPostRaise']['amount']:,} after the raise.",
                        f"Runway after the raise about {cap['runwayMonthsPostRaise']:.0f} months."],
            the_ask=["Raising a $1.2m pre-seed on a convertible note.",
                     "35% new language models, 30% programme delivery, 20% engineering, 15% evidence and G&A."],
            founders=["Meera Iyer, CEO: former government school teacher; speech-AI researcher.",
                      "Karthik Subramanian, CTO: speech engineer for Indian-language voice assistants."],
            team=["16 people: 7 engineering and speech research, 6 programme and training, 3 operations.",
                  "Programme leads in both states came from state education department roles."]),
        deckGaps=[{"section": "go_to_market", "gap": "One line; no procurement path, sales cycle or pipeline of states."},
                  {"section": "competition", "gap": "No named alternatives (e.g. other reading apps or NGO assessments) and no differentiation."}],
        dataRoom=standard_room(
            "Akshar Learning Technologies Private Limited", "the Registrar of Companies, Bengaluru (Ministry of Corporate Affairs)",
            "CIN U85500KA2024PTC187342", "2024-01-22",
            [("Meera Iyer", 46), ("Karthik Subramanian", 34), ("Employee stock option pool", 10), ("Angels (as converted)", 10)],
            10, "Four-year vesting with a one-year cliff.",
            ["Monthly management accounts in rupees.",
             "Contract value of ₹2.76 crore a year across two states at 30 Sep 2026.",
             "State payments arrive in instalments; receivables of ₹64 lakh outstanding.",
             "Cash at 30 Sep 2026: about $180,000 equivalent."],
            "GST registration and income tax returns",
            ["GST registration certificate (Karnataka) and GSTR-3B filings for FY2025-26.",
             "Income tax returns for FY2024-25.",
             "DPIIT startup recognition certificate."],
            ["Founder IP assignments covering speech models, app and reading passages.",
             "Licences for reading passages from state textbooks under the department agreements.",
             "Akshar trade mark application filed (class 9 and 41)."],
            ("Key customer contract summary: Karnataka state education department",
             ["Per-student fee of ₹60 a year for 1,200 schools.",
              "Contract awarded after a pilot in 120 schools.",
              "Child voice recordings deleted after scoring; only scores retained.",
              "One-year term, renewable for two further years."]),
            ("Board minutes, August 2026",
             ["Approved $1.2m pre-seed convertible note round.",
              "Reviewed Madhya Pradesh rollout progress.",
              "Approved Telugu and Marathi model research.",
              "Noted delayed instalment from one district."]),
            ("Company KYC pack",
             ["Certificate of incorporation, PAN and TAN.",
              "Directors' DIN and PAN.",
              "Registered office proof."]),
            [("Child data protection policy and consent process", "legal_ip", "ON_REQUEST",
              ["Verifiable parental consent through schools under the Digital Personal Data Protection Act.",
               "Recordings deleted after scoring.",
               "No advertising and no data sharing with third parties."])]),
        qGuide=["Bright and clear. Talk about children and teachers, not 'users'.",
                "Use exact figures: 1,900 schools, two states, over 410,000 children assessed.",
                "Akshar assesses reading. It does not teach or grade children for exams.",
                "Never share any child's recording, name or score.",
                "Do not name officials or imply any state endorses us beyond our contracts.",
                "Government payments can be slow. Be honest about that if asked.",
                "If asked about new languages, say they are in research, not live.",
                "Idealism is fine; overclaiming impact is not. We measure reading, then teachers act."],
        qPersonality="WARM",
        gateqAnswers={"sector": "Education: AI reading assessment for government schools", "stage": "pre_seed",
                      "geography": "Bengaluru, India; Karnataka and Madhya Pradesh",
                      "chequeNeed": {"targetRaise": 1_200_000, "minimumCheque": 25_000, "currency": "USD"},
                      "traction": "1,900 schools across 2 states; 410,000 students assessed",
                      "teamSize": 16})


# ---------------------------------------------------------------- 20 Railhead Robotics
def c20():
    yards = [6, 7, 8, 10, 12, 14, 15, 17]
    cap = capital(
        18_000_000, "USD", "Priced equity (Series A preferred)", "preMoneyValuation", 72_000_000, "2027-03-31", 1_000_000,
        [("Fleet expansion: drones, docks and spares", 35), ("Field operations and yard deployment teams", 25),
         ("Autonomy and defect-detection models", 25), ("FAA and FRA regulatory, safety and G&A", 15)],
        rounds(("Pre-seed", "2021-09-20", 1_500_000, "USD", "SAFE (post-money)", "Puget Hardware Angels"),
               ("Seed", "2022-11-30", 5_500_000, "USD", "Priced equity", "Cascade Freight Ventures")),
        ["Cascade Freight Ventures", "Northern Line Capital", "Puget Hardware Angels"],
        5_500_000, 520_000, 900_000)
    return dict(
        legalName="Railhead Robotics, Inc.", websiteUrl="https://railhead-robotics.example",
        foundedDate="2021-06-14", headquarters={"city": "Seattle", "region": "Washington", "country": "US"}, currentStageCode="series_a",
        headcount=58,
        shortDescription="Autonomous drones inspect freight rail yards every night; models flag cracks and wear on rails, ties and switches before they fail.",
        primaryDescription=("Railhead Robotics flies autonomous drones over freight rail yards every night, capturing every rail, tie and switch. "
                            "Its models flag cracks and wear long before they become failures, alongside the human inspectors who walk the line. "
                            "Railhead works with two Class I railroads across 17 yards and has found more than 1,100 track defects before failure. "
                            "It sells robotics-as-a-service on per-yard annual contracts."),
        tags={"industry": ["logistics", "manufacturing"], "business_model": ["services", "b2b_saas"],
              "customer_type": ["enterprise"], "geography": ["united_states", "north_america"],
              "other": ["robotics", "computer_vision", "mobility"]},
        keywords=["rail inspection", "drones", "freight rail", "track defects", "rail yards", "robotics-as-a-service",
                  "autonomous inspection", "Class I railroads", "computer vision", "derailment prevention", "Seattle", "infrastructure"],
        brand={"primary": "#B23A48", "accent": "#FFD23F", "ink": "#1C1C1C",
               "logoConcept": "Two parallel rails converging to a small dot overhead"},
        founderPerson=dict(
            name="Kenji Moriyama", role="Co-founder & CEO", appRole="OWNER", age=48, nationality="American", gender="male",
            city="Seattle", education=["BS Civil Engineering, University of Washington (2000)"],
            previousRoles=[{"title": "Track Inspector to Roadmaster", "org": "Western freight railroad", "from": 2001, "to": 2010},
                           {"title": "Manager of Track Maintenance", "org": "Western freight railroad", "from": 2010, "to": 2016},
                           {"title": "Director of Track Maintenance", "org": "Western freight railroad", "from": 2016, "to": 2021}],
            headline="Co-founder & CEO, Railhead Robotics | 20 years keeping freight trains on the track",
            professionalSummary="Twenty years in rail operations, from walking track as an inspector to director of track maintenance for a western freight railroad. Leads Railhead's railroad relationships and safety case.",
            backgroundSummary="Grew up in Tacoma, son of a longshoreman. Has walked a lot of track with a flashlight and respects the people who still do.",
            languages=["English", "Japanese (conversational)"]),
        team=[person("Sarah Lindqvist", "Co-founder & CTO", "ADMIN", "Robotics engineer; led autonomy for warehouse drones at a logistics company. Owns flight autonomy and the inspection models.", "American", "female"),
              person("Tyrone Washington", "VP Field Operations", "MEMBER", "Former railroad operations supervisor and FAA-certified remote pilot. Runs the nightly yard operations.", "American", "male"),
              person("Emily Chen", "Head of Machine Learning", "MEMBER", "Computer vision researcher; built defect detection for bridge inspection. Leads model training and validation.", "American", "female")],
        capital=cap,
        metrics=metrics([("yards", "Yards under contract", "count", None),
                         ("railroads", "Class I railroad customers", "count", None),
                         ("defects_found_cumulative", "Track defects found before failure, cumulative", "count", None),
                         ("arr", "Annual recurring revenue", "money", "USD")],
                        {"yards": yards, "railroads": [1, 1, 1, 2, 2, 2, 2, 2],
                         "defects_found_cumulative": [310, 390, 480, 600, 760, 870, 980, 1_100],
                         "arr": [y * 240_000 for y in yards]},
                        "ARR = yards × $240,000 per yard per year. Defects are those confirmed by railroad track staff and repaired."),
        deck=deck(
            problem=["Most rail yards are still inspected by a person walking the line with a flashlight.",
                     "Inspectors do a great job, but one person can only see so much in a shift; missed defects cause derailments."],
            solution=["Autonomous drones fly over the yard every night.",
                      "They capture every rail, tie and switch.",
                      "Models flag cracks and wear long before they become failures, for track staff to confirm."],
            value_proposition=["Full-yard coverage every night, not a sample.",
                               "Inspectors focus on confirming and fixing, not searching.",
                               "Fewer derailments and less yard downtime."],
            market=["Method: North American freight yards and terminals × per-yard annual contract, plus mainline corridors.",
                    "TAM: about 1,300 yards × $240,000 = $312m, plus about $450m for mainline corridor inspection = $762m.",
                    "SAM: about 420 yards at the six Class I railroads operating in the US = $101m.",
                    "SOM: 120 yards by 2029 = $28.8m ARR."],
            go_to_market=["Direct enterprise sales to Class I engineering and safety leadership.",
                          "Land with a few yards, expand across divisions.",
                          "Short-line and regional railroads through a partner after Series A."],
            business_model=["Robotics-as-a-service: $240,000 per yard per year, drones, docks and analysis included.",
                            "Multi-year contracts with annual yard additions.",
                            "Gross margin 58%, rising with fleet utilisation."],
            traction=["2 Class I railroads; 17 yards.",
                      "Over 1,100 track defects found before failure.",
                      "$4.08m ARR."],
            competition=["ENSCO Rail and Loram: track geometry and inspection vehicles, strong on mainline, less on yards.",
                         "Percepto: autonomous drone-in-a-box platforms for industrial sites.",
                         "Duos Technologies: railcar inspection portals.",
                         "Railhead is built for nightly full-yard track inspection by people who ran track maintenance."],
            financials=["ARR target: $9.6m end-2027, $17m end-2028, $28.8m end-2029.",
                        f"Net burn today about ${cap['monthlyNetBurn']['amount']:,} a month; about ${cap['plannedMonthlyNetBurnPostRaise']['amount']:,} after the raise.",
                        f"Runway after the raise about {cap['runwayMonthsPostRaise']:.0f} months."],
            the_ask=["Raising an $18m Series A (priced).",
                     "35% fleet expansion, 25% field operations, 25% autonomy and models, 15% regulatory, safety and G&A."],
            founders=["Kenji Moriyama, CEO: 20 years in rail operations; former director of track maintenance at a western freight railroad.",
                      "Sarah Lindqvist, CTO: led autonomy for warehouse drones at a logistics company."],
            team=["58 people: 22 engineering and ML, 26 field operations, 4 commercial, 6 G&A.",
                  "All field pilots hold FAA Part 107 certificates; operations under BVLOS waivers."]),
        deckGaps=[],
        dataRoom=standard_room(
            "Railhead Robotics, Inc.", "the Delaware Division of Corporations", "File number 5964318", "2021-06-14",
            [("Kenji Moriyama", 27), ("Sarah Lindqvist", 23), ("Cascade Freight Ventures", 22), ("Employee option pool", 15),
             ("Northern Line Capital", 8), ("Angels", 5)],
            15, "Four-year vesting with a one-year cliff; ISOs for US employees.",
            ["Monthly accrual-basis accounts with ARR by yard.",
             "ARR grew from $1.44m in Oct 2025 to $4.08m in Sep 2026.",
             "Drone fleet capitalised over three years.",
             "Cash at 30 Sep 2026: $5.5m; monthly net burn about $520k."],
            "Tax filings and certificates of good standing",
            ["Federal Form 1120 for 2023, 2024 and 2025.",
             "Delaware and Washington certificates of good standing.",
             "Washington business and occupation tax filings."],
            ["CIIAA agreements for founders and all staff.",
             "Three US patent applications on nightly yard flight planning and defect localisation.",
             "RAILHEAD trade mark registered (class 9 and 42)."],
            ("Key customer contract summary: Class I railroad (name withheld)",
             ["11 yards at $240,000 per yard per year; three-year master services agreement.",
              "Railhead flies nightly; railroad track staff confirm and repair flagged defects.",
              "Safety plan and FAA waiver compliance owned by Railhead.",
              "Images and data owned by the railroad."]),
            ("Board minutes, Q3 2026",
             ["Approved Series A process.",
              "Reviewed second railroad's expansion from 4 to 6 yards.",
              "Approved spare drone inventory policy.",
              "Noted no flight safety incidents in 2026."]),
            ("Company KYB pack",
             ["Certificate of incorporation, bylaws and EIN letter.",
              "Beneficial ownership information filing receipt.",
              "FAA operator registrations."]),
            [("FAA waivers and safety management system", "legal_ip", "SHARED_ONLY",
              ["Part 107 beyond-visual-line-of-sight waivers covering all 17 yards.",
               "Safety management system manual and incident log.",
               "Insurance certificate for aviation liability."]),
             ("Defect detection validation", "financials", "ON_REQUEST",
              ["How the 1,100 defects are counted: flagged, confirmed by railroad staff, repaired.",
               "Precision and recall against manual inspection on a 90-day sample.",
               "Breakdown by defect type."])]),
        qGuide=["Plain-spoken and patient. Rail people do not trust hype.",
                "Never name our railroad customers. Say 'two Class I railroads'.",
                "Do not criticise human inspectors. Drones help them; they do not replace them.",
                "1,100 is defects confirmed by railroad staff, not just model flags.",
                "Do not claim we prevented a specific derailment.",
                "Regulatory questions about the FAA or FRA go to me.",
                "Safety comes first in everything we say.",
                "If an investor wants to see a night operation, offer a supervised yard visit."],
        qPersonality="DIRECT",
        gateqAnswers={"sector": "Mobility / Robotics: autonomous rail infrastructure inspection", "stage": "series_a",
                      "geography": "Seattle, Washington, United States; yards across the US",
                      "chequeNeed": {"targetRaise": 18_000_000, "minimumCheque": 1_000_000, "currency": "USD"},
                      "traction": "2 Class I railroads; 17 yards; 1,100 track defects found before failure",
                      "teamSize": 58})


COMPANIES = [c16, c17, c18, c19, c20]
