import { z } from "zod";

import {
  QMessageSchema,
  QRunHandleSchema,
  QRunSummarySchema,
  QStreamEventSchema,
  toPublicQFailure,
  type CorrelationId,
  type QCapability,
  type QConsequenceClass,
  type QConversationId,
  type QFailureDiagnosticCode,
  type QMessage,
  type QMessageId,
  type QMessageRole,
  type QRunHandle,
  type QRunId,
  type QRunStatus,
  type QRunSummary,
  type QStreamEvent,
  type QStreamEventId,
  type QStreamEventType,
  type QSubjectRef,
  type QVisibleStage,
  type UtcTimestamp,
} from "@capital-q/contracts";
import type { OrganisationId, TenantId, UserId } from "@capital-q/security";

/**
 * Q runtime records (CQ-Q-002, doc 13 §34, §47).
 *
 * What the runtime holds durably, and how each is projected onto the public
 * Q contract. The records carry what the runtime needs — tenant, owner,
 * version, allocator, internal failure code — and the projections are built
 * by parsing into the public schemas, so nothing internal can reach a client
 * by accident.
 *
 *   Q conversation ≠ Q institutional memory
 *   Q message      ≠ canonical company truth
 *   Q run          ≠ Q Knowledge Object
 *   Q run event    ≠ domain event ≠ audit event
 */

/** Whether the owner was acting personally or for an organisation. */
export const Q_CONVERSATION_CONTEXT_TYPES = [
  "PERSONAL",
  "ORGANISATION",
] as const;
export type QConversationContextType =
  (typeof Q_CONVERSATION_CONTEXT_TYPES)[number];
export const QConversationContextTypeSchema = z.enum(
  Q_CONVERSATION_CONTEXT_TYPES,
);

export type QConversation = {
  readonly id: QConversationId;
  readonly tenantId: TenantId;
  /** The owner. The only person who may read or continue the conversation. */
  readonly userId: UserId;
  /** Acting context, not visibility. */
  readonly organisationId: OrganisationId | null;
  readonly contextType: QConversationContextType;
  readonly subjects: readonly QSubjectRef[];
  readonly createdAt: UtcTimestamp;
  readonly archivedAt: UtcTimestamp | null;
};

export type NewQConversation = {
  readonly tenantId: TenantId;
  readonly userId: UserId;
  readonly organisationId: OrganisationId | null;
  readonly subjects: readonly QSubjectRef[];
};

export type QRunRecord = {
  readonly id: QRunId;
  readonly tenantId: TenantId;
  readonly actorUserId: UserId;
  readonly actorOrganisationId: OrganisationId | null;
  readonly conversationId: QConversationId | null;
  readonly objective: string;
  readonly capability: QCapability;
  readonly consequenceClass: QConsequenceClass;
  readonly status: QRunStatus;
  readonly subjects: readonly QSubjectRef[];
  /** NULL until the orchestrator, prompt registry and model policy exist. */
  readonly orchestrationVersion: string | null;
  readonly promptBundleVersion: string | null;
  readonly modelPolicyVersion: string | null;
  readonly correlationId: CorrelationId;
  readonly createdAt: UtcTimestamp;
  /** When orchestration began; NULL for a run that was never picked up. */
  readonly startedAt: UtcTimestamp | null;
  readonly completedAt: UtcTimestamp | null;
  /** Internal diagnostic. Never serialised to a client as-is. */
  readonly failureCode: QFailureDiagnosticCode | null;
  readonly version: number;
  readonly lastEventSequence: number;
};

export type NewQRun = {
  readonly tenantId: TenantId;
  readonly actorUserId: UserId;
  readonly actorOrganisationId: OrganisationId | null;
  readonly conversationId: QConversationId;
  readonly objective: string;
  readonly capability: QCapability;
  readonly consequenceClass: QConsequenceClass;
  readonly subjects: readonly QSubjectRef[];
  readonly correlationId: CorrelationId;
};

export type QConversationMessage = {
  readonly id: QMessageId;
  readonly tenantId: TenantId;
  readonly conversationId: QConversationId;
  readonly runId: QRunId;
  readonly role: QMessageRole;
  readonly content: string;
  readonly contentType: "TEXT";
  readonly createdAt: UtcTimestamp;
};

export type NewQConversationMessage = {
  /**
   * Optional, server-generated by the caller. A streaming answer names the
   * message before its text exists, so the live deltas and the persisted
   * message share one identity (CQ-Q-009 §18, §79).
   */
  readonly id?: QMessageId | undefined;
  readonly tenantId: TenantId;
  readonly conversationId: QConversationId;
  readonly runId: QRunId;
  readonly role: QMessageRole;
  readonly content: string;
};

export type QRunEventRecord = {
  readonly id: QStreamEventId;
  readonly tenantId: TenantId;
  readonly runId: QRunId;
  readonly sequence: number;
  readonly eventType: QStreamEventType;
  readonly visibleStage: QVisibleStage | null;
  /** The event's `data`, exactly as the stream contract defines it. */
  readonly payload: Readonly<Record<string, unknown>>;
  readonly occurredAt: UtcTimestamp;
};

/**
 * An event to append, expressed in the public stream vocabulary so the
 * writer validates it against the contract before it is stored. The
 * runtime never stores a payload the stream could not later emit.
 */
export type NewQRunEvent = {
  readonly tenantId: TenantId;
  readonly runId: QRunId;
  readonly sequence: number;
  readonly eventType: QStreamEventType;
  readonly visibleStage: QVisibleStage | null;
  readonly payload: Readonly<Record<string, unknown>>;
};

// ---------------------------------------------------------------------------
// Public projections. Each parses into the public schema: the schema is the
// allowlist, and a record field that is not in it cannot leak.
// ---------------------------------------------------------------------------

export function toQRunHandle(run: QRunRecord): QRunHandle {
  return QRunHandleSchema.parse({
    runId: run.id,
    ...(run.conversationId === null
      ? {}
      : { conversationId: run.conversationId }),
    status: run.status,
    createdAt: run.createdAt,
  });
}

export function toQMessage(message: QConversationMessage): QMessage {
  return QMessageSchema.parse(
    message.role === "USER"
      ? {
          messageId: message.id,
          runId: message.runId,
          role: "USER",
          text: message.content,
          createdAt: message.createdAt,
        }
      : {
          messageId: message.id,
          runId: message.runId,
          role: "Q",
          text: message.content,
          createdAt: message.createdAt,
        },
  );
}

/**
 * The run as a client reads it. The failure, when there is one, is the
 * public projection of the internal code — the code itself never travels.
 */
export function toQRunSummary(
  run: QRunRecord,
  messages: readonly QConversationMessage[],
  visibleStage: QVisibleStage | null,
): QRunSummary {
  return QRunSummarySchema.parse({
    runId: run.id,
    ...(run.conversationId === null
      ? {}
      : { conversationId: run.conversationId }),
    capability: run.capability,
    status: run.status,
    visibleStage,
    subjects: run.subjects,
    messages: messages.map(toQMessage),
    ...(run.status === "FAILED" && run.failureCode !== null
      ? {
          failure: toPublicQFailure(
            { diagnosticCode: run.failureCode },
            { runId: run.id },
          ),
        }
      : {}),
    correlationId: run.correlationId,
    createdAt: run.createdAt,
    ...(run.startedAt === null ? {} : { startedAt: run.startedAt }),
    ...(run.completedAt === null ? {} : { completedAt: run.completedAt }),
  });
}

/** A stored event back in its stream form, validated against the contract. */
export function toQStreamEvent(event: QRunEventRecord): QStreamEvent {
  return QStreamEventSchema.parse({
    contractVersion: 1,
    eventId: event.id,
    runId: event.runId,
    sequence: event.sequence,
    occurredAt: event.occurredAt,
    type: event.eventType,
    data: event.payload,
  });
}
