/**
 * Q contracts (CQ-Q-001, doc 12 §7-9, §37, §44, §70; doc 22 §66-84).
 *
 * The language every client -- Capital Q web, mobile later, GateQ, future
 * partners -- uses to talk to Q, and the language Q uses to answer. It
 * describes capability and product semantics only. There is no LangGraph
 * node, graph checkpoint, provider thread, model name, prompt identifier,
 * specialist name, chain-of-thought or scratchpad anywhere in this surface,
 * and none may be added: implementation frameworks stay behind adapters in
 * the packets that introduce them.
 *
 * Two trust zones share this directory and are named on every type:
 *
 *   PUBLIC    may reach a client. Every public schema is an allowlist; a
 *             response is built by parsing into it, never by serialising an
 *             internal object.
 *   INTERNAL  runtime only. Carries what the Context Firewall, the approval
 *             engine and observability need to decide what may leave.
 *
 * Nothing here executes anything. No model is called, no graph runs, no
 * retrieval occurs, no tool executes, no action executes, no table exists.
 */

export {
  Q_CONTRACT_VERSION,
  QContractVersionSchema,
  type QContractVersion,
} from "./version.js";

export {
  QActionProposalIdSchema,
  QApprovalIdSchema,
  QConversationIdSchema,
  QArtifactIdSchema,
  QFindingIdSchema,
  QMessageIdSchema,
  QRunIdSchema,
  QStreamEventIdSchema,
  QToolCallIdSchema,
  type QActionProposalId,
  type QApprovalId,
  type QConversationId,
  type QArtifactId,
  type QFindingId,
  type QMessageId,
  type QRunId,
  type QStreamEventId,
  type QToolCallId,
} from "./ids.js";

export {
  Q_CAPABILITIES,
  Q_CLIENT_MODALITIES,
  Q_CONSEQUENCE_CLASSES,
  Q_MODALITIES,
  Q_SOURCE_APPLICATIONS,
  QCapabilitySchema,
  QClientModalitySchema,
  QConsequenceClassSchema,
  QModalitySchema,
  QSourceApplicationSchema,
  type QCapability,
  type QConsequenceClass,
  type QModality,
  type QSourceApplication,
} from "./capability.js";

export {
  Q_SUBJECT_KINDS,
  Q_SUBJECTS_MAX,
  QCapitalObjectiveSubjectSchema,
  QCompanySubjectSchema,
  QDocumentSubjectSchema,
  QInvestorOrganisationSubjectSchema,
  QOrganisationSubjectSchema,
  QRelationshipSubjectSchema,
  QSubjectKindSchema,
  QSubjectRefSchema,
  QSubjectRefsSchema,
  QUserSubjectSchema,
  type QSubjectKind,
  type QSubjectRef,
} from "./subject.js";

export {
  Q_OBJECTIVE_MAX_LENGTH,
  QActorSchema,
  QInteractionSchema,
  QLocaleSchema,
  QPurposeSchema,
  QRequestContextSchema,
  QRequestedKnowledgeScopesSchema,
  QTenantSchema,
  type QActor,
  type QInteraction,
  type QPurpose,
  type QRequestContext,
  type QTenant,
} from "./context.js";

export {
  AppendQRunMessageRequestSchema,
  CreateQRunRequestSchema,
  Q_MESSAGE_TEXT_MAX_LENGTH,
  Q_OPENING_MAX_LENGTH,
  QRequestEnvelopeSchema,
  QUserMessageInputSchema,
  QViewingMomentSchema,
  Q_SCREEN_ROUTES,
  QScreenContextSchema,
  QScreenRouteSchema,
  type QScreenContext,
  type QScreenRoute,
  type AppendQRunMessageRequest,
  type CreateQRunRequest,
  type QRequestEnvelope,
  type QUserMessageInput,
  type QViewingMoment,
} from "./request.js";

export {
  manifestRefs,
  Q_MANIFEST_DIALOG_KINDS,
  Q_MANIFEST_DIALOG_REFS_MAX,
  Q_MANIFEST_DIALOGS_MAX,
  Q_MANIFEST_FILTER_KEYS,
  Q_MANIFEST_REF_KINDS,
  Q_MANIFEST_SECTION_KINDS,
  Q_MANIFEST_SECTION_REFS_MAX,
  Q_MANIFEST_SECTIONS_MAX,
  Q_MANIFEST_TABS,
  QManifestDialogKindSchema,
  QManifestDialogSchema,
  QManifestRefKindSchema,
  QManifestRefSchema,
  QManifestSectionKindSchema,
  QManifestSectionSchema,
  QManifestTabSchema,
  QPageManifestSchema,
  type QManifestDialog,
  type QManifestDialogKind,
  type QManifestRef,
  type QManifestRefKind,
  type QManifestSection,
  type QManifestSectionKind,
  type QManifestTab,
  type QPageManifest,
} from "./screen-manifest.js";

export {
  PermittedContextPlanSchema,
  Q_COMBINATION_EFFECTS,
  Q_CONTEXT_DENIAL_REASONS,
  Q_CONTEXT_FIREWALL_POLICY_VERSION,
  Q_FACT_CATEGORIES,
  Q_KNOWLEDGE_SCOPE_KINDS,
  Q_PLAN_DENIED_MAX,
  Q_PLAN_SCOPES_MAX,
  Q_RETRIEVAL_LAYERS,
  Q_SCOPE_PROJECTIONS,
  Q_SENSITIVITY_RANK,
  Q_TASK_CLASSES,
  QAuthorisedKnowledgeScopeSchema,
  QCombinationConstraintSchema,
  QContextDenialReasonSchema,
  QContextLabelSchema,
  QDeniedScopeSchema,
  QDisclosureRightsSchema,
  QFactCategorySchema,
  QKnowledgeScopeKindSchema,
  QRetrievalLayerSchema,
  QScopeFilterSchema,
  QScopeProjectionSchema,
  QSensitivityClassSchema,
  QTaskClassSchema,
  sensitivityWithin,
  strongerSensitivity,
  type PermittedContextPlan,
  type QAuthorisedKnowledgeScope,
  type QCombinationConstraint,
  type QContextDenialReason,
  type QContextLabel,
  type QDeniedScope,
  type QDisclosureRights,
  type QFactCategory,
  type QKnowledgeScopeKind,
  type QRetrievalLayer,
  type QScopeFilter,
  type QScopeProjection,
  type QSensitivityClass,
  type QTaskClass,
} from "./firewall.js";

export {
  AppendQRunMessageResponseSchema,
  CreateQRunResponseSchema,
  LAST_EVENT_ID_HEADER,
  LastEventIdHeaderSchema,
  Q_APPROVAL_APPROVE_SUFFIX,
  Q_APPROVAL_REJECT_SUFFIX,
  Q_APPROVALS_PATH,
  Q_RUN_CANCEL_SUFFIX,
  Q_RUN_EVENTS_SUFFIX,
  Q_RUN_MESSAGES_SUFFIX,
  Q_RUNS_PATH,
  Q_SSE_CONTENT_TYPE,
  Q_SSE_MAX_LAST_EVENT_ID,
  type AppendQRunMessageResponse,
  type CreateQRunResponse,
} from "./http.js";

export {
  isTerminalQRunStatus,
  Q_RUN_MESSAGES_MAX,
  Q_RUN_STATUSES,
  Q_RUN_TERMINAL_STATUSES,
  Q_RUN_WAITING_STATUSES,
  QRunHandleSchema,
  QRunStatusSchema,
  QRunSummarySchema,
  QRunTerminalStatusSchema,
  type QRunHandle,
  type QRunStatus,
  type QRunSummary,
  type QRunTerminalStatus,
} from "./run.js";

export {
  CreateQVoiceSessionRequestSchema,
  CreateQVoiceSessionResponseSchema,
  OnboardingJourneyTypeForVoiceSchema,
  Q_VOICE_CHOICES,
  Q_VOICE_SESSIONS_PATH,
  Q_VOICE_WS_PATH,
  Q_VOICE_TURN_PATH,
  Q_VOICE_SCREEN_PATH,
  QVoiceScreenUpdateSchema,
  type QVoiceScreenUpdate,
  Q_VOICE_THINK_PATH,
  Q_VOICE_HM_BEATS,
  Q_VOICE_HUM_BEATS,
  Q_VOICE_QUESTION_BEAT,
  Q_VOICE_THINKING_BEATS,
  Q_VOICE_SPEECH_PATH,
  Q_SPEECH_MAX_CHARS,
  Q_SPEECH_MAX_BYTES,
  Q_SPEECH_MEDIA_TYPE,
  CreateQSpeechRequestSchema,
  type CreateQSpeechRequest,
  Q_VOICE_PROVIDERS,
  QVoiceProviderSchema,
  type QVoiceProvider,
  Q_VOICE_DESTINATIONS,
  qVoiceTurnPath,
  qVoiceScreenPath,
  QVoiceDestinationSchema,
  QVoiceTurnStateSchema,
  QVoiceChoiceSchema,
  type CreateQVoiceSessionRequest,
  type CreateQVoiceSessionResponse,
  type QVoiceChoice,
  type QVoiceDestination,
  type QVoiceTurnState,
  QVoiceDuplexCredentialSchema,
  type QVoiceDuplexCredential,
  Q_VOICE_LISTENING_LEVELS,
  Q_VOICE_LISTENING_DEFAULT,
  QVoiceListeningLevelSchema,
  type QVoiceListeningLevel,
  QVoiceDuplexListeningSchema,
  type QVoiceDuplexListening,
  Q_VOICE_DUPLEX_TOOL_PATH,
  Q_VOICE_DUPLEX_NARRATION_PATH,
  qVoiceDuplexNarrationPath,
  QVoiceDuplexNarrationRequestSchema,
  type QVoiceDuplexNarrationRequest,
  QVoiceDuplexNarrationResultSchema,
  type QVoiceDuplexNarrationResult,
  Q_VOICE_DUPLEX_USAGE_PATH,
  Q_VOICE_DUPLEX_END_PATH,
  qVoiceDuplexToolPath,
  qVoiceDuplexUsagePath,
  qVoiceDuplexEndPath,
  QVoiceDuplexToolCallSchema,
  type QVoiceDuplexToolCall,
  QVoiceDuplexToolResultSchema,
  type QVoiceDuplexToolResult,
  Q_VOICE_DUPLEX_HEARD_PATH,
  qVoiceDuplexHeardPath,
  QVoiceDuplexHeardSchema,
  type QVoiceDuplexHeard,
  Q_VOICE_DUPLEX_ROUTES,
  QVoiceDuplexHeardResultSchema,
  type QVoiceDuplexHeardResult,
  Q_VOICE_DUPLEX_SAID_PATH,
  qVoiceDuplexSaidPath,
  QVoiceDuplexSaidSchema,
  type QVoiceDuplexSaid,
  QVoiceDuplexUsageReportSchema,
  type QVoiceDuplexUsageReport,
  QVoiceDuplexUsageResultSchema,
  type QVoiceDuplexUsageResult,
  QVoiceDuplexEndSchema,
  type QVoiceDuplexEnd,
  Q_VOICE_DUPLEX_FALLBACK_CAUSES,
  QVoiceDuplexLineStatsSchema,
  type QVoiceDuplexLineStats,
  Q_VOICE_DUPLEX_REJOIN_PATH,
  qVoiceDuplexRejoinPath,
  QVoiceDuplexRejoinSchema,
  type QVoiceDuplexRejoin,
  QVoiceDuplexRejoinResultSchema,
  type QVoiceDuplexRejoinResult,
} from "./voice.js";

export {
  Q_VISIBLE_STAGE_LABELS,
  Q_VISIBLE_STAGES,
  qVisibleStageLabel,
  QVisibleStageSchema,
  type QVisibleStage,
} from "./stage.js";

export {
  nextSilenceBeat,
  Q_HUM_STYLES,
  Q_SILENCE_BEAT_KINDS,
  Q_SILENCE_LADDER,
  Q_SILENCE_START,
  Q_SILENCE_THINGS,
  QSilenceBeatSchema,
  QSilenceFocusSchema,
  silenceHum,
  silenceProgressLine,
  silenceStageLine,
  silenceThingForRoute,
  silenceThreadLine,
  stripSilenceBeats,
  type QHumStyle,
  type QSilenceBeat,
  type QSilenceBeatKind,
  type QSilenceFocus,
  type QSilenceInput,
  type QSilenceState,
  type QSilenceStep,
  type QSilenceThing,
  type QSilenceThread,
} from "./silence-ladder.js";

export {
  Q_MESSAGE_ROLES,
  Q_RESPONSE_TEXT_MAX_LENGTH,
  QMessageRoleSchema,
  QMessageSchema,
  QResponseMessageSchema,
  QUserMessageSchema,
  type QMessage,
  type QMessageRole,
  type QResponseMessage,
  type QUserMessage,
} from "./message.js";

// PRESENCE block
export {
  Q_GESTURE_MAX_SENTENCE_INDEX,
  Q_GESTURES_MAX,
  Q_PRESENCE_GESTURES,
  QPresenceGestureSchema,
  QSentenceGestureSchema,
  QSentenceGesturesSchema,
  QVoicePresenceSchema,
  type QPresenceGesture,
  type QSentenceGesture,
  type QSentenceGestures,
  type QVoicePresence,
} from "./presence.js";
// end PRESENCE block

export {
  Q_CONFIDENCE_LABELS,
  Q_CONFIDENCE_LEVELS,
  Q_UNCERTAIN_CONFIDENCE_LEVELS,
  qConfidenceLabel,
  QConfidenceLevelSchema,
  QUncertainConfidenceLevelSchema,
  type QConfidenceLevel,
} from "./confidence.js";

export {
  Q_EVIDENCE_REF_KINDS,
  Q_EVIDENCE_REFS_MAX,
  QClaimRefSchema,
  QDocumentRefSchema,
  QEvidenceItemRefSchema,
  QEvidenceRefKindSchema,
  QEvidenceRefSchema,
  QEvidenceRefsSchema,
  QSourceRefSchema,
  type QEvidenceRef,
  type QEvidenceRefKind,
} from "./evidence-ref.js";

export {
  Q_FINDING_ASSUMPTION_MAX_LENGTH,
  Q_FINDING_ASSUMPTIONS_MAX,
  Q_FINDING_STATEMENT_MAX_LENGTH,
  Q_FINDING_TYPES,
  QFindingTypeSchema,
  QInternalFindingSchema,
  QPublicFindingSchema,
  type QFindingType,
  type QInternalFinding,
  type QPublicFinding,
} from "./finding.js";

export {
  Q_CLARIFICATION_OPTION_MAX_LENGTH,
  Q_CLARIFICATION_OPTIONS_MAX,
  Q_CLARIFICATION_OPTIONS_MIN,
  Q_CLARIFICATION_QUESTION_MAX_LENGTH,
  Q_COMPARISON_LABEL_MAX_LENGTH,
  Q_COMPARISON_ROWS_MAX,
  Q_COMPARISON_VALUE_MAX_LENGTH,
  Q_RESULT_BLOCK_KINDS,
  Q_RESULT_BLOCKS_MAX,
  Q_TEXT_BLOCK_MAX_LENGTH,
  Q_UNCERTAINTY_MISSING_ITEM_MAX_LENGTH,
  Q_UNCERTAINTY_MISSING_MAX,
  Q_UNCERTAINTY_STATEMENT_MAX_LENGTH,
  QActionProposalBlockSchema,
  QArtifactReferenceBlockSchema,
  QDocumentToolResultSchema,
  type QDocumentToolResult,
  QClarificationRequestBlockSchema,
  QCompanyReferenceBlockSchema,
  QComparisonBlockSchema,
  QComparisonCardsBlockSchema,
  QEvidenceBlockSchema,
  QFindingBlockSchema,
  QInvestorReferenceBlockSchema,
  QResultBlockKindSchema,
  QResultBlockSchema,
  QResultBlocksSchema,
  QTextBlockSchema,
  QUiIntentBlockSchema,
  QPublicSourceBlockSchema,
  QUncertaintyBlockSchema,
  type QResultBlock,
  type QResultBlockKind,
} from "./result-block.js";

export {
  Q_ANSWER_CARD_FOLLOW_UPS_MAX,
  Q_ANSWER_CARD_HUES,
  Q_ANSWER_CARD_LEVELS,
  Q_ANSWER_CARD_MEASURES_MAX,
  Q_ANSWER_CARD_REASONS_MAX,
  Q_ANSWER_CARDS_MAX,
  Q_ANSWER_CARDS_SHAPES,
  QAnswerCardFitSchema,
  QAnswerCardLevelSchema,
  QAnswerCardMeasureSchema,
  QAnswerCardSchema,
  QAnswerCardsBlockSchema,
  QAnswerCardsShapeSchema,
  type QAnswerCard,
  type QAnswerCardFit,
  type QAnswerCardLevel,
  type QAnswerCardMeasure,
  type QAnswerCardsBlock,
  type QAnswerCardsShape,
} from "./answer-cards.js";

export {
  Q_COMPARISON_SUBJECTS_MAX,
  Q_COMPARISON_SUBJECTS_MIN,
  Q_UI_COMPANY_SECTIONS,
  Q_NAVIGATE_DESTINATIONS,
  Q_UI_INTENT_KINDS,
  QNavigateDestinationSchema,
  QNavigateIntentSchema,
  QFocusSectionIntentSchema,
  QOpenCompanyIntentSchema,
  QShowComparisonIntentSchema,
  QShowEvidenceIntentSchema,
  QUiCompanySectionSchema,
  QUiIntentKindSchema,
  QUiIntentSchema,
  Q_THEME_CHOICES,
  Q_WEBSITE_URL_MAX_LENGTH,
  QThemeChoiceSchema,
  QWebsiteUrlSchema,
  QSetThemeIntentSchema,
  QReloadPageIntentSchema,
  QOpenWebsiteIntentSchema,
  Q_MOTION_CHOICES,
  QMotionChoiceSchema,
  QSetQMotionIntentSchema,
  QSetVoiceIntentSchema,
  QSignOutIntentSchema,
  Q_RECORD_PAGES,
  Q_ROOM_OBJECTS,
  Q_SETTINGS_SECTIONS,
  QOpenSettingsIntentSchema,
  QRoomObjectSchema,
  QSettingsSectionSchema,
  QShowInQRoomIntentSchema,
  QShowCalendarConnectIntentSchema,
  type QShowCalendarConnectIntent,
  Q_DOCUMENT_ACTS,
  Q_DOCUMENT_PAGE_MAX,
  QDocumentActSchema,
  QDocumentActIntentSchema,
  type QOpenSettingsIntent,
  type QRoomObject,
  type QSettingsSection,
  type QShowInQRoomIntent,
  type QDocumentAct,
  type QDocumentActIntent,
  Q_SCREEN_ACTS,
  Q_SCREEN_SECTIONS,
  QRecordPageSchema,
  QScreenActIntentSchema,
  QScreenActSchema,
  QScreenSectionSchema,
  type QScreenAct,
  type QScreenActIntent,
  QOpenRecordPageIntentSchema,
  QOpenSetupIntentSchema,
  QSetDiscoverFiltersIntentSchema,
  type QSetDiscoverFiltersIntent,
  type QRecordPage,
  type QMotionChoice,
  QClientActionIntentSchema,
  Q_CLIENT_ACTION_TOOLS,
  Q_INSTANT_ACTION_TOOLS,
  QClientActionToolResultSchema,
  type QClientActionToolResult,
  type QClientActionIntent,
  type QThemeChoice,
  type QUiCompanySection,
  type QUiIntent,
  type QUiIntentKind,
  type QNavigateDestination,
} from "./ui-intent.js";

export {
  isTerminalQToolCallStatus,
  Q_TOOL_CALL_STATUSES,
  Q_TOOL_CALL_TERMINAL_STATUSES,
  Q_TOOL_CLASSIFICATIONS,
  QToolCallRecordSchema,
  QToolCallStatusSchema,
  QToolClassificationSchema,
  QToolFailureCodeSchema,
  QToolNameSchema,
  QToolProgressSchema,
  type QToolCallRecord,
  type QToolCallStatus,
  type QToolClassification,
  type QToolName,
  type QToolProgress,
} from "./tool.js";

export {
  isTerminalQActionStatus,
  Q_ACTION_BINDING_VERSION,
  Q_ACTION_CLASSES,
  Q_ACTION_PREVIEW_MAX_LENGTH,
  Q_ACTION_PROPOSAL_STATUSES,
  Q_ACTION_STATUSES,
  Q_ACTION_SUMMARY_MAX_LENGTH,
  Q_ACTION_TERMINAL_STATUSES,
  Q_APPROVAL_REQUIRED_ACTION_CLASSES,
  Q_APPROVAL_STATUSES,
  QActionBindingEnvelopeSchema,
  QActionClassSchema,
  QActionPayloadHashSchema,
  QActionProposalSchema,
  QActionProposalStatusSchema,
  QActionStatusSchema,
  QActionTypeSchema,
  QActionVersionSchema,
  QApprovalRefSchema,
  QApprovalRequirementSchema,
  QApprovalStatusSchema,
  type QActionBindingEnvelope,
  type QActionClass,
  type QActionPayloadHash,
  type QActionProposal,
  type QActionProposalStatus,
  type QActionStatus,
  type QActionType,
  type QApprovalRef,
  type QApprovalRequirement,
  type QApprovalStatus,
} from "./action.js";

export {
  ApproveQApprovalRequestSchema,
  Q_APPROVAL_REJECTION_REASON_MAX_LENGTH,
  QApprovalActionViewSchema,
  QApprovalViewSchema,
  Q_PENDING_APPROVALS_MAX,
  QPendingApprovalListSchema,
  QPendingApprovalSchema,
  RejectQApprovalRequestSchema,
  type ApproveQApprovalRequest,
  type QApprovalActionView,
  type QApprovalView,
  type QPendingApproval,
  type QPendingApprovalList,
  type RejectQApprovalRequest,
} from "./approval.js";

export {
  Q_FAILURE_DETAIL_MAX_LENGTH,
  Q_FAILURE_DIAGNOSTIC_CODES,
  Q_PUBLIC_FAILURE_CODES,
  Q_PUBLIC_FAILURE_MESSAGE_MAX_LENGTH,
  Q_PUBLIC_FAILURE_MESSAGES,
  QFailureDiagnosticCodeSchema,
  QPublicFailureCodeSchema,
  QPublicFailureSchema,
  QRunFailureSchema,
  toPublicQFailure,
  type QFailureDiagnosticCode,
  type QPublicFailure,
  type QPublicFailureCode,
  type QPublicFailureRefs,
  type QRunFailure,
  type QRunFailureLike,
} from "./failure.js";

export {
  isDurableQStreamEvent,
  isDurableQStreamEventType,
  isTerminalQStreamEvent,
  Q_STREAM_DELTA_MAX_LENGTH,
  Q_STREAM_DURABLE_EVENT_TYPES,
  Q_STREAM_EPHEMERAL_EVENT_TYPES,
  Q_STREAM_EVENT_TYPES,
  Q_STREAM_TERMINAL_EVENT_TYPES,
  QActionProposedEventSchema,
  QApprovalRequiredEventSchema,
  QFindingAvailableEventSchema,
  QInputRequiredEventSchema,
  QMessageCompletedEventSchema,
  QMessageDeltaEventSchema,
  QRunCompletedEventSchema,
  QRunFailedEventSchema,
  QRunStartedEventSchema,
  QStageChangedEventSchema,
  QStreamEventSchema,
  QStreamEventTypeSchema,
  QStreamSequenceSchema,
  type QStreamEvent,
  type QStreamEventType,
} from "./stream.js";

export {
  Q_CHALLENGE_LEVELS,
  Q_COMMUNICATION_PRESETS,
  Q_COMMUNICATION_PROFILES,
  Q_DEFAULT_COMMUNICATION_PRESET,
  Q_EXPLANATION_STYLES,
  Q_OPERATING_MODES,
  Q_PROACTIVITY_MODES,
  Q_QUESTION_STYLES,
  Q_RESPONSE_DEPTHS,
  Q_TONES,
  QChallengeLevelSchema,
  QCommunicationPresetSchema,
  QCommunicationProfileSchema,
  QExplanationStyleSchema,
  QOperatingModeSchema,
  QProactivityModeSchema,
  QQuestionStyleSchema,
  QResponseDepthSchema,
  QToneSchema,
  type QChallengeLevel,
  type QCommunicationPreset,
  type QCommunicationProfile,
  type QExplanationStyle,
  type QOperatingMode,
  type QProactivityMode,
  type QQuestionStyle,
  type QResponseDepth,
  type QTone,
} from "./communication.js";

export {
  ListQConversationsQuerySchema,
  ListQConversationsResponseSchema,
  Q_CONVERSATION_ARCHIVE_SUFFIX,
  Q_CONVERSATION_MESSAGE_HIDE_SUFFIX,
  Q_CONVERSATION_MESSAGES_MAX,
  Q_CONVERSATIONS_PAGE_MAX,
  Q_CONVERSATIONS_PATH,
  QConversationDetailSchema,
  QConversationSummarySchema,
  QConversationTitleSchema,
  type ListQConversationsQuery,
  type ListQConversationsResponse,
  type QConversationDetail,
  type QConversationSummary,
} from "./conversation.js";

export {
  Q_ARTIFACT_FINDINGS_PER_SECTION_MAX,
  Q_ARTIFACT_INSTRUCTION_MAX,
  Q_ARTIFACT_SECTION_BODY_MAX,
  Q_ARTIFACT_SECTIONS_MAX,
  Q_ARTIFACT_STATUSES,
  Q_ARTIFACT_SUMMARY_MAX,
  Q_ARTIFACT_TITLE_MAX,
  Q_ARTIFACT_TYPES,
  Q_ARTIFACT_VERSIONS_SUFFIX,
  Q_ARTIFACTS_PATH,
  Q_CHART_KINDS,
  Q_CHART_POINTS_MAX,
  Q_DECK_SLIDES_MAX,
  Q_SLIDE_BULLET_MAX,
  Q_SLIDE_BULLETS_MAX,
  Q_SLIDE_LAYOUTS,
  Q_VISUAL_DIRECTIONS,
  Q_ARTIFACT_EXPORT_FORMATS,
  Q_ARTIFACT_EXPORT_REFUSALS,
  Q_ARTIFACT_EXPORT_SUFFIX,
  qArtifactExportFormats,
  qArtifactPath,
  QArtifactExportFormatSchema,
  QArtifactExportRefusalSchema,
  type QArtifactExportFormat,
  type QArtifactExportRefusal,
  CreateQArtifactRequestSchema,
  ListQArtifactsQuerySchema,
  ListQArtifactsResponseSchema,
  QArtifactContentSchema,
  QArtifactDetailSchema,
  QArtifactSectionSchema,
  QArtifactStatusSchema,
  QArtifactSummarySchema,
  QArtifactTypeSchema,
  QArtifactVersionSchema,
  QChartKindSchema,
  QChartPointSchema,
  QChartSchema,
  QDeckSchema,
  QDocumentLookSchema,
  QDeckColourSchema,
  QSlideImageSchema,
  Q_SLIDE_IMAGE_HOST,
  // DOCS block: generated images.
  Q_GENERATED_IMAGE_SCHEME,
  generatedImageId,
  type QSlideImage,
  QSlideLayoutSchema,
  QSlideSchema,
  QVisualDirectionSchema,
  ReviseQArtifactRequestSchema,
  type CreateQArtifactRequest,
  type ListQArtifactsQuery,
  type ListQArtifactsResponse,
  type QArtifactContent,
  type QChart,
  type QChartKind,
  type QChartPoint,
  type QDeck,
  type QDocumentLook,
  type QSlide,
  type QSlideLayout,
  type QVisualDirection,
  type QArtifactDetail,
  type QArtifactSection,
  type QArtifactStatus,
  type QArtifactSummary,
  type QArtifactType,
  type QArtifactVersion,
  type ReviseQArtifactRequest,
} from "./artifact.js";

// DOCS block: brand kit, audit, pairings, answer exports.
export {
  Q_ANSWER_EXPORTS_PATH,
  Q_BRAND_KIT_CONFIRM_SUFFIX,
  Q_BRAND_KIT_LOGO_SUFFIX,
  Q_BRAND_KIT_PATH,
  Q_BRAND_KIT_SOURCES,
  Q_BRAND_KIT_STATUSES,
  Q_BRAND_KIT_SUGGEST_SUFFIX,
  Q_BRAND_LOGO_MAX_BYTES,
  Q_DOCUMENT_AUDIT_CHECKS,
  Q_FONT_PAIRINGS,
  ConfirmQBrandKitRequestSchema,
  CreateQAnswerExportRequestSchema,
  QBrandKitSchema,
  QBrandKitSourceSchema,
  QBrandKitStateSchema,
  QBrandKitStatusSchema,
  QBrandPaletteSchema,
  QDocumentAuditSchema,
  QDocumentRubricSchema,
  QDocumentEditSchema,
  Q_DOCUMENT_EDIT_KINDS,
  FillQArtifactPlaceholderRequestSchema,
  FillQArtifactPlaceholderResponseSchema,
  Q_ARTIFACT_PROGRESS_SUFFIX,
  Q_ARTIFACT_PLACEHOLDERS_SUFFIX,
  type QDocumentEdit,
  type FillQArtifactPlaceholderRequest,
  type FillQArtifactPlaceholderResponse,
  QDocumentPipelineStageSchema,
  QDocumentPipelineProgressSchema,
  Q_DOCUMENT_PIPELINE_STAGES,
  Q_DOCUMENT_PIPELINE_STAGE_LINES,
  QSlidePlaceholderSchema,
  Q_SLIDE_PLACEHOLDER_KINDS,
  type QDocumentRubric,
  type QDocumentPipelineStage,
  type QDocumentPipelineProgress,
  type QSlidePlaceholder,
  QFontPairingSchema,
  SetQBrandKitRequestSchema,
  type ConfirmQBrandKitRequest,
  type CreateQAnswerExportRequest,
  type QBrandKit,
  type QBrandKitSource,
  type QBrandKitState,
  type QBrandKitStatus,
  type QBrandPalette,
  type QDocumentAudit,
  type QFontPairing,
  type SetQBrandKitRequest,
} from "./artifact.js";

export {
  Q_INTERVIEW_PATH,
  Q_INTERVIEW_TURN_SEGMENT,
  QInterviewAskingSchema,
  QInterviewTurnRequestSchema,
  QInterviewTurnResponseSchema,
  type QInterviewTurnRequest,
  type QInterviewTurnResponse,
} from "./interview.js";

export {
  PROFILE_FINDING_KEYS,
  PROFILE_FINDING_SUBJECT_TYPES,
  ProfileFindingKeySchema,
  ProfileFindingSchema,
  ProfileFindingSourceSchema,
  ProfileFindingSubjectTypeSchema,
  ProfileFindingsQuerySchema,
  ProfileFindingsResponseSchema,
  Q_PROFILE_FINDINGS_PATH,
  type ProfileFinding,
  type ProfileFindingKey,
  type ProfileFindingSource,
  type ProfileFindingSubjectType,
  type ProfileFindingsQuery,
  type ProfileFindingsResponse,
} from "./profile-findings.js";

export {
  Q_MEMORY_FORGET_PATH,
  Q_MEMORY_KINDS,
  Q_MEMORY_PATH,
  QMemoryItemDtoSchema,
  QMemoryListDtoSchema,
  type QMemoryItemDto,
  type QMemoryListDto,
} from "./memory.js";

export {
  Q_MEETING_ASSISTANT_PATH,
  Q_MEETING_ASSISTANT_STATUSES,
  Q_MEETING_FLAG_KINDS,
  QMeetingAssistantDtoSchema,
  QMeetingAssistantStatusSchema,
  QMeetingCommitmentSignalSchema,
  type QMeetingCommitmentSignal,
  QMeetingFlagSchema,
  QMeetingFollowUpSchema,
  qMeetingAssistantPath,
  type QMeetingAssistantDto,
  type QMeetingAssistantStatus,
  type QMeetingFlag,
  type QMeetingFollowUp,
} from "./meeting-assistant.js";
export {
  Q_ERRAND_PATH,
  Q_ERRAND_STATUSES,
  Q_RELATIONSHIP_ERRANDS_PATH,
  QErrandDtoSchema,
  QErrandListDtoSchema,
  qErrandPath,
  qRelationshipErrandsPath,
  QErrandStoppedDtoSchema,
  type QErrandDto,
  type QErrandListDto,
  type QErrandStoppedDto,
} from "./errands.js";
// REHEARSE block (2026-10-01)
export * from "./rehearsals.js";
// end REHEARSE block
export {
  Q_CONDUCT_ACTIONS,
  Q_CONDUCT_MOODS,
  Q_PERSONALITIES,
  Q_STANDING_PATH,
  Q_STANDING_PERSONALITY_PATH,
  QConductSchema,
  QPersonalitySchema,
  QStandingDtoSchema,
  SetQPersonalityRequestSchema,
  type QConduct,
  type QConductMood,
  type QPersonality,
  type QStandingDto,
} from "./conduct.js";
// Standing instructions (ADR 0043).
export {
  handleEverythingGrant,
  INSTRUCTION_ACTIONS_BY_SIDE,
  INSTRUCTION_DEFAULT_ACTIONS,
  INSTRUCTION_HAND_OVER_ACTIONS,
  INSTRUCTION_HAND_OVER_KINDS,
  type InstructionHandOverKind,
  INSTRUCTION_ACTION_MODES,
  INSTRUCTION_AUTO_ELIGIBLE_ACTIONS,
  INSTRUCTION_BUDGET_USD_MONTH_DEFAULT,
  INSTRUCTION_MESSAGES_PER_COUNTERPART_MAX,
  InstructionGrantPayloadSchema,
  InstructionGrantSchema,
  InstructionWorkingHoursSchema,
  Q_INSTRUCTION_GRANT,
  STANDING_INSTRUCTION_STATUSES,
  StandingInstructionDtoSchema,
  type StandingInstructionDto,
  type InstructionActionMode,
  type InstructionGrant,
  type InstructionGrantPayload,
  type InstructionWorkingHours,
  type StandingInstructionStatus,
  DELEGATED_ROUTINE_ACTIONS,
  DELEGATION_LIMITS,
  INSTRUCTION_DELEGATION_SCOPES,
  INSTRUCTION_DELEGATION_WORDS,
  InstructionDelegationDtoSchema,
  InstructionDelegationRequestSchema,
  type InstructionDelegationDto,
  type InstructionDelegationRequest,
  type InstructionDelegationScope,
} from "./instructions.js";
// AUTO block: Q's delegated work (ADR 0030).
export {
  Q_PRESENCE_PATH,
  Q_WORK_ITEM_PATH,
  Q_WORK_KINDS,
  Q_WORK_WAKE_CHANNEL,
  Q_INSTRUCTION_WAKE_CHANNEL,
  Q_INSTRUCTION_NEW_COMPANY_CHANNEL,
  Q_WORK_LANE_ANSWER_PATH,
  Q_WORK_LANE_PATH,
  Q_WORK_LANE_STAGES,
  Q_WORK_PATH,
  Q_WORK_STATUSES,
  QPresenceRequestSchema,
  QWorkAcceptedDtoSchema,
  QWorkDetailDtoSchema,
  QWorkDtoSchema,
  qWorkItemPath,
  QWorkLaneAnswerRequestSchema,
  qWorkLaneAnswerPath,
  QWorkLaneDtoSchema,
  qWorkLanePath,
  QWorkListDtoSchema,
  QWorkSlotSchema,
  QWorkStepDtoSchema,
  Q_WORK_LANE_REPORT_PATH,
  qWorkLaneReportPath,
  QWorkReportDtoSchema,
  type QWorkReportDto,
  Q_WORK_OUTREACH_START,
  Q_WORK_STANDIN_START,
  QWorkCallWindowSchema,
  QWorkOutreachGrantSchema,
  QWorkOutreachStartPayloadSchema,
  QWorkStandInGrantSchema,
  QWorkStandInStartPayloadSchema,
  type QWorkCallWindow,
  type QWorkOutreachGrant,
  type QWorkOutreachStartPayload,
  type QWorkStandInGrant,
  type QWorkStandInStartPayload,
  type QPresenceRequest,
  type QWorkAcceptedDto,
  type QWorkDetailDto,
  type QWorkDto,
  type QWorkLaneAnswerRequest,
  type QWorkLaneDto,
  type QWorkListDto,
  type QWorkSlot,
  type QWorkStepDto,
  Q_WORK_RUN_STATES,
  Q_WORK_PAUSED_BY_YOU,
  QWorkRunStateSchema,
  QWorkSpendSchema,
  type QWorkRunState,
  type QWorkSpend,
} from "./work.js";
// WORK-58: Q's work page (suggestions, pause/resume, done).
export {
  Q_WORK_DONE_PAGE_MAX,
  Q_WORK_DONE_PATH,
  Q_WORK_PAUSE_PATH,
  Q_WORK_RESUME_PATH,
  Q_WORK_DELEGATION_PATH,
  qWorkDelegationPath,
  Q_WORK_SUGGESTION_DISMISSALS_PATH,
  Q_WORK_SUGGESTION_KINDS,
  Q_WORK_SUGGESTIONS_MAX,
  Q_WORK_SUGGESTIONS_PATH,
  Q_WORK_SINCE_NAMES_MAX,
  Q_WORK_SINCE_PATH,
  QWorkActivityCountSchema,
  QWorkSinceDtoSchema,
  QWorkSinceQuerySchema,
  type QWorkActivityCount,
  type QWorkSinceDto,
  QWorkDoneItemDtoSchema,
  QWorkDonePageDtoSchema,
  QWorkDoneQuerySchema,
  qWorkPausePath,
  qWorkResumePath,
  QWorkSuggestionDismissRequestSchema,
  QWorkSuggestionDtoSchema,
  QWorkSuggestionKeySchema,
  QWorkSuggestionListDtoSchema,
  type QWorkDoneItemDto,
  type QWorkDonePageDto,
  type QWorkSuggestionDismissRequest,
  type QWorkSuggestionDto,
  type QWorkSuggestionKind,
  type QWorkSuggestionListDto,
} from "./work-page.js";
export { Q_USAGE_PATH, QUsageDtoSchema, type QUsageDto } from "./usage.js";
// end AUTO block

// DAILY block (The Q Daily, docs/specs/2026-10/daily.md)
export * from "./daily.js";
// end DAILY block

// BILLING-2 block (ADR 0036): the Capital Readiness Blueprint's contracts.
export * from "./readiness-blueprint.js";
// end BILLING-2 block

// READINESS block (Q.03/Q.04): the founder-private diagnosis and plan.
export * from "./readiness.js";
// end READINESS block

// WORKFORCE block (founder brief J1-J9): Q's workforce of agents.
export * from "./briefing-command.js";
export {
  Q_WORKFORCE_DRAFT_RETRY_PATH,
  qWorkforceDraftRetryPath,
  WorkforceDraftRetryRequestSchema,
  WorkforceDraftRetryResultDtoSchema,
  type WorkforceDraftRetryRequest,
  type WorkforceDraftRetryResultDto,
  Q_WORKFORCE_JOB_PATH,
  Q_WORKFORCE_JOBS_PATH,
  Q_WORKFORCE_OVERVIEW_PATH,
  Q_WORKFORCE_JOB_START,
  WorkforceJobStartPayloadSchema,
  WorkforcePlannedStepSchema,
  type WorkforceJobStartPayload,
  type WorkforcePlannedStep,
  WORKFORCE_AGENT_ROLES,
  WORKFORCE_TEAM_STATES,
  WORKFORCE_DRAFT_OUTCOMES,
  WORKFORCE_FEEDBACK_KINDS,
  WORKFORCE_JOB_SOURCES,
  WORKFORCE_JOB_STATUSES,
  WORKFORCE_RUN_STATUSES,
  WORKFORCE_TIMELINE_KINDS,
  WorkforceAgentRoleSchema,
  WorkforceAgentRunDtoSchema,
  WorkforceDraftDtoSchema,
  WorkforceGradeDtoSchema,
  WorkforceJobDetailDtoSchema,
  WorkforceJobListDtoSchema,
  WorkforceJobListQuerySchema,
  WorkforceJobSourceSchema,
  WorkforceJobSummaryDtoSchema,
  WorkforceReviewBarDtoSchema,
  WorkforceTimelineEntryDtoSchema,
  WorkforceOverviewDtoSchema,
  WORKFORCE_INSTRUCTION_STEP_STATUSES,
  WorkforceInstructionDtoSchema,
  WorkforceInstructionStepDtoSchema,
  type WorkforceInstructionDto,
  type WorkforceInstructionStepDto,
  qWorkforceJobPath,
  type WorkforceOverviewDto,
  type WorkforceAgentRunDto,
  type WorkforceDraftDto,
  type WorkforceJobDetailDto,
  type WorkforceJobListDto,
  type WorkforceJobSummaryDto,
  type WorkforceTimelineEntryDto,
} from "./workforce.js";
// end WORKFORCE block

// voice-cards: the person's Q room feed (every run's answer, any path).
export {
  Q_ROOM_HOLD_MS,
  Q_ROOM_KEPT,
  Q_ROOM_PATH,
  QRoomEntrySchema,
  QRoomReadQuerySchema,
  QRoomReadSchema,
  QRoomSourceSchema,
  type QRoomEntry,
  type QRoomRead,
  type QRoomReadQuery,
  type QRoomSource,
} from "./room.js";
