import { randomUUID } from "node:crypto";

import { z } from "zod";

import { createUuidIdSchema } from "@capital-q/contracts";

/**
 * The identity of one audit record. Generated by the application *before*
 * the write, so a retried command carries the same id and the unique index
 * makes the second write idempotent.
 *
 * Deliberately its own brand: an audit record is not a domain event, and the
 * two identifier spaces never mix.
 */
export const AuditEventIdSchema = createUuidIdSchema("AuditEventId");
export type AuditEventId = z.infer<typeof AuditEventIdSchema>;

export function createAuditEventId(): AuditEventId {
  return AuditEventIdSchema.parse(randomUUID());
}
