/**
 * Words the recogniser should expect (CQ-Q-VOICE-001 D §52, rework). The
 * interview vocabulary, and the names and places a Nigerian or wider West
 * African founder is likely to say: a recogniser mis-hears a name it has
 * never been told about far more often than an accent. Shared by every
 * speech transport.
 */
export const ASR_KEYWORDS: readonly string[] = [
  "Capital Q",
  "Vaultlyne",
  "MRR",
  "ARR",
  "pre-seed",
  "seed",
  "Series A",
  "Series B",
  "Lagos",
  "Nairobi",
  "Nigeria",
  "Ghana",
  "Kenya",
  "naira",
  "Abuja",
  "Port Harcourt",
  "Ibadan",
  "Yaba",
  "Lekki",
  "Accra",
  "Kigali",
  "Kampala",
  "Cairo",
  "Johannesburg",
  "Cape Town",
  "Paystack",
  "Flutterwave",
  "Moniepoint",
  "OPay",
  "Interswitch",
  "Jumia",
  "Andela",
  "Y Combinator",
  "angel",
  "pre-money",
  "post-money",
  "SAFE",
  "convertible note",
  "cheque size",
  "ticket size",
  "LP",
  "GP",
  "fund of funds",
  "family office",
  "pilot",
  "design partner",
  "churn",
  "runway",
  "burn",
  "gross margin",
  "take rate",
  "GMV",
  "fintech",
  "agritech",
  "healthtech",
  "edtech",
  "proptech",
  "insurtech",
  "logistics",
  "mobility",
  "SaaS",
  "B2B",
];
