-- CQ-MEDIA-TRANSCRIPT (R18) · A pitch's timed transcript.
--
-- The provider's generated captions for a READY pitch, kept as Capital Q's
-- own record so Q can answer "what did they say at 1:42?" and the player
-- can show captions. The transcript is part of the pitch, never a separate
-- disclosure: whoever may play the pitch may read it, and nobody else. No
-- row here grants anything; the media context authorises every read with
-- the same rule it uses to mint a playback token.
--
--   transcript ≠ evidence of the company's claims
--   generated text ≠ what was said, verbatim (it is labelled generated)
--
-- One row per asset and language, written once when the provider has it.
-- A regenerated transcript is a new asset's (a replaced pitch), never an
-- overwrite of this one.

create table media.pitch_transcripts (
  id                 uuid primary key default gen_random_uuid(),
  tenant_id          uuid not null references identity.tenants (id) on delete restrict,
  media_asset_id     uuid not null references media.media_assets (id) on delete cascade,
  -- BCP 47, as the provider names it.
  language           text not null check (language ~ '^[a-z]{2,3}(-[A-Za-z0-9]{2,8})*$'),
  -- Machine-generated by the video provider. Nothing else writes here yet.
  source             text not null check (source in ('PROVIDER_GENERATED')),
  -- Timed cues, [{ "startMs": int, "endMs": int, "text": string }], ordered.
  cues               jsonb not null check (
                       jsonb_typeof(cues) = 'array'
                       and jsonb_array_length(cues) <= 5000
                       and length(cues::text) <= 1048576),
  -- The WebVTT the player's <track> is served, as the provider produced it.
  vtt                text not null check (length(vtt) between 7 and 1048576),
  created_at         timestamptz not null default clock_timestamp(),
  constraint pitch_transcripts_one_per_language unique (media_asset_id, language)
);

comment on table media.pitch_transcripts is
  'A pitch''s timed, provider-generated transcript. Readable only by whoever may play the pitch, authorised by the media context on every read. Never evidence, never a disclosure of its own.';

create index pitch_transcripts_tenant_idx
  on media.pitch_transcripts (tenant_id, media_asset_id);

alter table media.pitch_transcripts enable row level security;
