-- ADMIN (docs/specs/2026-10/admin.md §6, ADR 0033): Capital Q's own
-- operations console -- operator roles, step-up, break-glass, account
-- suspensions, safety reviews, Q kill switches, firewall decision log and
-- email delivery log.
--
-- Everything here is INTERNAL_SERVER_ONLY: RLS on, no policy for any client
-- role, no grant to anon or authenticated. Only the server reaches these
-- tables, and only after it has decided the caller is a platform admin with
-- the permission (packages/platform-admin). Append-only except the current
-- value of a feature flag (each change is also appended to its history) and
-- a break-glass request, which is decided exactly once.

create schema if not exists platform_ops;
comment on schema platform_ops is
  'Capital Q operations: admin roles history, step-ups, console audit, suspensions, break-glass, safety reviews, kill switches, firewall decision log, email delivery log. Server-only.';

revoke all on schema platform_ops from public, anon, authenticated;
grant usage on schema platform_ops to postgres, service_role;

-- ---------------------------------------------------------------------------
-- Roles. The founder's existing row becomes platform_owner; later grants
-- must name a role (the default is dropped right after the backfill).
-- ---------------------------------------------------------------------------

alter table identity.platform_admins
  add column role text not null default 'platform_owner'
    check (role in ('platform_owner', 'operator', 'trust_and_safety', 'support', 'analyst')),
  add column granted_by uuid references identity.user_profiles (id) on delete restrict;
alter table identity.platform_admins alter column role drop default;

comment on column identity.platform_admins.role is
  'One operator role (reference values; permissions are the versioned code table ADMIN_PERMISSIONS in @capital-q/platform-admin).';

create table platform_ops.admin_role_events (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null references identity.user_profiles (id) on delete restrict,
  event           text not null check (event in ('GRANTED', 'CHANGED', 'REVOKED')),
  role            text check (role is null or role in
                    ('platform_owner', 'operator', 'trust_and_safety', 'support', 'analyst')),
  previous_role   text check (previous_role is null or previous_role in
                    ('platform_owner', 'operator', 'trust_and_safety', 'support', 'analyst')),
  actor_user_id   uuid not null references identity.user_profiles (id) on delete restrict,
  reason          text not null check (length(btrim(reason)) between 3 and 500),
  occurred_at     timestamptz not null default clock_timestamp(),
  check ((event = 'REVOKED') = (role is null)),
  check (event = 'GRANTED' or previous_role is not null),
  check (actor_user_id <> user_id)
);
create index admin_role_events_user_idx on platform_ops.admin_role_events (user_id, occurred_at desc);

-- ---------------------------------------------------------------------------
-- Step-up: a fresh re-authentication, verified by the API with the Auth
-- server, lets one admin perform sensitive actions for a short window.
-- ---------------------------------------------------------------------------

create table platform_ops.step_ups (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references identity.user_profiles (id) on delete restrict,
  method       text not null check (method in ('password', 'otp', 'totp')),
  verified_at  timestamptz not null default clock_timestamp(),
  expires_at   timestamptz not null,
  check (expires_at > verified_at and expires_at <= verified_at + interval '30 minutes')
);
create index step_ups_user_idx on platform_ops.step_ups (user_id, expires_at desc);

-- ---------------------------------------------------------------------------
-- The console's own audit: every action an admin takes, with the role they
-- held, the step-up and break-glass that allowed it, and the reason.
-- ---------------------------------------------------------------------------

create table platform_ops.admin_actions (
  id              bigint generated by default as identity primary key,
  event_id        uuid not null unique default gen_random_uuid(),
  actor_user_id   uuid not null references identity.user_profiles (id) on delete restrict,
  actor_role      text not null check (actor_role in
                    ('platform_owner', 'operator', 'trust_and_safety', 'support', 'analyst')),
  action_type     text not null check (action_type ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$' and length(action_type) <= 128),
  resource_type   text not null check (resource_type ~ '^[a-z][a-z0-9_]*$' and length(resource_type) <= 64),
  resource_id     text not null check (length(resource_id) between 1 and 200),
  reason          text check (reason is null or length(reason) <= 1000),
  step_up_id      uuid references platform_ops.step_ups (id) on delete restrict,
  break_glass_id  uuid,
  outcome         text not null check (outcome in ('SUCCEEDED', 'DENIED', 'FAILED')),
  metadata        jsonb not null default '{}'::jsonb
                    check (jsonb_typeof(metadata) = 'object' and octet_length(metadata::text) <= 16384),
  occurred_at     timestamptz not null default clock_timestamp()
);
create index admin_actions_time_idx on platform_ops.admin_actions (occurred_at desc, id desc);
create index admin_actions_actor_idx on platform_ops.admin_actions (actor_user_id, occurred_at desc);
create index admin_actions_resource_idx on platform_ops.admin_actions (resource_type, resource_id);

-- ---------------------------------------------------------------------------
-- Account suspensions. Current standing = the latest row for the person.
-- ---------------------------------------------------------------------------

create table platform_ops.account_suspensions (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references identity.user_profiles (id) on delete restrict,
  action         text not null check (action in ('SUSPENDED', 'UNSUSPENDED')),
  reason         text not null check (length(btrim(reason)) between 3 and 500),
  actor_user_id  uuid not null references identity.user_profiles (id) on delete restrict,
  occurred_at    timestamptz not null default clock_timestamp(),
  check (actor_user_id <> user_id)
);
create index account_suspensions_user_idx on platform_ops.account_suspensions (user_id, occurred_at desc, id);

-- ---------------------------------------------------------------------------
-- Break-glass: reading a private chat or a Q run's content needs a stated
-- reason and a second person's approval. SOLO approval (no other eligible
-- admin exists) is explicit and visible. Decided exactly once.
-- ---------------------------------------------------------------------------

create table platform_ops.break_glass_requests (
  id                  uuid primary key default gen_random_uuid(),
  requester_user_id   uuid not null references identity.user_profiles (id) on delete restrict,
  target_type         text not null check (target_type in ('RELATIONSHIP_CHAT', 'Q_RUN')),
  target_id           uuid not null,
  reason              text not null check (length(btrim(reason)) between 20 and 1000),
  status              text not null default 'PENDING' check (status in ('PENDING', 'APPROVED', 'DENIED')),
  approval_kind       text check (approval_kind is null or approval_kind in ('SECOND_PERSON', 'SOLO')),
  decided_by_user_id  uuid references identity.user_profiles (id) on delete restrict,
  decided_at          timestamptz,
  decision_note       text check (decision_note is null or length(btrim(decision_note)) between 3 and 500),
  expires_at          timestamptz,
  created_at          timestamptz not null default clock_timestamp(),
  check ((status = 'PENDING') = (decided_by_user_id is null and decided_at is null)),
  check ((status = 'APPROVED') = (approval_kind is not null and expires_at is not null)),
  check (approval_kind is distinct from 'SECOND_PERSON' or decided_by_user_id <> requester_user_id),
  check (approval_kind is distinct from 'SOLO' or decided_by_user_id = requester_user_id),
  check (status <> 'DENIED' or decided_by_user_id <> requester_user_id),
  check (expires_at is null or expires_at <= decided_at + interval '30 minutes')
);
create index break_glass_requests_status_idx on platform_ops.break_glass_requests (status, created_at);
create index break_glass_requests_target_idx on platform_ops.break_glass_requests (target_type, target_id);

create table platform_ops.break_glass_reads (
  id              bigint generated by default as identity primary key,
  request_id      uuid not null references platform_ops.break_glass_requests (id) on delete restrict,
  reader_user_id  uuid not null references identity.user_profiles (id) on delete restrict,
  items           integer not null check (items >= 0),
  occurred_at     timestamptz not null default clock_timestamp()
);
create index break_glass_reads_request_idx on platform_ops.break_glass_reads (request_id, occurred_at);

create or replace function platform_ops.break_glass_decide_once()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    raise exception 'platform_ops.break_glass_requests is never deleted'
      using errcode = 'restrict_violation';
  end if;
  if old.status <> 'PENDING'
     or new.id <> old.id
     or new.requester_user_id <> old.requester_user_id
     or new.target_type <> old.target_type
     or new.target_id <> old.target_id
     or new.reason <> old.reason
     or new.created_at <> old.created_at then
    raise exception 'a break-glass request is decided once and never rewritten'
      using errcode = 'restrict_violation';
  end if;
  return new;
end;
$$;

create trigger break_glass_requests_decide_once
  before update or delete on platform_ops.break_glass_requests
  for each row execute function platform_ops.break_glass_decide_once();

-- ---------------------------------------------------------------------------
-- Safety reviews of R34 reports. The report row is communication's; the
-- review history is operations'. Effective review = latest row.
-- ---------------------------------------------------------------------------

create table platform_ops.report_reviews (
  id                uuid primary key default gen_random_uuid(),
  report_id         uuid not null references communication.reports (id) on delete restrict,
  reviewer_user_id  uuid not null references identity.user_profiles (id) on delete restrict,
  outcome           text not null check (outcome in ('NO_ACTION', 'WARNED', 'ACCOUNT_SUSPENDED', 'ESCALATED')),
  note              text not null check (length(btrim(note)) between 3 and 1000),
  occurred_at       timestamptz not null default clock_timestamp()
);
create index report_reviews_report_idx on platform_ops.report_reviews (report_id, occurred_at desc);

-- ---------------------------------------------------------------------------
-- Kill switches for Q autonomy and the Q Daily. On by default; turning one
-- off stops new steps. Every change is appended to the history.
-- ---------------------------------------------------------------------------

create table platform_ops.feature_flags (
  key          text primary key check (key ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$' and length(key) <= 64),
  enabled      boolean not null,
  description  text not null check (length(description) between 1 and 300),
  updated_by   uuid references identity.user_profiles (id) on delete restrict,
  reason       text check (reason is null or length(btrim(reason)) between 3 and 500),
  updated_at   timestamptz not null default clock_timestamp(),
  check ((updated_by is null) = (reason is null))
);

create table platform_ops.feature_flag_events (
  id             bigint generated by default as identity primary key,
  key            text not null references platform_ops.feature_flags (key) on delete restrict,
  enabled        boolean not null,
  actor_user_id  uuid not null references identity.user_profiles (id) on delete restrict,
  reason         text not null check (length(btrim(reason)) between 3 and 500),
  occurred_at    timestamptz not null default clock_timestamp()
);
create index feature_flag_events_key_idx on platform_ops.feature_flag_events (key, occurred_at desc);

insert into platform_ops.feature_flags (key, enabled, description) values
  ('q.autonomy.errands', true, 'Let Q handle this: errands Q runs on a person''s one approval (ADR 0028).'),
  ('q.autonomy.delegations', true, 'Standing delegations Q carries out on events without asking each time (ADR 0030).'),
  ('q.daily', true, 'The Q Daily: generating each person''s edition and emailing it.');

-- ---------------------------------------------------------------------------
-- Context Firewall decisions, codes only: what Q was allowed to consider
-- for a run and what it was refused. No text, no content.
-- ---------------------------------------------------------------------------

create table platform_ops.q_firewall_decisions (
  id                bigint generated by default as identity primary key,
  tenant_id         uuid references identity.tenants (id) on delete restrict,
  user_id           uuid,
  run_id            uuid,
  correlation_id    text check (correlation_id is null or length(correlation_id) between 1 and 128),
  capability        text not null check (capability ~ '^[A-Z][A-Z_]{0,31}$'),
  outcome           text not null check (outcome in ('AUTHORISED', 'DENIED')),
  reason            text check (reason is null or reason ~ '^[A-Z][A-Z_]{0,63}$'),
  allowed_labels    text[] not null default '{}' check (cardinality(allowed_labels) <= 64),
  denied            jsonb not null default '[]'::jsonb
                      check (jsonb_typeof(denied) = 'array' and octet_length(denied::text) <= 8192),
  occurred_at       timestamptz not null default clock_timestamp()
);
create index q_firewall_decisions_run_idx on platform_ops.q_firewall_decisions (run_id) where run_id is not null;
create index q_firewall_decisions_time_idx on platform_ops.q_firewall_decisions (occurred_at desc);

-- ---------------------------------------------------------------------------
-- Capital Q's own emails: outcome per send. Recipient domain and a hash
-- only -- never the address, subject or body.
-- ---------------------------------------------------------------------------

create table platform_ops.email_deliveries (
  id                bigint generated by default as identity primary key,
  source            text not null check (source ~ '^[a-z][a-z0-9_.]{1,63}$'),
  provider          text not null check (provider in ('BREVO_API', 'SMTP')),
  outcome           text not null check (outcome in ('SENT', 'FAILED')),
  error_class       text check (error_class is null or error_class ~ '^[A-Z0-9_]{1,32}$'),
  recipient_domain  text not null check (length(recipient_domain) between 1 and 253),
  recipient_hash    text not null check (recipient_hash ~ '^[0-9a-f]{64}$'),
  occurred_at       timestamptz not null default clock_timestamp(),
  check ((outcome = 'FAILED') = (error_class is not null))
);
create index email_deliveries_time_idx on platform_ops.email_deliveries (occurred_at desc);

-- ---------------------------------------------------------------------------
-- Append-only guard for the ledgers.
-- ---------------------------------------------------------------------------

create or replace function platform_ops.append_only()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception '%.% is append-only', tg_table_schema, tg_table_name
    using errcode = 'restrict_violation';
end;
$$;

create trigger admin_role_events_append_only before update or delete on platform_ops.admin_role_events
  for each row execute function platform_ops.append_only();
create trigger step_ups_append_only before update or delete on platform_ops.step_ups
  for each row execute function platform_ops.append_only();
create trigger admin_actions_append_only before update or delete on platform_ops.admin_actions
  for each row execute function platform_ops.append_only();
create trigger account_suspensions_append_only before update or delete on platform_ops.account_suspensions
  for each row execute function platform_ops.append_only();
create trigger break_glass_reads_append_only before update or delete on platform_ops.break_glass_reads
  for each row execute function platform_ops.append_only();
create trigger report_reviews_append_only before update or delete on platform_ops.report_reviews
  for each row execute function platform_ops.append_only();
create trigger feature_flag_events_append_only before update or delete on platform_ops.feature_flag_events
  for each row execute function platform_ops.append_only();
create trigger q_firewall_decisions_append_only before update or delete on platform_ops.q_firewall_decisions
  for each row execute function platform_ops.append_only();
create trigger email_deliveries_append_only before update or delete on platform_ops.email_deliveries
  for each row execute function platform_ops.append_only();

revoke all on function platform_ops.append_only() from public;
revoke all on function platform_ops.break_glass_decide_once() from public;

-- ---------------------------------------------------------------------------
-- Protection.
-- ---------------------------------------------------------------------------

alter table platform_ops.admin_role_events     enable row level security;
alter table platform_ops.step_ups              enable row level security;
alter table platform_ops.admin_actions         enable row level security;
alter table platform_ops.account_suspensions   enable row level security;
alter table platform_ops.break_glass_requests  enable row level security;
alter table platform_ops.break_glass_reads     enable row level security;
alter table platform_ops.report_reviews        enable row level security;
alter table platform_ops.feature_flags         enable row level security;
alter table platform_ops.feature_flag_events   enable row level security;
alter table platform_ops.q_firewall_decisions  enable row level security;
alter table platform_ops.email_deliveries      enable row level security;

revoke all on all tables in schema platform_ops from public, anon, authenticated;
grant select, insert, update, delete on all tables in schema platform_ops to postgres, service_role;
grant usage, select on all sequences in schema platform_ops to postgres, service_role;
