-- Credit ledger groundwork (lead 2026-10-03: "add cost and billing little
-- by little"). Additive and inert: nothing writes a price, nothing is
-- charged, no provider is called. Each entry is a quantity of a metered
-- unit for an account, with money as numeric plus an ISO currency, and
-- the rate left unset (RATE_NOT_SET) until the founder sets one. Stripe
-- Billing Meters can later be fed from these rows through the outbox; the
-- export is recorded in its own table then, so entries stay append-only.

create table billing.credit_entries (
  id               bigint generated by default as identity primary key,
  organisation_id  uuid references identity.organisations (id) on delete restrict,
  user_id          uuid references identity.user_profiles (id) on delete restrict,
  account_key      text generated always as (
                     case when organisation_id is not null
                          then 'o:' || organisation_id::text
                          else 'p:' || user_id::text end) stored,
  -- What happened: usage taken from the account, credit granted to it, or a
  -- correction of an earlier entry (by reference; never an edit).
  kind             text not null check (kind in ('USAGE', 'GRANT', 'ADJUSTMENT')),
  -- The metered unit, e.g. MODEL_COST_USD (Q's model cost passed through).
  unit             text not null check (unit ~ '^[A-Z][A-Z0-9_]{1,63}$'),
  -- Signed: USAGE is negative, GRANT positive; never a float.
  quantity         numeric(20, 8) not null check (quantity <> 0),
  rate_status      text not null default 'RATE_NOT_SET'
                     check (rate_status in ('RATE_NOT_SET', 'RATED')),
  -- The price per unit and the money, only once a rate is set.
  unit_rate        numeric(20, 8) check (unit_rate is null or unit_rate >= 0),
  amount           numeric(20, 8),
  currency         char(3) not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  -- Where it came from and its idempotency: one entry per source event.
  source           text not null check (source ~ '^[A-Z][A-Z0-9_]{1,63}$'),
  source_ref       text not null check (length(source_ref) between 3 and 200),
  -- The ADJUSTMENT's earlier entry.
  corrects_id      bigint references billing.credit_entries (id) on delete restrict,
  -- The Stripe Billing Meter event name it will feed, when one is chosen.
  meter_event_name text check (meter_event_name is null or meter_event_name ~ '^[a-z][a-z0-9_]{1,99}$'),
  occurred_at      timestamptz not null,
  created_at       timestamptz not null default clock_timestamp(),
  check (num_nonnulls(organisation_id, user_id) = 1),
  check ((rate_status = 'RATE_NOT_SET') = (unit_rate is null and amount is null)),
  check (rate_status = 'RATE_NOT_SET' or (unit_rate is not null and amount is not null)),
  check ((kind = 'ADJUSTMENT') = (corrects_id is not null)),
  unique (source, source_ref)
);

comment on table billing.credit_entries is
  'Append-only credit ledger groundwork: signed quantities of a metered unit per account, numeric money plus ISO currency once a rate is set (RATE_NOT_SET until then), idempotent per source event. Inert: nothing is priced or charged from it yet.';

create index credit_entries_account_idx
  on billing.credit_entries (account_key, occurred_at desc);

create trigger credit_entries_append_only
  before update or delete on billing.credit_entries
  for each row execute function billing.append_only();

-- Server-only, like the rest of billing.
alter table billing.credit_entries enable row level security;
revoke all on billing.credit_entries from public, anon, authenticated;
grant select, insert on billing.credit_entries to service_role;
grant usage, select on sequence billing.credit_entries_id_seq to service_role;
