-- CQ-SEC-003 · Audit infrastructure
--
-- Durable, append-oriented accountability: who acted, under whose authority,
-- in which tenant/organisation, what they did, to which resource, when, and
-- with what outcome. Two tables with different semantics:
--
--   audit.material_actions   accountability for material actions
--   audit.security_events    security monitoring events (often no mutation)
--
-- Audit history ≠ Q memory ≠ domain event ≠ analytics ≠ operational log.
-- Rows are historical facts: no updated_at, no version, and no client role
-- may UPDATE or DELETE. Governed retention remains possible for the
-- privileged owner; ordinary application paths cannot rewrite history.

create schema if not exists audit;
comment on schema audit is
  'Append-oriented accountability records. Server-only; never exposed through the Data API; no client role may read or mutate.';
revoke all on schema audit from public;

-- ---------------------------------------------------------------------------
-- audit.material_actions
-- ---------------------------------------------------------------------------

create table audit.material_actions (
  -- Internal storage/ordering key only; never the cross-boundary identity.
  id                 bigint generated by default as identity primary key,
  -- AuditEventId, generated by the application before the write so a retried
  -- command cannot create a second record.
  event_id           uuid not null unique,
  tenant_id          uuid not null references identity.tenants (id) on delete restrict,
  -- Persisted actor vocabulary (doc 13 §50): the application ActorType maps
  -- onto it through one explicit adapter.
  actor_type         text not null check (actor_type in ('human', 'q', 'capital_q_system', 'connected_system')),
  -- Meaning depends on actor_type: a UserId for humans; a future Q
  -- action/run identity for Q; a stable internal or connector identity
  -- otherwise. Never a credential or provider name.
  actor_id           uuid,
  -- The human whose authority the action was performed under. Distinct from
  -- the actor: Q acting under David's approval records actor = q,
  -- authority = David.
  authority_user_id  uuid references identity.user_profiles (id) on delete restrict,
  -- The organisation context the actor was acting for AT THE TIME. Persisted,
  -- never looked up later: if the person changes organisation, history stays.
  organisation_id    uuid references identity.organisations (id) on delete restrict,
  action_type        text not null check (action_type ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$' and length(action_type) <= 128),
  resource_type      text not null check (resource_type ~ '^[a-z][a-z0-9_]*$' and length(resource_type) <= 64),
  -- Opaque reference. Text rather than uuid so connected-system and provider
  -- resources can be audited; never human-readable private content.
  resource_id        text not null check (length(resource_id) between 1 and 200),
  -- Doc 13 extension point; the canonical relationship arrives with CQ-NET-001.
  relationship_id    uuid,
  occurred_at        timestamptz not null,
  outcome            text not null check (outcome in ('SUCCEEDED', 'FAILED', 'DENIED')),
  -- Small, safe, structured references only (validated by the application;
  -- ceiling enforced here as a backstop). Never payloads, documents,
  -- prompts, tokens or secrets.
  metadata           jsonb not null default '{}'::jsonb
                       check (jsonb_typeof(metadata) = 'object' and octet_length(metadata::text) <= 16384),
  correlation_id     uuid,
  -- A human acts as themself: actor required, authority is the actor. A
  -- delegated-authority model, when it exists, relaxes this explicitly.
  check (actor_type <> 'human' or (actor_id is not null and authority_user_id = actor_id)),
  -- Q never performs a material action without a human authority reference.
  check (actor_type <> 'q' or authority_user_id is not null)
);

comment on table audit.material_actions is
  'Append-oriented accountability for material actions. Corrections are new records; nothing here is updated or deleted by application code.';

create index material_actions_tenant_time_idx
  on audit.material_actions (tenant_id, occurred_at desc);
create index material_actions_organisation_time_idx
  on audit.material_actions (organisation_id, occurred_at desc)
  where organisation_id is not null;
create index material_actions_actor_time_idx
  on audit.material_actions (actor_id, occurred_at desc)
  where actor_id is not null;
create index material_actions_resource_time_idx
  on audit.material_actions (resource_type, resource_id, occurred_at desc);
create index material_actions_action_time_idx
  on audit.material_actions (action_type, occurred_at desc);
create index material_actions_correlation_idx
  on audit.material_actions (correlation_id)
  where correlation_id is not null;
create index material_actions_authority_idx
  on audit.material_actions (authority_user_id)
  where authority_user_id is not null;

-- ---------------------------------------------------------------------------
-- audit.security_events
-- ---------------------------------------------------------------------------

create table audit.security_events (
  id               bigint generated by default as identity primary key,
  event_id         uuid not null unique,
  tenant_id        uuid references identity.tenants (id) on delete restrict,
  user_id          uuid references identity.user_profiles (id) on delete restrict,
  event_type       text not null check (event_type ~ '^[a-z][a-z0-9_]*$' and length(event_type) <= 64),
  severity         text not null check (severity in ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  resource_type    text check (resource_type is null or (resource_type ~ '^[a-z][a-z0-9_]*$' and length(resource_type) <= 64)),
  resource_id      text check (resource_id is null or length(resource_id) between 1 and 200),
  occurred_at      timestamptz not null,
  -- Pseudonymous network identifiers only. Raw IP / user agent are never
  -- accepted by the writer.
  ip_hash          text check (ip_hash is null or length(ip_hash) between 8 and 128),
  user_agent_hash  text check (user_agent_hash is null or length(user_agent_hash) between 8 and 128),
  metadata         jsonb not null default '{}'::jsonb
                     check (jsonb_typeof(metadata) = 'object' and octet_length(metadata::text) <= 16384),
  correlation_id   uuid
);

comment on table audit.security_events is
  'Security monitoring events (denials, firewall blocks, suspected injection, rate limits). Separate semantics from material actions; append-oriented.';

create index security_events_tenant_time_idx
  on audit.security_events (tenant_id, occurred_at desc)
  where tenant_id is not null;
create index security_events_user_time_idx
  on audit.security_events (user_id, occurred_at desc)
  where user_id is not null;
create index security_events_type_time_idx
  on audit.security_events (event_type, occurred_at desc);
create index security_events_severity_time_idx
  on audit.security_events (severity, occurred_at desc);
create index security_events_resource_time_idx
  on audit.security_events (resource_type, resource_id, occurred_at desc)
  where resource_id is not null;
create index security_events_correlation_idx
  on audit.security_events (correlation_id)
  where correlation_id is not null;

-- ---------------------------------------------------------------------------
-- Access posture: no client role reads, inserts, updates or deletes audit
-- rows. Audit is written by the server inside business transactions and,
-- when read surfaces exist, will be read through capability-controlled
-- APIs. RLS is enabled with no policies as the second layer.
-- ---------------------------------------------------------------------------

alter table audit.material_actions enable row level security;
alter table audit.security_events enable row level security;
